### PR TITLE
Fix a couple more corner cases when using zlib-ng

### PR DESCRIPTION
**Pull request by kcgen**
# Description

- Adds `-mfpu=neon` flag to zlib-ng's CMake arguments, otherwise it fails to use Neon even when native optimizations are requested (affects gcc on arm Linux platforms).
- Drops the `auto / system / built-in` options for zlib-ng in favour of Meson's standardized wrap fallback controls (`--wrap-mode` and `--force-fallback-for=[list]`)
- Fixes a small `CFLAG` vs. `LDFLAG` typo.
- Fixes zlib-ng not being enabled for MSYS2 builds (now it is).

## Related issues

https://github.com/zlib-ng/zlib-ng/issues/1621

# Manual testing

Tested on the Pi 4, x86-64, Apple M1, and confirmed zlib-ng is being built and used under MSYS2.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by johnnovak — APPROVED** [review]
Noice 👍🏻

**Comment by kcgen** [comment]
With 0.82 now in place; merging.

**Comment by weirddan455** [comment]
It seems zlib-ng is disabled by default now.  My system zlib is plain old (slow) zlib.  Is that intentional?

```
  Build Summary
    Build type            : debug
    Install prefix        : /usr/local
    SIMD instruction set  : SSE2 and SSSE3
    Host page size (bytes): 4096

    zlib provider         : system library
```

I believe prior to this PR, it was installing zlib-ng from the meson wrap.  I realize I could use a flag to force wrap fallback soi f this is intended, all good.  Just wanted to confirm.

**Comment by kcgen** [comment]
@weirddan455, yes, we only go through the extra work of setting up zlib-ng for optimized build.  I started to write more here explaining why and decided instead to codify it with feedback in Meson file (because, no doubt, others will wonder why, too).

The new PR will give this feedback in your case:

```
  Build Summary
    Build type            : debug
    Install prefix        : /usr/local
    SIMD instruction set  : SSE2 and SSSE3
    Host page size (bytes): 4096

    zlib-ng provider      : skipped (non-optimized build)
    zlib provider         : system library
    PNG provider          : system library
    SpeexDSP provider     : system library
```

And I've added this comment in the meson.build file:

``` text
# The zlib-ng wrap, on the other hand, is a costly endeavour because it
# single-handledly quadruples the 'meson setup' time for the entire project (6.1s
# to 25.8s) due to the use of the much slower CMake build system, therefore we
# only expend this effort (to optimize zlib) for comensurate optimized builds.
# This nuance is also explained in meson_options.txt for packagers.
```

To benchmark your own builds:

```
git clean -ffdx; time meson setup build

git clean -ffdx; time meson setup -Dbuildtype=debug -Dunit_tests=disabled build
```

**Pull request merged**
