### PR TITLE
Fix a boundary check when reading the GUS volume register

### PR DESCRIPTION
**Pull request by kcgen**
Also adds the GUS Enhancements to README's table of changes.
GUS emulation is now re-passing the full set of regression games and programs.

### CODE REVIEW

**Comment by kcgen** [comment]
Thanks for the quick report on this @dreamer; and very sorry for the hiccup!

**Review by dreamer — APPROVED** [review]
There's a typo in the first commit, I'll fix it while merging.

**Comment by kcgen** [comment]
Thanks for the quick merge and typo-fix!

**Comment by dreamer** [comment]
Merged in 5404322a946aa8deaf6827283399b62152929931 - thanks! :)

**Pull request closed without merging**
