### PR TITLE
Sync CD-audio codecs with upstream

### PR DESCRIPTION
**Pull request by kcgen**
This also tentatively fixes some of the issues flagged by LGTM.

### CODE REVIEW

**Comment by kcgen** [comment]
Pending changes:
 - dr_wav confirmed upstream on dev branch. Will be promoted to release.
 - dr_flac pending review of suggestion from @dreamer 
 - dr_mp3, upstream (minimp3) has fixed it. Change will now be pulled into dr_mp3, promoted for release, and then added to this PR.

**Comment by kcgen** [comment]
All codecs updated to release versions.
Moving PR our of draft state.

**Review by dreamer — APPROVED** [review]
@kcgen Thanks for tracking dr_libs release :)

**Comment by kcgen** [comment]
Rock n' roll fellas :-)
Warnings are falling fast.

**Pull request merged**
