### PR TITLE
Check the validity of leading path when checking device name

### LINKED ISSUE #3517: Alpha Storm install script fails to create directories
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The installer for Alpha Storm is just a .bat file.  It contains the following snippet to create new directories if they don't already exist:

```
IF EXIST %1\NUL GOTO D1
MD %1
IF NOT EXIST %1\NUL GOTO FAILURE
:D1
IF NOT EXIST %1\MONS\NUL	MD %1\MONS
IF NOT EXIST %1\OLD_ONES\NUL	MD %1\OLD_ONES
IF NOT EXIST %1\PACS\NUL	MD %1\PACS
IF NOT EXIST %1\SOUNDS\NUL	MD %1\SOUNDS
IF NOT EXIST %1\SPAM\NUL	MD %1\SPAM
IF NOT EXIST %1\SPAM\BASE\NUL	MD %1\SPAM\BASE
IF NOT EXIST %1\SPAM\DARK\NUL	MD %1\SPAM\DARK
IF NOT EXIST %1\SPAM\IMP\NUL	MD %1\SPAM\IMP
IF NOT EXIST %1\SPAM\VARG\NUL	MD %1\SPAM\VARG
IF NOT EXIST %1\SPAM\PIR\NUL	MD %1\SPAM\PIR
IF NOT EXIST %1\TEXAS\NUL	MD %1\TEXAS
IF NOT EXIST %1\YARDS\NUL	MD %1\YARDS
```
The directories fail to get created.  I wrote a stand-alone script to reproduce the problem.  Copy this to `test.bat` and run `test foo`.  Expected result is `C:\FOO` gets created and then `C:\FOO\BAR`.  Instead neither gets created.

```
IF NOT EXIST %1\NUL MD %1
IF NOT EXIST %1\BAR\NUL MD %1\bar
```

I debugged the code starting from `CMD_IF` and the problem is it's matching to a DOS device called `NUL` and returning that the path does exist even when `C:\FOO` does not exist.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Run the Alpha Storm install.bat or my 2 line repro script.
2.  Directories do not get created as expected.

### Download URL of affected game or software

https://www.myabandonware.com/game/alpha-storm-bh2

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

Fixes a bug with the Alpha Storm batch file installer which depends on checks like: `IF EXIST %1\NUL`

This is a revert of r4475 from DOSBox SVN
Partial revert of the merge commit c5f2bfe233edf71be0874f113c796bf01d1bf3c7

https://sourceforge.net/p/dosbox/code-0/4475/tree//dosbox/trunk/src/dos/dos_devices.cpp?diff=5049d97e71b75b3379a0122d:4474

## Related issues

Fixes #3517

# Manual testing

It fixes the Alpha Storm installer.  The commit claims to fix World Series of Poker installer.  That's a Windows 3.1 game though and I don't have that setup.  Possible regression there but do we even support Windows games?

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
> It fixes the Alpha Storm installer. The commit claims to fix World Series of Poker installer. That's a Windows 3.1 game though and I don't have that setup. Possible regression there but do we even support Windows games?

Yes @weirddan455, Win3.x games are definitely in scope. I should clarify this on our about page. Technically, Win3.x is a DOS program 😄 

It would be good to backport this, but we need to ensure we're not breaking something else. You could always test the real MS-DOS behaviour in VirtualBox/PCem/86box, or even Staging can boot real MS-DOS from mounted hard drive images (img format).

You can get most Win3.x games from eXoWin3.x:
https://www.retro-exo.com/index2.html

**Comment by weirddan455** [comment]
The installer for this game seems to work correctly:  https://archive.org/details/WSOPDLEX

I can't actually play the game after it's installed though because I'm having trouble switching to 256 color mode.  When I try to change it by Windows setup.exe it results in a completely garbled image.

image0001

**Comment by weirddan455** [comment]
Scratch that, the game works.  I found instructions to install video drivers in the wiki.  I'm not sure what else needs to be tested here.  I can't reproduce the bug the original SVN commit claimed to solve.

image0002

**Comment by johnnovak** [comment]
Thanks for the thorough testing @weirddan455. It's entirely possible some of our other enhancements compared to SVN cancels that old bug out.

**Review by johnnovak — APPROVED** [review]
Nice one @weirddan455 🥳

**Pull request merged**
