### PR TITLE
Fix empty mapperfile on start-up

### LINKED ISSUE #873: Git master can't save mapper file (bisected)
**Describe the bug**
Trying to save a mapper file results in the error message: `MAPPER: Can't open  for saving the key bindings`

**To Reproduce**
I've tested this with an empty config. Open up the mapper, make a change and click save.

**Environment (please complete the following information):**
Arch Linux

**Version of dosbox-staging:**

`v0.77.0-alpha-334-g77862ab8`

**Configuration parameters:**
Confirmed with the default/empty config file and no existing mapper.

**Additional context**
Git bisect points to b0ef7b34adcb5e104be39fae04482b62c8b5242d introducing this issue. Reverting the commit seems to resolve the issue.

### PR DESCRIPTION
**Pull request by kcgen**
Fixes #873. Thank you to @BPaden for reporting and testing!

### CODE REVIEW

**Review by dreamer — COMMENTED** [review]
This needs more testing… Judging by the code I think it breaks loading the mapperfile on start?

**Review by dreamer — CHANGES_REQUESTED** [review]
OK, it does not break loading of mapperfile *on start*. 

But it breaks changing the mapperfice via `config -set "sdl mapperfile=file.map"`, so we need another solution.

**Comment by kcgen** [comment]
> OK, it does not break loading of mapper file _on start_.
> 
> But it breaks changing the mapper file via `config -set "sdl mapperfile=file.map"`, so we need another solution.

The mapper's Init() function will be re-run on a load.  And @bpaden reported:

> 

Hmm I suspect the first one is being eaye

**Comment by BPaden** [comment]
Yep, looks like you have to type the command out twice. I somehow didn't notice this yesterday. I must have thought I had a typo or something. 😅

**Comment by kcgen** [comment]
> Yep, looks like you have to type the command out twice. I somehow didn't notice this yesterday. I must have thought I had a typo or something. sweat_smile

Thank you for this follow up @BPaden - You're both right - and makes perfect sense in the code :-)
Try two inbound shortly.

**Comment by kcgen** [comment]
Ready for testing! The code is simpler and safer now.
It would have been a net-reduction in LOC count too, if it weren't for some re-formatting and white-space.

Tested with:
 - `-startmapper`GUI on startup
 - `mapperfile = ...` via in conf
 - `mapperfile = ` and `config -set "sdl mapperfile=...` on the DOS command-line

**Comment by BPaden** [comment]
I have found no issues. :)

**Review by dreamer — APPROVED** [review]
Unfortunately, I don't have a joystick nearby so can't test, but I see nothing in here that would break #219 again. Let's merge this in (and if someone has a controller nearby - please test if it still works after this change).

@BPaden @kcgen Thank you!

**Comment by kcgen** [comment]
Thanks for the quick review on this @dreamer .

**Pull request merged**
