### PR TITLE
Make GCC 11 / Ubuntu 22.04 the minimum build target

### PR DESCRIPTION
**Pull request by johnnovak**
# Description

As we discussed today, let's move the minimum GCC version forward to 11 on Linux. That means bumping the GCC version of the "minimal build" target from 9 to 11. Staying on 9 just makes it a lot harder to use the nice new C++20 features. Supporting the last 2 Ubuntu LTS releases seems like a good approach; 3 is perhaps pushing it a little bit.

People who desire to compile Staging on legacy systems are welcome to check out an earlier release tag; those will still build with GCC 9, 10, etc.

Some notes:

- The ARMv7, ppc64 and aarch64 targets seem to use some custom Docker image created by kcgen if I'm not mistaken to cross-compile Staging for those platforms. I haven't touched those, neither am I going to. Feel free to tinker with them or maintain them if they're important for you, otherwise they will be disabled / removed the first time they cause a nuissance.
- We should eventually add a new 24.04 target; Linux guys, please step forward 😎 

# Relates issues

The below PR can only go in after this because of some C++20 features that are unsupported on GCC 9:

- https://github.com/dosbox-staging/dosbox-staging/pull/3650

# Manual testing

None.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by FeralChild64 — APPROVED** [review]
Looks OK. GCC 11 is, IMHO, a reasonable minimum.

**Comment by shermp** [comment]
I'm the creator of the Linux Docker images. It's easy enough to bump the debian versions as required to maintain compatibility. I think they're useful to keep (especially the ARM ones) to ensure we aren't introducing new code that stops those archs from compiling.

**Comment by johnnovak** [comment]
> I'm the creator of the Linux Docker images. It's easy enough to bump the debian versions as required to maintain compatibility. I think they're useful to keep (especially the ARM ones) to ensure we aren't introducing new code that stops those archs from compilingI.

Thanks for volunteering 👍🏻 Yes my preference if to keep them, especially the ARM ones, like you said. I just did not want to fall into the Docker image generation rabbit hole, I've never done that before.

Can you please raise a separate PR for this and create some succinct documentation about upgrading/maintaining those Docker cross-compile images? That would be great because of the bus factor, etc. 😏

**Comment by shermp** [comment]
> Can you please raise a separate PR for this and create some succinct documentation about upgrading/maintaining those Docker cross-compile images? That would be great because of the bus factor, etc. 😏

I was thinking this morning about how to improve (and simplify?) the docker image creation and tagging. I'm thinking of switching to scheme of something like `debian-cross:<deb_vers>-<arch>-<checksum of dockerfile and apt sources>`, and maybe (manual?) dosbox tagged versions for posterity.

**Comment by johnnovak** [comment]
> I was thinking this morning about how to improve (and simplify?) the docker image creation and tagging. 

The build system needs a lot of simplifications, we all agree on that, so yeah, go for it.

> I'm thinking of switching to scheme of something like `debian-cross:<deb_vers>-<arch>-<checksum of dockerfile and apt sources>`, 

That sounds like an improvement.

> and maybe (manual?) dosbox tagged versions for posterity.

You mean archieve snapshots of these Docker images whenever a tag is pushed? That is a good idea. Just be aware it will need to handle tag deletions & recreations as well (I "push forward" the release tag a lot when preparing a release).

Alternatively, if you don't want to automate this, the snapshotting could be a final one-time manual process done right after a public release.

**Pull request merged**
