### PR TITLE
DOSBox-X: Backport Tandy DAC anti-pop fixes and DMA controller fix for Prince of Persia

### PR DESCRIPTION
**Pull request by joncampbell123**

### CODE REVIEW

**Comment by dreamer** [comment]
@joncampbell123 thanks :) Can you shed some light on the usecase or bug that is being fixed by this commit?

I started Prince of Persia configured to run with:
- Sound: Tandy Sound
- Music: Tandy 3-voice

With dosbox-staging configured with:
```
[speaker]
pcspeaker = true
pcrate = 44100
tandy = on
tandyrate = 44100
```
I let the music play through the intro and played part of the first level. I can't tell the difference.

Maybe I missed something?

Also: we don't want the first commit (git commit tool); we have no use for it.

And, it's not finished yet (still WIP, as I worked on other tasks), but can you take a look at our [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/po/contributing-2/CONTRIBUTING.md#contributing-code), especially at part about [commit messages](https://github.com/dosbox-staging/dosbox-staging/blob/po/contributing-2/CONTRIBUTING.md#commit-messages).

**Comment by joncampbell123** [comment]
The git script was an accident,

Run Prince of Persia with machine=tandy.

When it uses the Tandy DAC for sound effects, the sound effects end with a loud pop because they don't end at DC zero (sample value 128).

On real Tandy 1000 hardware I have lying around, the pop is not audible, but there is some slight DAC noise that suggests when the DAC is turned off it decays to zero quickly.

This patch changes the behavior so that when the DAC is turned off after the sound effect, it renders the silence as the last sample sent decaying to zero for the same reason, which eliminates the popping noise and more closely follows apparent hardware behavior.

**Comment by joncampbell123** [comment]
I can also provide a video capture of actual Tandy 1000 TL/3 hardware while playing Prince of Persia to show what I mean, captured through an MCE2VGA and a VGA capture card with audio captured from the Tandy's headphone jack.

**Comment by dreamer** [comment]
Uff, finally had a moment to check this again.

@joncampbell123 Thank you for the thorough explanation, now I can reproduce the popping sound loud and clear - yeah, it is extremely annoying and definitely a bug.

The bad news is: your patch does not affect the output in dosbox-staging (at least with my .conf file, but it should not make a difference) - I spent some time testing various settings if I can trigger it and didn't succeed.

But the problem does not seem to be in the patch - it looks like that code is not being triggered any more *at all* - I hear the sound effects in-game (steps and such), but DAC-related functions in tandy_sound.cpp are not being triggered. 

I compared how different this code area is in DOSBox-X and dosbox-staging - and no, there are no big differences. I applied your patch to svn/trunk - and the same way, the code is not being triggered.

I suspect upstream introduced some regressions in this area, and DOSBox-X did not merge the breaking changes, so this code works as it was supposed to on your side, while we inherited the regression. I'll update the issue as I'll find out more.

**Comment by kcgen** [comment]
Taking a look at this issue now, and noticed some bugs in TandyDACGenerateDMASound. 

```
static void TandyDACGenerateDMASound(Bitu length) {
	if (length) {
		Bitu read=tandy.dac.dma.chan->Read(length,tandy.dac.dma.buf);
		tandy.dac.chan->AddSamples_m8(read,tandy.dac.dma.buf);
		if (read < length) {
			if (read>0) tandy.dac.dma.last_sample=tandy.dac.dma.buf[read-1];
			for (Bitu ct=read; ct < length; ct++) {
				tandy.dac.chan->AddSamples_m8(1,&tandy.dac.dma.last_sample);
			}
		}
	}
}
```

## Bug 1:  `read` less than `length` scenario.

The code starts by reading the DMA chunk then writing the mono-stream in the 2nd line: `tandy.dac.chan->AddSamples_m8(read,tandy.dac.dma.buf);`

It then carries on to check `if (read < length)` in this scenario, after which it writes all of the same samples /again/ to the mixer, essentially doubling the last handful of samples at the tail-end of a larger sound effect played across multiple callbacks. 

## Bug 2: `read` equals `length` scenario

In this scenario, the `if` branch is never taken and thus the `tandy.dac.dma.last_sample` value is never updated for the current set of samples. 

This means that `tandy.dac.dma.last_sample` becomes incorrect, and is actually never correct when DMA reads finish "evenly" with requested `length` read from DMA.

**Comment by joncampbell123** [comment]
How's this?

https://github.com/joncampbell123/dosbox-x/blob/master/src/hardware/tandy_sound.cpp#L240

**Comment by kcgen** [comment]
@joncampbell123,
Looking better (in -X's case of simulating the DAC hardware artifact postfixed after each sequence). 

In the DACUpdate function, if the state falls through the first two checks: 
- If `tandy.dac.enabled && ((tandy.dac.mode&0x0c)==0x0c)` is not true, followed by
- last sample being 128.

... then `AddSilence()` is run.  In theory, the added silence should be exactly more 128s.. in which case last_sample can assumed to be correct across this branch.  But if AddSilence () writes something else, then last_sample isn't correct anymore.  (But maybe it's correct enough, so long as AddSilence trends about the zero line instead od going off the rails in either direction). 

More minor comment is that:

``` c++
for (Bitu ct=0; ct < length; ct++) {
				tandy.dac.chan->AddSamples_m8(1,&tandy.dac.dma.last_sample);
			}
```
Is repeated in 3 of the 5 main branches making up the Update and Generate functions; so a bit of a code smell; so maybe that could be improved. 

Overwise it definitely licks the main issue flagged!

**Comment by kcgen** [comment]
@joncampbell123 , I'm going to close this PR as we've both spun off fixes that meet our project's goals.

For ref:
 - X fixed the last-sample issue flagged in the discussion above: https://github.com/joncampbell123/dosbox-x/commit/ad29a7c785006b01735c98fd5dac37d915bac9d2, which improves hardware accuracy when appending the DAC's ramping sound-effect.
 - staging authored PR #457 that gracefully declines -X's offer to simulate the Tandy DAC's ramp artifact appended after each DMA sequence.  This PR also does not to sustain the tail-tranfer's last-sample DC-offset as its inaudible and negatively influences other channels. Both choices knowingly put game-authored audio ahead of simulating artifacts caused by hardware engineering limitations or hardware bugs (which is what I consider the DAC ramping noise to be).

**Pull request closed without merging**
