### PR TITLE
Comment out voodoo logging for local blending API call

### PR DESCRIPTION
**Pull request by interloper98**
# Description

Just a one-liner to silent a log message.

Extreme Tennis makes tens of thousands of calls per second using local blending, and this logging can swamp the terminal or console with messages.

# Manual testing

Tested Extreme Tennis (3DFX launch option) from exoDOS with the following conf:

```ini
[dosbox]
machine=svga_s3
memsize=128

[cpu]
cputype = pentium_mmx
cycles = 50000

[voodoo]
voodoo=true
voodoo_memsize=12

[speaker]
pcspeaker = none

[ipx]
ipx=true

[autoexec]
mount c .
imgmount d cd/TIE_BREAK.cue -t cdrom
c:
@call run
```

And `run.bat` modified to crank up the texture memory unit's ram size from 2 MB to 8 MB: 

```shell
set SST_TMUMEM_SIZE=8
```

The game plays with smooth frame rates in-game, after scoring (game play stops and a score card pops up from the bottom of the screen), and during the instant replays after each set.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by weirddan455 — APPROVED** [review]
Yeah, I don't see a good reason for any of those logs to be there.  That's only useful for developers debugging Voodoo code.  Certainty should not be in a release build.

Usually if we have those types of logs we put them behind an `#ifdef DEBUG_VOODOO` or something that we manually turn on when needed (or just comment them out).

**Comment by Python-Exoproject** [comment]
Sweet work, that fixes that one up so it can work in Staging on 3DFX. Thanks!

**Review by Python-Exoproject — APPROVED** [review]

**Comment by interloper98** [comment]
Thanks for that suggestion @weirddan455. I'll replace the remaining voodoo log calls with that debug define approach.

Thanks for reporting this @Python-Exoproject ; your Extreme Tennis testing hit (what I assume to be) very rarely used voodoo functionality.

**Comment by interloper98** [comment]
(@johnnovak , with this PR only disabling some debug-level logging, it's probably good candidate to make it into the 0.82 release. Do I add a label for that? Or I can make a PR into that branch, too. Let me know)

**Comment by johnnovak** [comment]
> (@johnnovak , with this PR only disabling some debug-level logging, it's probably good candidate to make it into the 0.82 release. Do I add a label for that? Or I can make a PR into that branch, too. Let me know)

Yeah, this is 0.82 material. Please just merge to main. Whatever ends up in main I'll cherry-pick into the 0.82.x branch when the time comes -- leave it with me.

**Comment by interloper98** [comment]
put the voodoo logging in a wrapper; retested it and it's working fine (and suppressing the logging in Extreme Tennis)

**Review by johnnovak — APPROVED** [review]
Nice improvement @interloper98 👍🏻

**Comment by johnnovak** [comment]
@interloper98 Added "game compatibility" label. I started including a game compatibility improvements section in the release notes as that's a high interest topic, so we should use this label when applicable.

**Comment by interloper98** [comment]
Makes sense, thanks for that tip @johnnovak.

**Pull request merged**
