### PR TITLE
Use safer calls in dynrec and operators

### PR DESCRIPTION
**Pull request by kcgen**
Possible fix for #2346

### CODE REVIEW

**Comment by kcgen** [comment]
I can't repro https://github.com/dosbox-staging/dosbox-staging/issues/2346 on the M1; tried clang debug and release builds, hitting Ctrl+F11 and F12 stepping max-% up and down rapidly for over a minute with the demo running.  Used the conf as provided (MT32 and with the game configured for MT32 music).

**Comment by kcgen** [comment]
@johnnovak , curious if this branch is able to help.  If not, can you try a UBSAN build (or debug and get a backtrace?)

**Comment by johnnovak** [comment]
> @johnnovak , curious if this branch is able to help. If not, can you try a UBSAN build (or debug and get a backtrace?)

Sure, I can do that.

**Comment by johnnovak** [comment]
First attempt with a debug build seemed fine; I let the intro run for about 20 seconds while changing the speed up and down continuously.

Then I tried the sanitiser build, and with that it crashes in a matter of seconds.

First attempt:

```
2023-03-21 16:11:24.020 | CPU speed: max 20 percent.
2023-03-21 16:11:24.175 | CPU speed: max 25 percent.
2023-03-21 16:11:24.329 | CPU speed: max 30 percent.
2023-03-21 16:11:24.472 | CPU speed: max 35 percent.
2023-03-21 16:11:24.606 | CPU speed: max 40 percent.
2023-03-21 16:11:24.758 | CPU speed: max 45 percent.
2023-03-21 16:11:24.905 | CPU speed: max 50 percent.
2023-03-21 16:11:25.056 | CPU speed: max 55 percent.
2023-03-21 16:11:25.198 | CPU speed: max 60 percent.
2023-03-21 16:11:25.357 | CPU speed: max 65 percent.
2023-03-21 16:11:25.504 | CPU speed: max 70 percent.
2023-03-21 16:11:25.649 | CPU speed: max 75 percent.
2023-03-21 16:11:25.742 | ABORT: CALL:Descriptor type 0x13 unsupported
```

Second attempt:

```
2023-03-21 16:12:04.176 | CPU speed: max 35 percent.
2023-03-21 16:12:04.437 | CPU speed: max 40 percent.
2023-03-21 16:12:04.569 | CPU speed: max 45 percent.
2023-03-21 16:12:04.716 | CPU speed: max 50 percent.
2023-03-21 16:12:04.848 | CPU speed: max 55 percent.
2023-03-21 16:12:04.997 | CPU speed: max 60 percent.
2023-03-21 16:12:05.126 | CPU speed: max 65 percent.
2023-03-21 16:12:05.269 | CPU speed: max 70 percent.
2023-03-21 16:12:05.419 | CPU speed: max 75 percent.
2023-03-21 16:12:05.580 | CPU speed: max 80 percent.
2023-03-21 16:12:05.743 | CPU speed: max 75 percent.
2023-03-21 16:12:05.903 | CPU speed: max 70 percent. If the game runs too fast, try a fixed cycles amount in DOSBox's options.
2023-03-21 16:12:06.037 | CPU speed: max 65 percent. If the game runs too fast, try a fixed cycles amount in DOSBox's options.
2023-03-21 16:12:06.186 | CPU speed: max 60 percent. If the game runs too fast, try a fixed cycles amount in DOSBox's options.
2023-03-21 16:12:06.347 | CPU speed: max 55 percent. If the game runs too fast, try a fixed cycles amount in DOSBox's options.
2023-03-21 16:12:06.490 | CPU speed: max 50 percent. If the game runs too fast, try a fixed cycles amount in DOSBox's options.
2023-03-21 16:12:06.635 | CPU speed: max 45 percent. If the game runs too fast, try a fixed cycles amount in DOSBox's options.
2023-03-21 16:12:06.768 | ABORT: RET from illegal descriptor type 0x0
zsh: abort      ~/jn/dosbox-staging/build/sanitizer/dosbox -noprimaryconf
```

On my third attempt I got this and nothing unusual in the logs, but of course the process just got stuck at this point:

image

So it seems random memory corruption that can result in pretty much any error. Btw, I know that the game does its own memory management—I learned that yesterday when finally managing to get it to run on my real DOS box. It kept crashing with XMS & EMS, but it was fine when I had only conventional memory.

**Pull request merged**
