### PR TITLE
Reduce "noise" warnings on MSVC

### PR DESCRIPTION
**Pull request by kklobe**
# Description

This is a collection of "noise"-reducing commits for MSVC.

This gets us down to:

```log
Warnings grouped by type:

  deprecated-declarations : 14
  unused-variable         : 2
  format-security         : 2
  microsoft-include       : 1

Total: 19 warnings (out of 19 allowed)
```

# Manual testing

Ran the build output artifacts.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
@kklobe Doesn't force-move work?

```
git mv -f name.cpp Name.cpp
```

Or squashing the two succesive delete/recreate with different name commits into one?

**Comment by kklobe** [comment]
> @kklobe Doesn't force-move work?
> 
> ```
> git mv -f name.cpp Name.cpp
> ```
> 
> Or squashing the two succesive delete/recreate with different name commits into one?

Nope, it just makes an empty commit on a case-insensitive file system (i.e. windows and macos). You can do a `git config core.ignorecase false` but that can screw many things up, so this seemed the most straightforward way to do it.

**Review by shermp — APPROVED** [review]
Well done @kklobe . This is looking much better. Thanks for continuing to improve this MSVC stuff.

No trouble compiling here. And the vastly reduced warning count is very much appreciated.

**Review by johnnovak — APPROVED** [review]
Nice improvement @kklobe

**Pull request merged**
