### PR TITLE
Sync CD-DA codecs with upstream

### PR DESCRIPTION
**Pull request by kcgen**
Another routine update. Tested all standard codecs plus Sony Wave64, stereo and mono channels, and various sampling rates.

### CODE REVIEW

**Comment by kcgen** [comment]
Moving this PR to draft for now because the changes added a PVS warning and a handful of new Clang static analysis issues.  Will submit those upstream.

**Comment by kcgen** [comment]
Tracking external issue:

- https://github.com/mackron/dr_libs/issues/153
- https://github.com/mackron/dr_libs/issues/154
- https://github.com/mackron/dr_libs/issues/155
- https://github.com/mackron/dr_libs/issues/156
- https://github.com/mackron/dr_libs/issues/157
- https://github.com/mackron/dr_libs/issues/158
- https://github.com/mackron/dr_libs/issues/159
- https://github.com/mackron/dr_libs/issues/160
- https://github.com/mackron/dr_libs/issues/161
- https://github.com/mackron/dr_libs/issues/162
- https://github.com/mackron/dr_libs/issues/163
- https://github.com/mackron/dr_libs/issues/164
- https://github.com/mackron/dr_libs/issues/165
- https://github.com/mackron/dr_libs/issues/166

**Comment by kcgen** [comment]
**Update**: dr_wav and dr_mp3 are now running clean through both static analyzers. Will re-pull the formalized releases from upstream once ready, and then move this PR out of draft.

Discussion of changes are in: https://github.com/mackron/dr_libs/issues/155 and https://github.com/mackron/dr_libs/issues/165.

**Comment by kcgen** [comment]
The new issues been addressed as well as some older ones, bringing Clang's static analysis issue count down by 8 items. Thank you @mackron. 

Retested and all cases are passing. Moving out of draft.

**Comment by dreamer** [comment]
Previous versions of dr_libs libraries were thoroughly tested since we made last update in master branch several months ago. I prefer to keep this update out of master until we'll release 0.76.0.

**Comment by kcgen** [comment]
Works for me too, @dreamer. 
The entire suite is working flawlessly, so makes perfect sense to merge this post-0.76.

**Review by dreamer — APPROVED** [review]
These build failures on "Publish additional artefacts" are weird - happened to me a lot today.

Let's merge this in and see if they happen again.

@kcgen Thanks for keeping a tab on this upstream work :)

**Comment by kcgen** [comment]
One new Coverity issue detected. Tracking here: https://github.com/mackron/dr_libs/issues/171

**Pull request merged**
