### PR TITLE
Build macOS x86-64 release on arm64 runner

### PR DESCRIPTION
**Pull request by kcgen**
For those running x86-64 MacOS 10.15 systems, can you check this PR's release package here: https://github.com/dosbox-staging/dosbox-staging/actions/runs/2884738596

### CODE REVIEW

**Comment by Grounded0** [comment]
Whatever comes out should be validated with:
$ otool -l -arch x86_64 dosbox
$ otool -l -arch arm64 dosbox

Load command 10 gives out the goods:
Screenshot 2022-08-17 at 12 52 53

**Comment by kcgen** [comment]
Thanks @Grounded0.

I think we're good; I'm getting `minos 10.15` for the x86_64 query.

1.  **Mount the DMG**: `hdiutil attach dosbox-staging-macOS-v0.79.0-alpha-1153-g274c03.dmg`

    ``` text
    Checksumming Protective Master Boot Record (MBR : 0)…
    Protective Master Boot Record (MBR :: verified   CRC32 $38306EF5
    Checksumming GPT Header (Primary GPT Header : 1)…
     GPT Header (Primary GPT Header : 1): verified   CRC32 $B93ABB5D
    /dev/disk6          	GUID_partition_scheme          	
    /dev/disk6s1        	Apple_APFS                     	
    /dev/disk7          	EF57347C-0000-11AA-AA11-0030654	
    /dev/disk7s1        	41504653-0000-11AA-AA11-0030654	/Volumes/dosbox-    staging
    ```

2. **x86_64 query**: `otool -l -arch x86_64 /Volumes/dosbox-staging/dosbox-staging.app/Contents/MacOS/dosbox | grep -A8 "command 10"`

    ``` text
    Load command 10
          cmd LC_BUILD_VERSION
      cmdsize 32
     platform 1
        minos 10.15
          sdk 12.1
       ntools 1
         tool 3
      version 711.0
    ```

3. **arm64 query**: `otool -l -arch arm64 /Volumes/dosbox-staging/dosbox-staging.app/Contents/MacOS/dosbox | grep -A8 "command 10"`

    ``` text
    Load command 10
          cmd LC_BUILD_VERSION
      cmdsize 32
     platform 1
        minos 11.0
          sdk 12.1
       ntools 1
         tool 3
      version 711.0
    ```

**Comment by kcgen** [comment]
Merging based on good results.

**Comment by Burrito78** [comment]
Merge, i'll check on Monday and give a short status on Discord. Looks good though.

**Comment by kcgen** [comment]
> OK, i'll check on Monday and give a short status on Discord. Looks good though.

Thanks @Burrito78.

The good thing about this is, if we need to bolt on older SDK's into the M1 runner - then we have that ability.

Where as with the GitHub VMs, Microsoft/Apple are in charge of those.

**Pull request merged**
