### PR TITLE
Fix regression in voodoo 16-bit memory write

### LINKED ISSUE #2943: Archimedean Dynasty: Bugged HUD elements with 3dfx
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-1677-gf7498da22

### What Operating System are you using?

Windows 10

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Certain HUD elements are rendered wrong when playing the 3dfx version, and appear distorted a bit to the right. They consist of mostly text in the cockpit and 3rd person views, but also other elements such as reticles, circles and sqares around enemies, lines, etc.

Below are two screenshots comparing the software version to the 3dfx version. Check the upper middle part of the HUD, the text block in the middle left and the armor indicator on the lower right.

Software:
03a

3dfx:
03b

### Steps to reproduce the behaviour.

1. Download & install the game from the link below
2. Install the 1.120 patch and the 3dfx patch, working download links can be found at https://soggi.org/misc/3dfx-voodoo-game-patches.htm
3. Start the game via AD3DFX.EXE and start a mission such as training/instant action.
4. Look at the HUD and compare it to how it looks when playing through AD.EXE

### Download URL of affected game or software

https://archive.org/download/archimedean-dynasty

### Your configuration

```ini
The issue appears even with a default config file.
```

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by interloper98**
# Description

A typo in commit 5e24bad4 missed an else block when getting rid of an `E_Exit` condition. This PR restores the original logic, documents the alignment and shifting requirements, and makes it branchless.

It also continues to use an assert instead of the original `E_Exit`.

## Related issues

Fixes #2943 

archimedean-dynasty-3dfx-fix

# Manual testing

Also tested Carmageddon:

carmageddon-3dfx-fix

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by johnnovak — APPROVED** [review]
Very nice fix @interloper98, finally our Voodoo code gets some love 😆 🏅

**Comment by Grounded0** [comment]
Pinging @geist22

**Review by Grounded0 — APPROVED** [review]

**Comment by Grounded0** [comment]
Honestly I didn't even notice it but I'm happy its fixed now.

**Review by Python-Exoproject — APPROVED** [review]
Im no coder, so ill just approve this. Thanks for looking into it @interloper98

**Comment by geist22** [comment]
Great work! I can confirm that this fixes the HUD in Archimedean Dynasty.

**Pull request merged**
