### PR TITLE
Cleanup help messages for AUTOTYPE, DIR, and KEYB commands

### PR DESCRIPTION
**Pull request by Wengier**
This new PR cleans up help messages for DOS commands AUTOTYPE, DIR, and KEYB, using the style of DOS commands such as MOUNT and VER. The older help messages in these commands have been upgraded to the new style accordingly.

### CODE REVIEW

**Comment by kcgen** [comment]
Thanks for this @Wengier !

Would it be possible to keep the more terse tabular format of the arguments on the left, with short descriptions on the right?



Perhaps with colors added, and the three sections per the new format? (Usage / Where / Notes).

This will lighten the load for readers, and let them quickly see the flags.

**Comment by Wengier** [comment]
@kcgen (With the sole exception of INTRO command) these commands are essentially the last 3 DOS commands to implement the new style format; I don't think there are other commands left in the regular builds. If we implement some tabular format of the arguments for the DIR command, then it is the ONLY command to have such a special treatment, unlike all other commands. Also, compared with DOS, the options for DIR command in DOSBox Staging are certainly not complete, so implementing the tabular format is expected to make it exceed 25 lines on a standard screen. Thus I am not really sure if we need to handle DIR command in a special way. What do you think?

**Comment by kcgen** [comment]
> With one or two commands left, these commands are essentially the last 3 DOS commands to implement the new style format

:+1: ; this is great news - thanks for all these contributions!

> If we implement some tabular format of the arguments for the DIR command, then it is likely the only command to have such a special treatment, unlike all other commands <snip> I am not really sure if we need to handle DIR command in a special way. What do you think?

My fault in explaining what I was hoping to achieve.  I will retry.  When I glances at those two screenshots, the original layout lets me see the options easier than the new format, where the arguments are embedded throughout the paragraph. 

I don't think we need to adopt a new format or adjust the other help screens. 

Is it possible to adjust the help content such that the same ease-of-reading is accomplished?  (I'm not saying we need to rigidly keep the old format, just that I wold like something that's on-par with a nice layout and quick to read).

**Comment by Wengier** [comment]
@kcgen Thanks for the explanation, and I agree that it is certainly helpful to make the option list easier to read. Please check it the new version and see if it improves in this regard (it lists two options in a row under "Notes" so that the whole help message is still in one screen). I was mainly concerned about the new style we have used for commands, but I guess it is okay -- for example, when we add new options for e.g. LS command, they can be listed in a similar way too if it is agreed that such a list works well.

**Comment by kcgen** [comment]
Thanks @Wengier , the two-column approach is much improved, and retains the "/arg" at the front of the column, for easy reading.  :+1: 



Merging.

**Pull request merged**
