### PR TITLE
Fix CI hand-over of the MSVC binaries to MSYS2 packaging

### PR DESCRIPTION
**Pull request by kcgen**
# Description

A race condition in the MSVC CI artifact upload step meant we could upload the MSVC package with (or without) the debugger present.

If the MSVC debugger build job took longer than the non-debugger job, then the debugger would "miss the boat", leading to a warning-but-passing result on the MSYS2 side.

This PR splits out the debugger executable upload into its own step, so it's no longer dependent on the non-debugger package.

# Manual testing

I've inspected the packages and CI output, and it appears that everything is working - however we need to test setup.exe package to see if it has both the MSYS2 and MSVC executables.

@johnnovak, @shermp - can you check the installer?

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
> @johnnovak, @shermp - can you check the installer?

I will later, yeah.

**Comment by johnnovak** [comment]
@kcgen I've noticed you're still making changes to this. Let me know when it's final, then I'll test it.

**Comment by kcgen** [comment]
Unfortunately it's rough going.

I've filled 10 pages worth of CI jobs throughout the day and am no closer to figuring out how to reliably making our msys2 packing job depend on the msvc workflow's outputs (and I've tried github's workflow_run, fountainhead's wait action, and lots of variations)😭

I'm going to close this and will have to revert the CI changes that dependapot and I added, and we'll go back to the v3 APIs.

**Comment by johnnovak** [comment]
> Unfortunately it's rough going.
> 
> I've filled 10 pages worth of CI jobs throughout the day and am no closer to figuring out how to reliably making our msys2 packing job depend on the msvc workflow's outputs (and I've tried github's workflow_run, fountainhead's wait action, and lots of variations)😭
> 
> I'm going to close this and will have to revert the CI changes that dependapot added, and we'll go back to the v3 APIs.

That's the best. It's not like the v3 API will stop working soon. Then we can figure this out post 0.81.0 without stress. It's for the best not to mess with this before 22 Dec at least.

**Comment by shermp** [comment]
I guess we could always just merge MSVC and MSYS2 into a single "Windows" workflow, which would allow easier dependency management.

**Comment by kcgen** [comment]
> I guess we could always just merge MSVC and MSYS2 into a single "Windows" workflow, which would allow easier dependency management.

Yeah - that was my last option, but these workflows (the windows ones specifically, being more complex and larger) are already on the precipice of having runaway technical debt. 

Plus, being able to only debug them at a distance, in 20 minute increments, makes them very unwieldy - it's one of those tasks that just drains you, because there only outcome is just getting the damn thing back to a working baseline 😅

I think the next step for them is to go to shell scripts (or some 3rd party open-source python tool that can do this for us, and leave all this GitHub yaml behind.. well, except for the single hook to launch our system on the GitHub machine). 

It's the only way to move the development and testing locally and speed up the development iterations.

**Pull request closed without merging**
