### PR TITLE
Cleanup help messages for SERIAL and CD/CHDIR commands

### PR DESCRIPTION
**Pull request by Wengier**
The SERIAL command has been added recently, but its help message did not yet fully conform to the style of DOS commands such as MOUNT and VER. So I improved it to the desired style in this PR. Also, I noticed that the help message for CD/CHDIR command was not yet updated to the new style, so this PR updates it as well.

Also, ``SERIAL`` command without any argument will list all serial ports, or ``SERIAL n`` for listing the specified port. ``SERIAL /?`` will show its help information.

### CODE REVIEW

**Comment by kcgen** [comment]
> Also, `SERIAL` command without any argument will list all serial ports, or `SERIAL n` for listing the specified port. `SERIAL /?` will show its help information.

That's a nice touch @Wengier !

**Comment by kcgen** [comment]
## CD/CHDIR

**Comment by kcgen** [comment]
## SERIAL

**Review by sduensin — APPROVED** [review]
Looks great!

**Comment by kcgen** [comment]
Thanks for these improvements @Wengier  and the review @sduensin !

PS - I dropped the `backport` tag because, as @Burrito78 noted, getting translations complete for this would push out the timeaframe for the 0.78.1 maintenance release, and for users affected by it, getting those show-stoppers solved are critical.

**Pull request merged**
