### PR TITLE
Add translation batch file for Windows

### PR DESCRIPTION
**Pull request by Kappa971**
We talked about it here: https://github.com/dosbox-staging/dosbox-staging/pull/2302

Includes `uconv`, taken from the ICU v72.1 package, and `dos2unix` v7.4.4 (32-bit versions).

### CODE REVIEW

**Comment by kcgen** [comment]
The utility looks good @Kappa971 :+1: 

For the binaries in `tools/` normally we don't add binaries to the repository (they are large, get outdated so add work to refresh them, and worse - may not match the user's runtime environment (64-bit vs 32-bit? x86 vs ARM? lots of variations here: <https://github.com/unicode-org/icu/releases/tag/release-72-1>).

If we have documentation for translators, these tools could be part of the per-requisites (similar to how people wanting to compile have to download Meson, clang, gcc, etc).

Another suggestion would be to add ``tools\readme.txt` that points the user to the websites and asks them to unzip the packages inside the `tools` dir.  

The batch file could even type it:

```bat
if NOT EXIST tools\uconv.exe type tools\readme.txt
if NOT EXIST tools\dos2unix.exe type tools\readme.txt
```
(or something like that)

**Comment by Kappa971** [comment]
> The batch file looks good @Kappa971 👍
> 
> For the binaries in `tools/` normally we don't add binaries to the repository (they are large, get outdated so add work to refresh them, and worse - may not match the user's runtime environment (64-bit vs 32-bit? x86 vs ARM? lots of variations here: https://github.com/unicode-org/icu/releases/tag/release-72-1).
> 
> If we have documentation for translators, these tools could be part of the per-requisites (similar to how those wanting to compile have to download Meson, clang, gcc, etc).
> 
> Another suggestion would be to add `tools\readme.txt` that points the user to the websites and asks them to unzip the packages inside the `tools` dir.
> 
> The batch file could even type it:
> 
> ```batchfile
> if NOT EXIST tools\uconv.exe type tools\readme.txt
> if NOT EXIST tools\dos2unix.exe type tools\readme.txt
> ```
> 
> (or something like that)
> 
> We would also then want git to ignore any new files found inside `tools/`, which we can do using a little text file: `contrib/resources/translations/.gitignore` having a single line: `tools`.

It would be better to be able to download the necessary tools (in Windows 10 and 11 there are `wget` and `curl`).
I have no idea how to download the latest versions without having to modify the batch file for each new release...

**Comment by kcgen** [comment]
> It would be better to be able to download the necessary tools (in Windows 10 and 11 there is curl).
> I have no idea how to download the latest versions without having to modify the batch file for each new release...

I know what you mean, @Kappa971 - it would be nice to offer this, but it gets even trickier: you have to figure out what architecture (ARM vs x86-32bit vs x86-64-bit) they're running too.. and yeah, then also keep these scripts updated to fetch the latest version.

Fortunately for anyone wanting to put in the help to translate (and that's not a small amount of work!) downloading a couple zip files and unpacking them is a tiny step - and it's just a one-time step.

**Comment by Kappa971** [comment]
`uconv.exe` requires dlls that change name at each version (eg `icudt71.dll` in version 71.1, `icudt72.dll` in version 72.1). I could list the required dlls as well, but I'm afraid they might be removed/renamed (e.g. `icudt72.dll` becomes `something82.dll)` or new ones added in the future, and this would make the batch file and readme obsolete. Suggestions are welcome,

**Comment by kcgen** [comment]
> `uconv.exe` requires dlls that change name at each version (eg. `icudt71.dll` in version 71.1, `icudt72.dll` in version 72.1). I could list the required dlls as well, but I'm afraid they might be removed/renamed (eg. `icudt72.dll` becomes `something82.dll)` or new ones added in the future, and this would make the batch file and readme obsolete. Suggestions are welcome,

I like the current approach with the readme; interested translators can download the tools and unzip them without much trouble.

**Review by kcgen — APPROVED** [review]
Looks good, @Kappa971.
I will squash the three commits into one, which would eliminate the binaries from the commit history.

**Comment by Kappa971** [comment]
Translators need to update the German, French and Spanish translations with the new color tags to avoid the dos2unix error.

**Pull request merged**
