### PR TITLE
Revert to physical memory calls for DMA transfers (#1563)

### LINKED ISSUE #1563: SB16 audio regression in Windows 3.11
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

Windows 10

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using SB16, playback of audio in Windows 3.11 is completely broken, sounds like gibberish.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Windows 3.11
2. The startup chime/tone should play. Instead static is heard
3. Play any wav file. Sound is either static, or repeating noises.

Note, this appears to have been introduced in #1536 
Sound plays fine in the prior workflow run.

### Your configuration

Using Creative SB16 audio driver 3.56.20 that I downloaded from their website.

### Provide a Log

```text
2022-02-11 16:35:56.912 | arguments: D:\\Downloads\\dosbox-staging-windows-msys2-x86_64-v0.79.0-alpha-184-g10990\\dosbox.exe -conf .\\win311.conf
2022-02-11 16:35:56.913 | Current dir: D:\Games\Dosbox Win311
2022-02-11 16:35:56.913 | stderr verbosity: 0
2022-02-11 16:35:56.913 | -----------------------------------
2022-02-11 16:35:56.913 | dosbox-staging version 0.79.0-alpha-184-g1099006c
2022-02-11 16:35:56.913 | ---
2022-02-11 16:35:56.913 | LOG: Loguru version 2.1.0 initialized
2022-02-11 16:35:56.937 | SDL: version 2.0.20 initialized (windows video and wasapi audio)
2022-02-11 16:35:56.939 | CONFIG: Unknown option latency
2022-02-11 16:35:56.939 | CONFIG: Unknown option logfile
2022-02-11 16:35:56.940 | CONFIG: Loaded primary conf file C:\Users\sherm\AppData\Local\DOSBox\dosbox-staging.conf
2022-02-11 16:35:56.940 | CONFIG: Loaded custom conf file .\win311.conf
2022-02-11 16:35:56.941 | DISPLAY: Initialized 1067x800 window-mode using Bilinear scaling on 1080p display-0
2022-02-11 16:35:57.174 | OPENGL: Vendor: ATI Technologies Inc.
2022-02-11 16:35:57.174 | OPENGL: Version: 4.6.14831 Compatibility Profile Context 21.5.2 27.20.20903.8001
2022-02-11 16:35:57.175 | OPENGL: GLSL version: 4.60
2022-02-11 16:35:57.175 | OPENGL: Pixel buffer object: available
2022-02-11 16:35:57.175 | OPENGL: NPOT textures: supported
2022-02-11 16:35:57.180 | DISPLAY: Unknown 640x400 (mode FFFFh) scaling by 1.7x2.0 to 1067x800 with 1.20 pixel-aspect
2022-02-11 16:35:58.209 | SDL: Mouse will be captured immediately on start and middle-click will uncapture the mouse.
2022-02-11 16:35:58.209 | LANG: Using internal English language messages
2022-02-11 16:35:58.219 | SYSTEM: Speed modifications are enabled
2022-02-11 16:35:58.283 | Memory sizes above 31 MB are NOT recommended.
2022-02-11 16:35:58.289 | Stick with the default values unless you are absolutely certain.
2022-02-11 16:35:58.302 | MEMORY: Base address: 00000254450D1040
2022-02-11 16:35:58.305 | MEMORY: Using 8192 DOS memory pages (32 MiB)
2022-02-11 16:35:58.311 | RENDER: Using GLSL shader 'default'
2022-02-11 16:35:58.319 | VIDEO: Initialized S3 Trio64 VESA 2.0 compatible with 4-MiB of FP DRAM supporting 86 modes
2022-02-11 16:35:58.335 | MIXER: SDL changed the blocksize from 1024 to 441 frames
2022-02-11 16:35:58.337 | MIXER: Negotiated 2-channel 44100-Hz audio in 441-frame blocks
2022-02-11 16:35:58.339 | MIXER: FSYNTH channel operating at 44100 Hz without resampling
2022-02-11 16:35:58.364 | MIDI: Using SoundFont 'SC-55.SoundFont.v1.2b.sf2'
2022-02-11 16:35:58.366 | MIDI: Chorus enabled with 3 voices at level 1.20, 0.30 Hz speed, 8.00 depth, and sine-wave modulation
2022-02-11 16:35:58.370 | MIDI: Reverb enabled with a 0.61 room size, 0.23 damping, 0.76 width, and level 0.56
2022-02-11 16:35:58.373 | MIDI: Opened device: fluidsynth
2022-02-11 16:35:58.374 | MIXER: FM channel operating at 44100 Hz without resampling
2022-02-11 16:35:58.376 | MIXER: SB channel operating at 22050 Hz and upsampling to the output rate
2022-02-11 16:35:58.378 | SB16: @SET BLASTER=A220 I7 D1 H5 T6
2022-02-11 16:35:58.379 | MIXER: SPKR channel operating at 18939 Hz and upsampling to the output rate
2022-02-11 16:35:58.381 | MIXER: DISNEY channel operating at 10000 Hz and upsampling to the output rate
2022-02-11 16:35:58.393 | SLIRP: Slirp version: 4.6.1
2022-02-11 16:35:58.395 | SLIRP: Successfully initialized
2022-02-11 16:35:58.397 | NE2000: Base=0x300 irq=3
2022-02-11 16:35:58.399 | AUTOEXEC: Using autoexec from one or more joined sections
2022-02-11 16:35:58.456 | MAPPER: no joysticks found
2022-02-11 16:35:58.459 | MAPPER: Loaded default key bindings
2022-02-11 16:35:58.472 | MOUNT: Path 'win_c' found
2022-02-11 16:35:58.475 | SDL: captured the mouse
2022-02-11 16:35:58.484 | DISPLAY: Text 640x400 (mode 3h) scaling by 1.7x2.0 to 1067x800 with 1.20 pixel-aspect
2022-02-11 16:36:00.547 | DISPLAY: EGA 640x480 16 color (mode 12h) scaling by 1.7x1.7 to 1067x800 with 1.00 pixel-aspect
2022-02-11 16:36:01.337 | SB16: DSP was reset
2022-02-11 16:36:01.341 | SB16: DSP was reset
2022-02-11 16:36:01.478 | DISPLAY: VESA 1024x768 32-bit (mode 118h) scaling by 1.0x1.0 to 1067x800 with 1.00 pixel-aspect
2022-02-11 16:36:02.311 | SB16: DSP was reset
2022-02-11 16:36:08.185 | SB16: DSP was reset
2022-02-11 16:36:08.251 | DISPLAY: Text 640x400 (mode 3h) scaling by 1.7x2.0 to 1067x800 with 1.20 pixel-aspect
2022-02-11 16:36:11.691 | SDL: released the mouse
2022-02-11 16:36:11.739 | atexit
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
One of several optimizations in the community patch adopted in https://github.com/dosbox-staging/dosbox-staging/commit/fba92d41c23d53d032e57eac4507ef5d1a2edd60 was that it made use of the block-transfer routines:

```c++
MEM_BlockRead(page*4096 + (offset & 4095), write, pagesize);
MEM_BlockWrite(page*4096 + (offset & 4095), write, pagesize);
```

instead of the per-address looping:

```c++
for ( ; size ; size--, offset++) {
	if (offset>(dma_wrapping<<dma16)) {
	offset &= dma_wrap;
	Bitu page = highpart_addr_page+(offset >> 12);
	/* care for EMS pageframe etc. */
	if (page < EMM_PAGEFRAME4K) page = paging.firstmb[page];
	else if (page < EMM_PAGEFRAME4K+0x10) page = ems_board_mapping[page];
	else if (page < LINK_START) page = paging.firstmb[page];
	*write++=phys_readb(page*4096 + (offset & 4095));
```

The difference between the block routine and the `phys_` routines is the latter includes a memory offset (`MemBase`) for the program itself.

This PR reverts to the `phys_` routines while keeping the hoisting optimizations provided by Peter Ferrie's patch.

Thanks to @shermp for flagging and bisecting this issue. Fixes #1563.

### CODE REVIEW

**Comment by shermp** [comment]
Don't know enough about the code to say whether it's any good or not (some of that arithmetic looks a bit hairy!), but the end result is that the regression in question is fixed.

I don't think I've ever come accross `*var++ = ...` before today

**Comment by kcgen** [comment]
> Don't know enough about the code to say whether it's any good or not (some of that arithmetic looks a bit hairy!), but the end result is that the regression in question is fixed.
> 
> I don't think I've ever come accross `*var++ = ...` before today

Thanks for the quick review! I agree. Pushed an update that switches those to array index notation.

**Comment by shermp** [comment]
> > I don't think I've ever come accross `*var++ = ...` before today
> 
> Thanks for the quick review! I agree. Pushed an update that switches those to array index notation.

Win 3.11 and Epic pinball still working :)

**Review by Wengier — APPROVED** [review]
Glad to have the code that fixes the regression.

**Comment by kcgen** [comment]
@shermp , @Wengier : thank you for the reviews.

**Pull request merged**
