### PR TITLE
Unicode mapping for CYRILLIC LETTER I WITH GRAVE, RUBLE, BG

### PR DESCRIPTION
**Pull request by Torinde**
Closes #2592

### CODE REVIEW

**Review by FeralChild64 — CHANGES_REQUESTED** [review]
I have just one remark - please make these changes in one commit:

1. Backup your changed files somewhere, just to be sure.
2. Execute the following commands in your repository:

```bash
git reset HEAD~4
git add .
git commit
git push --force
```

One advice for the future: it is best to keep the main branch of your repository a mirror of the original main and only do your development in branches.

**Comment by Torinde** [comment]
Hoping that the "refreshed Github" has extra features - first tried entering those commands at the "Command palette" in the Github.com web interface:
image
Not working. Obviously not the right place.
Installed Github Desktop, "cloned" my repository locally, but again no place to enter commands, referred me to yet another tool to install: "Git"
Installed Git (which installs 100 other stuff like editor, SSH, etc.?)

1. git reset HEAD~4 - seems OK
2. git add . - seems OK
3. git commit - opened some kind of text editor (vim??) with some pre-filled comment, but I couldn't "save" it
4. opened GIT GUI - clicked "Commit" button, wrote comment, seems OK
5. git push --force (or GUI "Push" button and then "force ..." checkbox) - doesn't work. In the background appears "Git credentials manager" console - if I click on it "Required command not provided" or something like that flashes in red quickly...
6. Force-closing this background window, AFTER Windows terminates it makes another window to appear: "OpenSSH Login". Entering credentials there doesn't help.

Takeaways:
- it's something simple/obvious that I'm missing (like entering my credentials in yet another place, probably in Git somewhere?)
- Github web interface should provide "command prompt" equivalent supporting those git commands.

**Comment by weirddan455** [comment]
> git commit - opened some kind of text editor (vim??) with some pre-filled comment, but I couldn't "save" it

Yeah, that's probably vim or vi by default.  Type `:wq` to save and quit.  You can also just do `git commit -m "My commit description"` instead to skip the editor

> git push --force (or GUI "Push" button and then "force ..." checkbox) - doesn't work. In the background appears "Git credentials manager" console - if I click on it "Required command not provided" or something like that flashes in red quickly...

Get the exact error message for that.  I believe Git for Windows has a special GitHub credential manager that should just work when you type your GitHub username and password into it.  On other operating systems, (like what I had to do on Linux) you have to make a "Personal Access Token" and use that as your git password:  https://github.com/settings/tokens

I believe that's not needed on Windows but maybe worth a try if you want to bypass the credential manager.

If you want to hop on Discord I might be able to help you further.

**Review by kcgen — APPROVED** [review]
@Torinde, cheers - very nice PR, :beers:!

@FeralChild64, if you want to try, GitHub has a handy  squash-at-merge time. Will attach a screenshot.

**Pull request merged**
