### PR TITLE
Use wrapping behavior on localFile seek position

### LINKED ISSUE #3778: Repeating seek failures in `WINDOWS/SYSTEM/DVA.386` when reinstalling WinG
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82-alpha (main)

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When re-installing the WinG package in Window 3.11, I get repeating warnings in the log:

```text
FS: File seek failed for './WINDOWS/SYSTEM/DVA.386'
FS: File seek failed for './WINDOWS/SYSTEM/DVA.386'
FS: File seek failed for './WINDOWS/SYSTEM/DVA.386'
FS: File seek failed for './WINDOWS/SYSTEM/DVA.386'
FS: File seek failed for './WINDOWS/SYSTEM/DVA.386'
FS: File seek failed for './WINDOWS/SYSTEM/DVA.386'
```

This is essentially locks up Windows 3.11, however the emulator can still be Ctrl+F9 to quit.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download and extract: [wfw-trio-170.zip](https://github.com/user-attachments/files/15891109/wfw-trio-170.zip)

2. Run Staging when inside the `wfw-trio-170/` directory

3. Windows 3.11 starts, then launch the 'rerun WinG setup' icon:

    wing-resetup

4. Click default/yes answers; the install should jam up with these seek errors filling Staging's log output.

---

A one-time work-around is to delete `WINDOWS/SYSTEM/DVA.386` and also delete the `device=` s reference in `WINDOWS/SYSTEM.INI`:

```ini
[386Enh]
device=C:\WINDOWS\SYSTEM\dva.386
```

### Download URL of affected game or software

https://github.com/user-attachments/files/15891109/wfw-trio-170.zip

### Your configuration

```ini
`dosbox.conf` is included in the zip.
```

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description
Tested on MS-DOS 6.22 with some ugly looking assembly code I wrote.  The return value from seek wraps.  If you're at position 10 and you seek backwards by 20, it returns ~4 billion.

## Related issues

Fixes #3778

# Manual testing
Implementing this behavior fixes the WinG installer.  Blackthorne continues to work.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by johnnovak — APPROVED** [review]
Nice edge case fix @weirddan455. See, this is where using the integrated debugger would've come in handy 😏

**Comment by weirddan455** [comment]
> Nice edge case fix @weirddan455. See, this is where using the integrated debugger would've come in handy 😏

I don't know that the debugger would have helped.  I knew what Dosbox was doing.  I needed to confirm what MS-DOS was doing so I had to write a DOS program.  I used assembly because NASM can output a .COM file and setting up a DOS C compiler is kind of a pain.

**Comment by johnnovak** [comment]
> I don't know that the debugger would have helped

You could have used your DOS program and inspect the register values in the debugger after a BIOS call, so you could have spared the effort of writing the number to string conversion routine, that's whst I meant.

**Comment by weirddan455** [comment]
>  You could have used your DOS program and inspect the register values in the debugger after a BIOS call, so you could have spared the effort of writing the number to string conversion routine, that's whst I meant.

Well I was trying to test in MS-DOS 6.22 in a VM, not inside Dosbox.

**Comment by johnnovak** [comment]
> Well I was trying to test in MS-DOS 6.22 in a VM, not inside Dosbox.

Not sure if you're aware, you can also run real MS-DOS 6.22 in DOSBox if you mount a FAT HDD partition image. I kinda assumed you did that, that's why I brought up the DOSBox debugger 😄

**Pull request merged**
