### PR TITLE
Change the current icons being used by DOSBox Staging

### PR DESCRIPTION
**Pull request by ThomasEricB**
The idea is: remove the circle to make the executable icons cleaner (nothing to do with the favcon from the website nor the website). Basically this:
firefox_ZGh9UimAZt

### CODE REVIEW

**Comment by ThomasEricB** [comment]
If @kcgen requests, I can later try to make the changes with less commits and/or fix things as necessary

**Comment by kcgen** [comment]
Suggest squashing all this down to one commit; something like "Remove background circle from logos". 

Also suggest not creating "new" and "old" directories; just replace the files straight away (and add additional files, if more are needed too). 

The commit history of the repository maintains those old versions, so they will always be present in prior commits (so no need to move them to an "old" directory.. just replace them 👍). 

Will defer review and acceptance to @johnnovak , regarding how this factors into the documentation site.

**Comment by ThomasEricB** [comment]
> Suggest squashing all this down to one commit; something like "Remove background circle from logos".

Okay, I'll create a new pull request

**Comment by ThomasEricB** [comment]
I already deleted my repository. I'm going to do through git this time.

**Comment by ThomasEricB** [comment]
Procedeed with https://github.com/dosbox-staging/dosbox-staging/pull/2232

**Pull request closed without merging**
