### PR TITLE
PVS Studio warning fixes

### PR DESCRIPTION
**Pull request by FeralChild64**
# Description

Fixed few warnings.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by kcgen — APPROVED** [review]
Reviewed commit by comment, all looks great.
First time below 160 on the PVS front!



Created with:

```line_history.sh
git log --pretty=format:"%h %ad" --date=short --follow -- "$1" | \
while read commit_hash commit_date; do
  git show "$commit_hash" -- "$1" | grep "$2" | sed "s/^/$commit_date - /"
done
```

```
./line_history.sh .github/workflows/pvs-studio.yml "^+.*MAX_BUGS:" \
 | tac \
 | sed 's/ - +          MAX_BUGS: /,/g' \
 > pvs_bugs.csv

```

And to see when we updated PVS Studio:

```
.github/workflows/pvs-studio.yml "^+.*debfile:" | tac
```

**Comment by FeralChild64** [comment]
At some point we’ll need to dig into the CPU emulation code. There is about 60 warning originating there.

**Comment by kcgen** [comment]
> At some point we’ll need to dig into the CPU emulation code:

@FeralChild64:

**Comment by kcgen** [comment]
(I love that old pic of a kid digging into pancakes :-)

**Pull request merged**
