### PR TITLE
Guard against zero-height modes when setting up a new video mode

### PR DESCRIPTION
**Pull request by johnnovak**
# Description

Some games set up weird custom modes temporarily that result in a zero-height video mode (e.g., Impossible Mission II on Tandy). These are probably some tricks that work on hardware, but in software we need to guard against divide-by-zero exceptions downstream when calculating the aspect ratios.

Fixes https://github.com/dosbox-staging/dosbox-staging/issues/3436

# Manual testing

Impossible Mission 2 works with `machine = tandy` (use `IM2_TAN.EXE`).

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by weirddan455** [comment]
Yeah I was just looking into this.  This fixes the crash but there's a visual effect they were going for that doesn't look quite right with this fix applied.  Compare this branch to v0.80.1.

On v0.80.1 when the level starts, the video starts with a thin line in the center and expands out vertically until it fills the entire screen.  On this branch it just looks kind of janky.

**Comment by weirddan455** [comment]
Bisected the visual bug to your big double-scanning rework commit dd8ae1423a9d496f78fdcf39798568aea6bbadca

I just used this patch to work around the crash since it applies cleanly to everything from 0.80.1 to current main:

```
diff --git a/src/hardware/vga_other.cpp b/src/hardware/vga_other.cpp
index 308694ceb..4e473c7c3 100644
--- a/src/hardware/vga_other.cpp
+++ b/src/hardware/vga_other.cpp
@@ -87,7 +87,7 @@ static void write_crtc_data_other(io_port_t, io_val_t value, io_width_t)
                vga.other.vadjust = val;
                break;
        case 0x06:              //Vertical rows
-               if (vga.other.vdend ^ val) VGA_StartResize();
+               if ((val > 0) && (vga.other.vdend ^ val)) VGA_StartResize();
                vga.other.vdend = val;
                break;
        case 0x07:              //Vertical sync position
```

**Comment by johnnovak** [comment]
> I just used this patch to work around the crash since it applies cleanly to everything from 0.80.1 to current main:

Yeah, I actually like yours better. Please raise a PR and then I'll close this. It's better not to even call resize in this case.

> On v0.80.1 when the level starts, the video starts with a thin line in the center and expands out vertically until it fills the entire screen. On this branch it just looks kind of janky.

Indeed. Thanks for bisecting. I'm not quite keen on figuring this out right now, so could you please raise a ticket for it? Arguably, it's a minor thing but we should keep track of it and eventually fix it.

The crash fix, however, needs to go in now and we should backport it.

**Comment by johnnovak** [comment]
Fixed in https://github.com/dosbox-staging/dosbox-staging/pull/3448

**Pull request closed without merging**
