### PR TITLE
Fix a few mistakes, and convert more escape codes to ansi text

### PR DESCRIPTION
**Pull request by rderooy**
Also, add the 'nl' option to the CONFIG_LANGUAGE string of other languages.

Lastly, ran `encode.sh` to encode the utf-8 text files into lng

p.s. there is no ansi text code for clear screen?

### CODE REVIEW

**Comment by kcgen** [comment]
Can you snip out the added English soundfont blocks from the non-english .LNG files?

Ideally the LNG files should only contain translated messages.

For unmaintained/stale translations (like Spanish and French), the benefit is that untranslated messages will come from the the binary's source code, as opposed to a possibly a stale English version sitting in the LNG file. 

For example:
 If someone improves the soundfont conf wording tomorrow, then:
 - `main` French and Spanish users will see this newer wording (albeit in English).
 - but if we merge this PR as-is, then French and Spanish users will see the slightly outdated English wording, instead of the latest wording in the source code.

**Comment by kcgen** [comment]
Looks good, @rderooy !

Can you squash the second commit into the first? (otherwise it's a "wash", ie: adding text and then removing it.

**Comment by kcgen** [comment]
> p.s. there is no ansi text code for clear screen?

Yes; `git grep -B10 "clears all text"`

---

```c++
src/shell/shell.cpp-    MSG_Add("SHELL_CMD_CLS_HELP", "Clears the DOS screen.\n");
src/shell/shell.cpp-    MSG_Add("SHELL_CMD_CLS_HELP_LONG",
src/shell/shell.cpp-            "Usage:\n"
src/shell/shell.cpp-            "  [color=green]cls[reset]\n"
src/shell/shell.cpp-            "\n"
src/shell/shell.cpp-            "Where:\n"
src/shell/shell.cpp-            "  This command has no parameters.\n"
src/shell/shell.cpp-            "\n"
src/shell/shell.cpp-            "Notes:\n"
src/shell/shell.cpp:            "  Running [color=green]cls[reset] clears all texts on the DOS screen, except for the command\n"
```

``` c++

**Comment by rderooy** [comment]
@kcgen, I think we are talking about 2 different things. I was asking for something like `[cls]` (similar to how you can change colours and such) to clear the screen in help messages such as used for the `INFO` screens, not the dos `cls` command.

**Comment by kcgen** [comment]
> @kcgen, I think we are talking about 2 different things. I was asking for something like `[cls]` (similar to how you can change colours and such) to clear the screen in help messages such as used for the `INFO` screens, not the dos `cls` command.

Oh yes - I misunderstood.

Maybe 'reset' will do the job?

Here are all the tags (from the code):

```c++
	static inline const std::string light_prefix = "light-";

	static inline const std::unordered_map<std::string, TagDetail> tags = {
	        {"color", {Group::Colors, Type::Color}},
	        {"bgcolor", {Group::Colors, Type::BGColor}},
	        {"erasel", {Group::Erasers, Type::EraseL}},
	        {"erases", {Group::Erasers, Type::EraseS}},
	        {"i", {Group::Styles, Type::It}},
	        {"b", {Group::Styles, Type::Bold}},
	        {"u", {Group::Styles, Type::Ul}},
	        {"s", {Group::Styles, Type::Strike}},
	        {"blink", {Group::Styles, Type::Blink}},
	        {"dim", {Group::Styles, Type::Dim}},
	        {"hidden", {Group::Styles, Type::Hidden}},
	        {"inverse", {Group::Styles, Type::Inverse}},
	        {"reset", {Group::Misc, Type::Reset}},
	};

	static inline const std::unordered_map<std::string, ColorDetail> color_values = {
	        {"black", {Color::Black, false}},
	        {"red", {Color::Red, false}},
	        {"green", {Color::Green, false}},
	        {"yellow", {Color::Yellow, false}},
	        {"blue", {Color::Blue, false}},
	        {"magenta", {Color::Magenta, false}},
	        {"cyan", {Color::Cyan, false}},
	        {"white", {Color::White, false}},
	        {"default", {Color::Default, false}},
	        {"light-black", {Color::Black, true}},
	        {"light-red", {Color::Red, true}},
	        {"light-green", {Color::Green, true}},
	        {"light-yellow", {Color::Yellow, true}},
	        {"light-blue", {Color::Blue, true}},
	        {"light-magenta", {Color::Magenta, true}},
	        {"light-cyan", {Color::Cyan, true}},
	        {"light-white", {Color::White, true}},
	        {"light-default", {Color::Default, true}},
	};

	static inline const std::unordered_map<std::string, EraseExtents> eraser_extents = {
	        {"end", EraseExtents::End},
	        {"begin", EraseExtents::Begin},
	        {"entire", EraseExtents::Entire},
	};
};
```

And some unit tests here, which likely has most of the use cases covered:

`tests/ansi_code_markup_tests.cpp`

(Adding @shermp )

**Comment by rderooy** [comment]
I have squashed the commits. But the CONFIG_SOUNDFONT message was already in the utf-8 files before I did the first push. Running the `encode.sh` command just added them to the .lng files.

Regarding the `[reset]` command, that only resets the colors and such, it does not clear the screen as is done with the escape sequence at the beginning of the INFO screens.

**Comment by kcgen** [comment]
Indeed; it's no perfect; the encode script can't tell the difference if a string has been translated or not, it just does the codepage conversation. 

normally I try to exclude untranslated strings from making it into the resulting LNGs, (with `git add -p`), but when dealing with massive submissions this becomes a lot harder.

At least in this case, it's easy to see and removed. 

Hopefully the transition to gettext with eliminate a lot of these subtleties!

**Comment by kcgen** [comment]
Hmm.. I'm not sure then, how to clear the screen. Maybe this could be added to the markup commands (I recall it was possible using an escape sequence on real dos)

**Comment by shermp** [comment]
tag `[erases=entire]` *should* work (if my memory is correct)

**Pull request merged**
