### PR TITLE
WIP: metainfo + wire up linux stuff

### PR DESCRIPTION
**Pull request by okias**
Brings Linux support out-of-box.

Also includes metainfo file, which makes a nice product entry inside package managers, so users likely install this software.

- [ ] review by someone who understand automake mess :wink: 
- [ ] make it build

Based on
- https://github.com/FeignInt/dosbox-staging-deb/blob/debianish/debian/patches/linux_desktop_files.patch
- https://github.com/dosbox-staging/dosbox-staging/issues/351 @Kirtai

### CODE REVIEW

**Comment by okias** [comment]
rant - randomly working and not working git pushes. I must say, when github began, it was more reliable than when M$ own it..
```
Please make sure you have the correct access rights
and the repository exists.
client_loop: send disconnect: Broken pipe
fatal: Could not read from remote repository.
```

**Comment by kcgen** [comment]
Small tip: for PRs that you want to share but aren't finalized yet, use the 'Covert to Draft' toggle:

**Comment by okias** [comment]
thx, somehow didn't noticed that "WIP:" didn't changed that. I got used to Gitlab features :laughing:

**Comment by dreamer** [comment]
Not sure where are you going with this, (will reserve proper comments for the review), but I wanted to avoid storing png files directly in the repo. Packagers can either: 

- add any any SVG renderer as a build dependency and generate those icons (Makefily supports only `rsvg-convert`, but I am ok with making Makefile more generic)
- use scalable SVG icon only

the way I do it in our WIP Fedora spec file: [link](https://github.com/dosbox-staging/dosbox-staging/blob/po/fedora-spec/contrib/fedora/dosbox-staging.spec#L55)

 Ico file was an exception, because there is literally no way to generate ico file dynamically on Windows :/

The reason was: when developing an icon, I went through many iterations - storing all of those binary files in git would make repo unreasonably larger (considering it's only an icon).

That being said, if installing `rsvg-convert` or other SVG renderer as build dependency is a problem for some distributions, I am ok with bundling small png files. I just really would prefer to avoid it.

**Comment by okias** [comment]
My goal is end up shipping Linux build procedure, which starts with make and ends with complete all stuff (binary, icons, metadata). It's common for most projects. TBH I feel urge to die after experiencing automake after long time (most Linux & Win projects I know are already on CMake or switched to Meson). About bundling icons -> i'm not insisting on that, but since CI multiple CI jobs need it, I'd ship it (at least until I tune it up + I have been also been considering using SVG only).

**Comment by dreamer** [comment]
> TBH I feel urge to die after experiencing automake after long time 

Oh, we feel the same :( automake is causing us pain as well - our long-term plan is to replace it (not sure with what yet - I did some experiments with CMake, Meson, and Cargo). As for now, at least it's easy for packagers to copy dosbox build scripts.

**Comment by dreamer** [comment]
> About bundling icons -> i'm not insisting on that, but since CI multiple CI jobs need it, I'd ship it (at least until I tune it up + I have been also been considering using SVG only).

Initially we provided PNG files in all sizes (including large ones), and I iterated on design many times, so storing icons back then would be problematic, but nowadays all small PNG icons are below single-block size, and the icon is somewhat fixed for now, so it doesn't really matter. I would recommend including small icons beside the scalable one - they have adjustments to make the icon sharper (I picked sizes to fill all places where small icon is shown on Gnome and KDE).

**Comment by kcgen** [comment]
Despite being binary, atleast icons are relatively small and long-lived; so even if we can't represent them in a precusor format, the size burden should be trivial. 

Then again, 4k 'retina' icons might be another story!

Worst case, we could also purge all prior history of old icons to minimize space (BFG was a powerful tool I've had to use the the past, and I see https://github.com/newren/git-filter-repo is possibly the state of the art.. although avoid this path is always preferable :-).

**Comment by dreamer** [comment]
> Despite being binary, atleast icons are relatively small and long-lived; so even if we can't represent them in a precusor format, the size burden should be trivial.
> 
> Then again, 4k 'retina' icons might be another story!

Oh, no - I won't bundle .icns file in repo (it does already include 'retina' versions of the icons). macOS does not support scalable icons, so resulting icns file is way too big binary file for storing in Git.

> Worst case, we could also purge all prior history of old icons to minimize space (BFG was a powerful tool I've had to use the the past, and I see https://github.com/newren/git-filter-repo is possibly the state of the art), although avoiding this path is always preferable :-).

BFG is great tool (argh, I still need to submit my patches to that project), but we can't use it in this case (unless we would be ok with rewriting the master branch, but it would invalidate many references to specific commits). I prefer to keep our master branch free of large binary artifacts (but files below 2KiB are perfectly fine - all small PNGs fall in this category, files below 4KiB are acceptable).

**Comment by kcgen** [comment]
> (use of BFG) would invalidate many references to specific commits. 

Ahh; excellent point and that alone likely makes it's use a show stopper.

> I prefer to keep our master branch free of large binary artifacts (but files below 2KiB are perfectly fine - all small PNGs fall in this category, binaries below 4KiB are acceptable).

I like that policy!

**Comment by dreamer** [comment]
@okias I think the majority of work from this draft is either addressed or WIP now :)

- Pre-rendered png icons -> it's on master already, can be installed with `make -C contrib/icons install` (run `make -C contrib/icons help` for details)
- metainfo.xml -> initial version of XML file is merged
- installing more stuff with automake buildsystem -> we really don't want to do this, because autotools is messy. We are rewriting the buildsystem in meson though, so when it'll be ready I think it'll be much easier to install exactly the stuff we want, exactly in places we want.

**Comment by dreamer** [comment]
The buildsystem was replaced by Meson few days ago, I think 100% changes that were suggested in this PR is implemented already :) Closing to clean up PR queue a bit.

**Pull request closed without merging**
