### PR TITLE
Fix or simplify some descriptions

### LINKED ISSUE #3061: Errors/typing mistakes with dosbox --help and dosbox -v commands
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

Windows 11

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I noticed some errors/typing errors:
`  --noprimaryconf          Don't load or create the the primary configuration file.`
Double **the**

`  -c <command>             Run the specified DOS command before running FILE.`
Shouldn't it be **PATH**?

-----
```
:PROGRAM_CONFIG_SET_SYNTAX
Usage: [color=light-green]config [/reset]-set [color=light-cyan][SECTION][/reset] [color=white]PROPERTY[/reset][=][color=white]VALUE[/reset]

.
```
Why `[/reset]` and not `[reset]`?

-----

`dosbox --version` works but `dosbox -v` doesn't:
```
dosbox --version
dosbox-staging, version 0.81.0-alpha-1864-g2d0fcb92c

Copyright (C) 2020-2023  The DOSBox Staging Team
License: GNU GPL-2.0-or-later <https://www.gnu.org/licenses/gpl-2.0.html>

This is free software, and you are welcome to change and redistribute it under
certain conditions; please read the COPYING file thoroughly before doing so.
There is NO WARRANTY, to the extent permitted by law.
```

```
dosbox -v
CHECK FAILED:  arg_it < argc  (2 < 2)  Missing verbosity level after -v
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run on Windows Powershell or CMD `dosbox --help` and `dosbox -v`

### Download URL of affected game or software

_No response_

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
# Description

Fixes or simplifies some descriptions.

## Related issues

Fixes #3061 

# Manual testing

Tested:
 - printing the updated CLI `--help` hows updated text
 - printing man page shows updated text
 - writing a new conf files has updated text
 - passing `-V` prints the version
 - printing `config /help` handles the `[reset]` tag:

    

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by Grounded0** [comment]
@kcgen 

Can you just use latest release of:

https://anttipeltola.eu/docs/dosbox.1

It now incorporates your fixes and is actually 100% in lockstep with the console help page unlike yesterdays release.

**Comment by kcgen** [comment]
> https://anttipeltola.eu/docs/dosbox.1

Thanks @Grounded0; updated.

**Review by Grounded0 — APPROVED** [review]

**Review by Kappa971 — APPROVED** [review]
👍

**Comment by kcgen** [comment]
Typo's are all fixed and the pre-agreed chorus/reverb/crossfeed note has been snipped. Let's carry on.

**Comment by kcgen** [comment]
Thanks for the review guys.

**Comment by johnnovak** [comment]
Nice one @kcgen 👍🏻

**Pull request merged**
