### PR TITLE
Open the requested MIDI handler early and asynchronously [3/4]

### PR DESCRIPTION
**Pull request by kcgen**
**Motivation**
 - discussed in issue #735, items 3 and 4.

**Background**
 - The existing MIDI manager opens the requested MIDI handler with fallback to trying the default handlers (ALSA, OSS, and so on).
 - This task of opening the MIDI device needs to be finished when the emulated MPU401 asks the MIDI manager if MIDI is _**Available**_.

**Challenge**
 - We know that setting up MIDI (especially FluidSynth) is both CPU and IO intensive, often parsing several hundred MB worth of SF2 content and loading it into the synthesizer. 
 - So to eliminate as much of this time as possible, we want to start this loading as soon as possible **_and_** we want to do it in parallel with DOSBox's other startup activities.
 - We're free to run in parallel until the MPU401 asks us if we're ready.

**Approach**
- This PR leverages the new `EarlyInit` configuration sections to get MIDI's dependencies (like the SDL audio and mixer initialized) as-soon-as-possible, and from there we Init the MIDI handler early.
- We then kick off the MIDI Open() task in the background, and join (wait for the thread to finish) only when the MPU401 asks if we're available.
- It's at that point where we, if needed, can fallback to opening system MIDI devices if FluidSynth or MT32 failed to open. 

With this approach in mind, I suggest reviewing commit-by-commit. 

I've tested the following permutations successfully:
 
- mididevice = fluidsynth, that has a good config (passes) 
- mididevice = mt32, that has a good config (passes)
- mididevice = fluidsynth, that has a bad config, but midiconfig = 128:0 + Qsynth working (passes) 
- mididevice = mt32, that has a bad config, but midifconfig = 128:0 + Munt working (passes)
- mididevice = fluidsynth, that has a bad config, and midiconfig is bad. (Midi does not open, as expected) 
- mididevice = mt32, that has a bad config, but midifconfig is bad (Midi does not open, as expected)
- mididevice = auto and midiconfig = 128:0 + Qsynth working (passes) 
- mididevice = auto and midifconfig = 128:0 + Munt working (passes)

### CODE REVIEW

**Comment by kcgen** [comment]
Rebased against master and re-ran against above tests (all passing).

**Review by dreamer — COMMENTED** [review]
I haven't dived deeply into this review yet, but it has an initial flaw. Before we want to do any refactors like this - we want to get rid of this stupid `handler_list` global variable. Before any other refactorizations are done, we need to remove the bad code that creates all MidiHandlers when emulator starts.

**Comment by kcgen** [comment]
> Before we want to do any refactors like this - we want to get rid of this stupid handler_list global variable. Before any other refactorizations are done, we need to remove the bad code that creates all MidiHandlers when emulator starts.

Yes - this was a strange nuance, and getting rid of it will reduce this PR to leveraging the early init feature plus the background-and-wait functions. 

I'm happy for you to take the lead on this this initial restructuring, and I'll adjust this PR to fit.  We can defer this to a time that suits, as the change is relatively stand-alone. (Then I'll move this to draft pending the restructure) 👍

**Comment by dreamer** [comment]
@kcgen yes, thank you :) We have a lot of changes in MIDI area already - MT32 introduced new static analysis issues, etc - let's not do revolutions with code that's partially disabled on master branch. We'll get back to it after migration will be done.

**Comment by kcgen** [comment]
FluidSynth 2.2 gained parallel SF2 loading (divide-and-conquer type loading), which typically reduces load times by a factor of ~3x. For example, monster 2+GB SF2s now takes 5 seconds to load instead of 15+ seconds.

As most Staging users will be using much smaller SF2s (between ~50 MiB and 500 MiB), the gains from this PR will be marginal with SF2 load times having improved so much with FS 2.2.x Therefore, I'm not sure the small increase in code complexity and churn is worth the (likely unnoticeable) benefit - so closing this PR for now.

**Pull request closed without merging**
