### PR TITLE
Cleanup Linux workflows, add LTO build

### PR DESCRIPTION
**Pull request by FeralChild64**
# Description

Linux workflows cleanup. This PR also adds LTO check to make sure the issue https://github.com/dosbox-staging/dosbox-staging/issues/3519 won't return.

## Related issues

https://github.com/dosbox-staging/dosbox-staging/issues/3519

# Manual testing

I have checked that adding a commit which reverts https://github.com/dosbox-staging/dosbox-staging/commit/8c9b65c2bee5f3c84693581b5496ec3f0d45b313 causes the modified workflows to fail as in issue https://github.com/dosbox-staging/dosbox-staging/issues/3519

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by weirddan455** [comment]
LTO on debug builds is a bit unusual, though it probably doesn't hurt anything for CI purposes unless they take significantly longer to build.

I would definitely add these extra compile flags to the Release build though, where we already have LTO enabled.

**Comment by johnnovak** [comment]
> LTO on debug builds is a bit unusual

I agree, can we drop LTO from the debug builds @FeralChild64 ? That's not how we build the debug builds locally either, and it's frankly pointless for non-optimised non-release builds.

**Comment by FeralChild64** [comment]
But nearly all the builds are currently debug ones - only the minimum GCC 9 build isn’t. I can try tomorrow, but I’m not sure if GCC 9 (the only one with the release workflow) is advanced enough for LTO.

**Comment by weirddan455** [comment]
>  But nearly all the builds are currently debug ones - only the minimum GCC 9 build isn’t. I can try tomorrow, but I’m not sure if GCC 9 (the only one with the release workflow) is advanced enough for LTO.

It's already doing LTO and has been for a while.

https://github.com/dosbox-staging/dosbox-staging/blob/d221c959e2323414ab7c210297228884913bce0f/.github/workflows/linux.yml#L326-L336

If it doesn't support the new flags, maybe it's time to bump the compiler version.  We just dropped support for Debian 10.  Ubuntu 20.04 and Debian 11 both have GCC 10 at least.

**Comment by johnnovak** [comment]
> But nearly all the builds are currently debug ones - only the minimum GCC 9 build isn’t.

As I see it, all we need is to add the strict LTO validation/check flags to the release build so it fails with errors. I'm not even sure adding LTO + strict validation to the debug builds adds much value as stuff in debug builds might be inlined differently (or not at all), etc.

> If it doesn't support the new flags, maybe it's time to bump the compiler version. We just dropped support for Debian 10. Ubuntu 20.04 and Debian 11 both have GCC 10 at least.

Sounds reasonable to move the minimum requirement forward as time progresses, yeah. Especially in Linux land.

**Comment by FeralChild64** [comment]
I have tried to cleanup the workflows - if I understand this file correctly, they are named wrongly. I bumped GCC 9 to GCC 10, for the LTO check I have added a GCC 13 build (the former GCC 9 was a minimal build, it was not really suitable for testing LTO) - but now some shell unit tests fail.

Unfortunately, I have to drop this attempt. I have already started to many topics, I won't have much time for the development (if t all) in the upcoming days, and digging now into shell unit tests is the last thing I have time for.

**Pull request closed without merging**
