### PR TITLE
Move GUS rendering to main thread

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

Fixes a regression from d75e1057f5c6f7854b7ab1d9b3874cc8a6b8afce
Some games like Blood heavily use DMA for digitized sound
This causes audio distortion likely due to a timing issue on memory reads

Moving GUS to the main thread resolves this issue
Will need to look for a better asynchronous solution in the future

## Related issues

#3993

# Release notes

Fixes audio distortion in Blood (unsure if you want to put this as the only release this was in was RC1)

# Manual testing

Tested Blood and the Show demo

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by interloper98** [comment]
That was quick! Was doing some testing and confirmed good in Duke 3D.

Before (`main`):

https://github.com/user-attachments/assets/490795bb-0c0a-434b-842f-7b7ba56755dc

PR:

https://github.com/user-attachments/assets/35f5308d-a9d9-4518-8626-5fb47011ab8f

Getting a hang when closing the emulator (looks like it's waiting on a mutex):

```
2024-10-20 22:47:27.425 | GUS: Activated 24 voices at 25725 Hz
2024-10-20 22:47:27.466 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz throttled VFR, scaled to 2132x1599 pixels with 1:1.2 (5:6) pixel aspect ratio
2024-10-20 22:47:28.932 | SDL: Exit requested
2024-10-20 22:47:28.932 | SDL: Exit requested
2024-10-20 22:47:28.933 | GUS: Audio was made up of 2% 8-bit 2-voice and 99% 16-bit 2-voice samples
2024-10-20 22:47:28.933 | GUS: Shutting down
^C

Loguru caught a signal: SIGINT
Stack trace:
24      0x56a918a2b7b5 _start + 37
23      0x7e67e3c4e28b __libc_start_main + 139
22      0x7e67e3c4e1ca /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x7e67e3c4e1ca]
21      0x56a918a2b8a2 main + 34
20      0x56a918f109f4 sdl_main(int, char**) + 5924
19      0x56a918f1b6dd std::unique_ptr<Config, std::default_delete<Config> >::reset(Config*) + 29
18      0x56a918f1ca3c std::__uniq_ptr_impl<Config, std::default_delete<Config> >::reset(Config*) + 92
17      0x56a918b76d4b std::default_delete<Config>::operator()(Config*) const + 43
16      0x56a918b61ed9 Config::~Config() + 217
15      0x56a918b61499 Section_prop::~Section_prop() + 25
14      0x56a918b611f4 Section_prop::~Section_prop() + 36
13      0x56a918b61398 Section::ExecuteDestroy(bool) + 184
12      0x56a918f7a839 ds(+0xda7839) [0x56a918f7a839]
11      0x56a918f81ded std::unique_ptr<Gus, std::default_delete<Gus> >::reset(Gus*) + 29
10      0x56a918f81e5c std::__uniq_ptr_impl<Gus, std::default_delete<Gus> >::reset(Gus*) + 92
9       0x56a918f81eec std::default_delete<Gus>::operator()(Gus*) const + 44
8       0x56a918f7b0b9 Gus::~Gus() + 25
7       0x56a918f7ae9d Gus::~Gus() + 109
6       0x56a918febf3f MIXER_LockMixerThread() + 239
5       0x56a918bf4a45 std::recursive_mutex::lock() + 21
```

**Comment by weirddan455** [comment]
>  That was quick! Was doing some testing and confirmed good in Duke 3D.

Yeah, I had done the work the other day on a local branch.  Was just talking to @johnnovak over Discord to confirm he wanted this for 0.82.0.

>  Getting a hang when closing the emulator (looks like it's waiting on a mutex)

I know what that is.  The GUS queue needs to be added to `MIXER_LockMixerThread()` and `MIXER_UnlockMixerThread()`.  Need to do a small bit of refactoring to get that added.

**Comment by weirddan455** [comment]
Ok, that should fix the deadlock.  Just had to copy + paste the GUS definitions into a header file so I could access the queue from `mixer.cpp`.

**Review by johnnovak — APPROVED** [review]
Nice quick fix @weirddan455 🎉 Tested it with a few GUS demos, no issues.

Ship it! 🚢 :shipit: 😎

**Comment by johnnovak** [comment]
> Fixes audio distortion in Blood (unsure if you want to put this as the only release this was in was RC1)

Yeah, so when it's a regression introduced by the RC, we don't list it @weirddan455.

**Pull request merged**
