### PR TITLE
Update Italian (it-it) translation

### PR DESCRIPTION
**Pull request by Kappa971**
Ciao, mi dispiace dirlo ma questo è il mio ultimo lavoro di traduzione, a meno di eventuali aggiunte o correzioni prima del rilascio di DOSBox Staging 0.81.
Questo per "l'ambiente di lavoro" tossico che si è creato qui, a causa di uno degli sviluppatori che evidentemente ha problemi di disabilità come bipolarità o autismo o forse è semplicemente egocentrico e maleducato. Più di una volta mi ha risposto in modo ostile, senza che ce ne fosse motivo e io finora ho sempre evitato di buttare benzina sul fuoco, seppur rispondendo in modo schietto e diretto.
Considerando che il prossimo passo sarebbe insultarlo pesantemente con le infinite combinazioni di imprecazioni e parolacce possibili con la lingua italiana, preferisco andarmene e chiudere qui il mio lavoro perchè tutto ciò sarebbe inutile.

Ringrazio tutti gli altri sviluppatori di questo progetto, ringrazio @kcgen, sempre molto gentile e disponibile.

Spero che qualcun altro, con molta più pazienza di me nel discutere con questo tipo di sviluppatore, possa continuare la traduzione.
Buon lavoro e Addio

-----

Hi, I'm sorry to say this but this is my last translation work, unless there are any additions or corrections before the release of DOSBox Staging 0.81.
This is because of the toxic "work environment" that has been created here, due to one of the developers who evidently has disability issues such as bipolarity or autism or perhaps is simply egocentric and rude. More than once he responded to me in a hostile way, without any reason and so far I always avoided adding "fuel to the fire", although I responded in a frank and direct manner.
Considering that the next step would be to insult him heavily with the infinite combinations of imprecations and swear words possible with the Italian language, I prefer to leave and close my work here because all this would be useless.

I thank all the other developers of this project, I thank @kcgen, always very kind and helpful.

I hope that someone else, with much more patience than me in arguing with this type of developer, can continue the translation.
Good work and Goodbye

### CODE REVIEW

**Comment by Torinde** [comment]
@Kappa971, I think your contribution is worthy, not only in translations and I hope whatever was said can be excused and everybody can play along well again.

**Comment by johnnovak** [comment]
That's a nice case of projection there @Kappa971... Good riddance, we absolutely don't need people in this project that bring down our spirits by continuous nagging _after they were told repeatedly to stop._ Good luck elsewhere.

**Comment by Kappa971** [comment]
> That's a nice case of projection there @Kappa971... Good riddance, we absolutely don't need people in this project that bring down our spirits by continuous nagging _after they were told repeatedly to stop._ Good luck elsewhere.

I started contributing to the project in 2021 for DOSBox Staging 0.77, I never had any problems with anyone, you weren't part of the project yet.
You don't show any respect towards people, you think that treating people badly is right and that you are right, and this last message confirms what I wrote above, perhaps it is you who "bring down the spirit".

I don't expect your apology, it would be too much for you.
I don't want to waste any more time arguing with you.

> @Kappa971, I think your contribution is worthy, not only in translations and I hope whatever was said can be excused and everybody can play along well again.

The guy above says I bring down the spirit so... I don't want to bring down this poor man's spirit

**Comment by johnnovak** [comment]
User banned due to repeatedly disregarding [our code of conduct](https://dosbox-staging.github.io/get-involved/code-of-conduct/), harassing the development team, not letting go of minor issues after repeatedly asked to stop, and probably a few other things.

**Review by johnnovak — APPROVED** [review]

**Comment by Kappa971** [comment]
The only thing I can reproach other developers for is allowing a member of the project (who arrived later) to bully another member. Maybe this type of developer damages the project and its image (in this case it did), I hope someone takes action unless he is untouchable. Bye

**Pull request merged**
