### PR TITLE
Update Italian (it-it) translation

### PR DESCRIPTION
**Pull request by Kappa971**
I would like to point out:
In `PROGRAM_IMGMOUNT_HELP_LONG`:
```
  [color=cyan]BOOTIMAGE[reset] is a bootable disk image with specified -size GEOMETRY:
            bytes-per-sector,sectors-per-head,heads,cylinders
```
And in `PROGRAM_IMGMOUNT_SPECIFY_GEOMETRY`:
```
bytes_per_sector, sectors_per_cylinder, heads_per_cylinder, cylinder_count.
```

Shouldn't they be indicated the same way?

### CODE REVIEW

**Comment by kcgen** [comment]
> Shouldn't they be indicated the same way?

Yes, they are both text / documentation, so should use the same notation; I've pushed a fixed for that.

**Comment by Kappa971** [comment]
> Yes, they are both text / documentation, so should use the same notation; I've pushed a fixed for that.

Also here:
[color=blue]IMGMOUNT drive-letter location-of-image -size **bps,spc,hpc,cyl]**[reset]

**Comment by kcgen** [comment]
@Kappa971 , can you fix the conflicts? (The 'Resolve conflicts' button below will give you a web editor to update the lines)

**Review by kcgen — APPROVED** [review]
Looks good @Kappa971 !

**Pull request merged**
