### PR TITLE
Avoid false positive warnings in translations

### PR DESCRIPTION
**Pull request by japsmits**
# Description

Avoid false positive warnings in translations, indicating a duplicate message.

Only check for duplicates in English, and report them only if the descriptive text differs.

Note that some code-paths indeed add the same translation ID multiple times, but as long as the text is the same, this is ignored. That's something for a future clean-up, I guess.

## Related issues

#3599 

# Manual testing

Ran DOSBox both with English and Dutch translations. No more messages occur. Also avoids the message when a command is executed.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
Thanks @japsmits 🎉 Could you please fill out the checklist as well please?

**Review by johnnovak — APPROVED** [review]
The change looks fine @japsmits. I'll let @FeralChild64 do the final approval as he's our localisation expert 😄

**Comment by japsmits** [comment]
Sounds like a plan! 😸

**Review by FeralChild64 — APPROVED** [review]
Well, looks OK to me, given the current state of the code.

IMHO this file needs to be reworked, we should store translated messages in a separate structure - this way it would be possible to detect duplicates / unneeded strings in translations, and also to switch the translation in the runtime. But this is a larger task, definitely out of scope of this PR.

**Comment by japsmits** [comment]
Agreed.

I'll rebase, and than it can go in.

**Pull request merged**
