### PR TITLE
Cleanup configure.ac

### PR DESCRIPTION
**Pull request by dreamer**
Remove some annoying cruft. Also, generate less verbose makefiles by default.

### CODE REVIEW

**Comment by kcgen** [comment]
This is really nice to use @dreamer ; I don't see any issues with it - and if CI is happy then it's a go for me.

This actually makes this "cd-in cd-out" nonsense for every file really jump out instead of being lost in the flood of text:

``` text
Making all in serialport
make[4]: Entering directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
  CXX      libserial.o
make[4]: Leaving directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
make[4]: Entering directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
  CXX      misc_util.o
make[4]: Leaving directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
make[4]: Entering directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
  CXX      directserial.o
make[4]: Leaving directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
make[4]: Entering directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
  CXX      nullmodem.o
make[4]: Leaving directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
make[4]: Entering directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
  CXX      serialdummy.o
make[4]: Leaving directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
make[4]: Entering directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
  CXX      serialport.o
make[4]: Leaving directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
make[4]: Entering directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
  CXX      softmodem.o
make[4]: Leaving directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
make[4]: Entering directory '/ssd_backup/src/dosbox-staging/src/hardware/serialport'
  AR       libserial.a
```

Can this be made to behave properly too?

**Comment by dreamer** [comment]
> Can this be made to behave properly too?

By building with `make -s`… I experimented with MAKEFLAGS to make it the default, but eventually backed down, as it's unclear to me how autoconf-overriden MAKEFLAGS might interact with user-overriden MAKEFLAGS.

**Comment by kcgen** [comment]
> > Can this be made to behave properly too?
> 
> By building with `make -s`… I experimented with MAKEFLAGS to make it the default, but eventually backed down, as it's unclear to me how autoconf-overriden MAKEFLAGS might interact with user-overriden MAKEFLAGS.

Maybe simply augment the list of MAKEFLAGS?
cmake appears to manage it; some discussion here: https://gitlab.kitware.com/cmake/cmake/-/issues/20487

**Comment by kcgen** [comment]
More here: https://www.gnu.org/software/automake/manual/html_node/Automake-Silent-Rules.html

**Comment by kcgen** [comment]
https://stackoverflow.com/a/8080887

Seems fair enough?

**Comment by kcgen** [comment]
That's a nice use of ?= , I wasn't aware of that syntax!
Looking forward to much cleaner build output; thanks @dreamer!

**Comment by dreamer** [comment]
@kcgen Thanks! :)

**Pull request merged**
