### PR TITLE
Add MkDocs sources of the new website

### PR DESCRIPTION
**Pull request by johnnovak**
This contains the conversion of the existing website as of the 0.80.0 release, plus some extra stuff (front page, about page, etc.)

The website generated from these sources can be viewed here:
https://www.johnnovak.net/dosbox-staging-new-website/

The next PR(s) will contain the GitHub actions and whatever we need to generate and deploy this automatically.

### CODE REVIEW

**Comment by johnnovak** [comment]
Ummm... I'm inclined to disable the markdown linter altogether for the website. As a long as the output looks correct, I don't care what weird syntax we need to put into the `.md` files, and that max length of line exceeded is not helpful either...

**Comment by kcgen** [comment]
As long as we have a review process, we can catch really nasty formatting. There are tools that can mass-format too, so maybe once a year we can run a tidy pass just tonormalize all the MDs.

Each of the linter's rules has a justification - maybe there's a subset that are agreeable?

https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md

In the root of the repo, there's `.mdlrc`, where we can knock out entire rules (including long-line check :sweat_smile: )

Here's the current ones we've disabled site-wide:

``` ini
rules "~MD005", "~MD033", "~MD046"
```

**Comment by shermp** [comment]
Just a small observation on the demo site:

On my machine, when I start scrolling the page away from the top, the top `Dosbox Staging` title jumps a little. It looks like an animation is triggered, a slide from the right when scrolling away from the top, and sliding from the left when returning to the top.

Windows 11, Chrome 108.0.5359.125

**Comment by shermp** [comment]
This is looking great @johnnovak 🎉 

I do have a question regarding the home page however. What is everyone's thoughts on the use of inline SVG in the home page? I'm personally not a fan, I think it makes the source harder to read. I guess the upside is the page can be fully rendered on initial page load. On the other hand, external svg's can be cached by the browser.

**Comment by johnnovak** [comment]
> This is looking great @johnnovak 🎉
> 
> I do have a question regarding the home page however. What is everyone's thoughts on the use of inline SVG in the home page? I'm personally not a fan, I think it makes the source harder to read. I guess the upside is the page can be fully rendered on initial page load. On the other hand, external svg's can be cached by the browser.

Thanks @shermp :)

Regarding the inline SVGs, MkDocs Material that I'm using inlines every single SVG icon. For example, check out the "Get involved" page:
https://www.johnnovak.net/dosbox-staging-new-website/get-involved/

Or any random page on the MkDocs Material website:
https://squidfunk.github.io/mkdocs-material/reference/

So I'm just following the same pattern on the front page as well. It seems that this is current best-practice regarding SVG icons, which actually makes a lot of sense because loading a large number of icons can incur long delays on page loads, and really they don't take up much space in the generated HTML, and I assume they compress quite well.

This page gives a good overview of the various options regarding SVG icons, but like I said, that's what MkDocs Material does anyway and I'm not gonna change that.

https://cloudfour.com/thinks/svg-icon-stress-test/

**Comment by johnnovak** [comment]
> Each of the linter's rules has a justification - maybe there's a subset that are agreeable?

I've played around with it for an hour, and you know what, I'm changing my opinion about it... I think it's useful. It has highlighted some problems in the new website that went unnoticed, so we'll keep it! 🎉 

But I had to disable quite a few rules as they can't deal with some of the more complex structures we're using. I've mass updated all our `.md` files so they conform to the rules; we can relax them further later on as necessary.

Let me know what you think.

**Comment by kcgen** [comment]
This is top notch, @johnnovak!

Before we all decide merge, I was thinking about the pros and cons of including the static media (images, audio, and videos) in the repo:

 - (con) Git as a text-differ: ([people](https://github.com/sourcegraph/sourcegraph/issues/1952)) ([will](https://robinwinslow.uk/dont-ever-commit-binary-files-to-git)) ([say](https://robinwinslow.uk/dont-ever-commit-binary-files-to-git)) that git was technically designed to version and diff text, and therefore binary data should never be included in a repo. Even if binaries were tiny or free to store, these people would avoid binaries.

 - (con) Storage limits: Thorough documentation includes media, and these will quickly add up. For example, Just one video from our 0.79 release weighs in 50 MB, 3x the size of our entire `/src/` tree (3rd party sources included).  GitHub [recommends limited repos to under 1 GB](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#removing-files-from-a-repositorys-history).

 - (con) Performance degradation: pushing and pulling larger repos takes more time, even for people on fast systems. This is magnified on systems with slower network and IO resources.

 - (con) Community backlash from 'experts': No doubt, some will see that we've included binary data and jump to the conclusion that we're obviously git newbies doing it wrong, without realizing we've carefully weighed the consequences.

 - (pro) Self-contained: Colocating the media files gives us perfect versioning of the documentation along-side the code, guaranteeing that all clones and forks have the entirety of DOSBox Staging as a self-contained package that can be browsed locally without the need for a network. This is a massive pro.

 - (pro) Unnatural bifurcation: Documentation comes in many forms, be it text, audio, pictures, and video. But it's all just documentation and should be treated the same. 

_"Dude, just host your videos on YouTube, recordings on SoundCloud, and pictures on Imagur!"_ is a not a solution!

Are there ways we can eliminate most/all of the cons, but still achieve a self-contained repo - some a clone fetches everything locally?

**Comment by shermp** [comment]
Also, cloning/pulling a large repo on a slow or limited connection (eg: mobile data, or hotel wifi) is an absolute PITA.

**Comment by johnnovak** [comment]
Very good points about the large files @kcgen and @shermp. I just store everything in git for my [photo](https://photo.johnnovak.net/) website and it works (it's well under 1GB), but we need to be a bit more refined for this project, agreed.

My quick thoughts:

- Video and MP3 files are the main culprits. I'm very hesitant to start moving simple image files elsewhere, but maybe we could make an exception for really large PNG screenshots (btw, I recommend using 100% quality JPEGs instead; it cuts the file size in half, and you're hard pressed to see any difference even at 400% zoom!)
- **Git-LFS** wouldn't help because all it does is only fetches the last version of a given large file, excluding its (potentially very large) history. But we're not really versioning video and mp3 files; it's very rare that we update them again after the initial commit, so this extension is not suited for our usage patterns.
- **git-annex** looks very cool, and I would consider using it. Basically, it creates "symlinks" to external sources for large files, then these files can be pulled down & managed with extra "git annex" commands. Very cool. It supports a bunch of different backends, Google Drive, S3, DropBox, etc. But luckily, we won't need it...
- ...because these large files are only referenced from the HTML files, they're not needed for anything else. So if we just simply host them externally, the external links will continue to work even when running the site locally (e.g. with `mkdocs serve`). Remember, we don't need versioning for these video and audio (and maybe large image) files.
- As an added benefit, if we offered a downloadable offline version of the documentation in the future, it actually makes sense that we don't bundle hundreds of megs worth of video and mp3 files with it... Those will still require internet access and will remain externally hosted, which is the best  tradeoff in my view.

So far so good, so where to host? The short story is, I don't want to see *any* sponsored advertisements on our website and documentation, I don't want to see embedded players with logos of commercial companies, neither do I want these external commercial entities collect information about our users. So while YouTube would be an obvious answer for videos (or is it?), it has very serious—and to me completely unacceptable— drawbacks:

- sponsored ads that you cannot disable (apparently not even for paid accounts anymore)
- embedding YouTube videos is a privacy breach, plain and simple
- their copyright claims are increasingly becoming a problem — it's only a matter of time they start removing and/or charging for "retro gaming" content and/or soundtracks
- YouTube branding that you cannot remove

Some further quick thoughts:

- Vimeo would be a good alternative, but we'd need to pay for it.
- SoundCloud is out of the question because of the their very intrusive embedded company-branded player, and free accounts are limited to 3 hours of content.
- Amazon S3 would be great, but it's paid, and [their pricing structure](https://www.cloudzero.com/blog/s3-pricing) makes my head spin...
- Google Drive offers 15 GB of space with their free accounts and you can effectively turn folders into static websites by making them "public on the web", so this would be a viable option.

---

All in all, while we could use Google Drive, I think the best option would be the Internet Archive as they not just allow but apparently even encourage hosting free content on their servers, and they have a quite nice embedded player. Now, their players are branded with the IA logo, but as their goals are compatible with ours and open-source in general, I see that actually as a feature 😄 

E.g. here's an example of embedding the a Long Play video of a Prince of Persia game:
https://archive.org/details/LP_Prince_of_Persia_Warrior_Within

There's lots of [embedding options](https://archive.org/help/video.php?identifier=LP_Prince_of_Persia_Warrior_Within)—click on the "Share" button, then on "Advanced embedding details, examples, and help!" to view the instructions. You can even test the different embedding options on that page. Nice!

I ended up using this:

`<iframe src="https://archive.org/embed/LP_Prince_of_Persia_Warrior_Within" width="800" height="600" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>`

Which looks like this:

image

Embedding audio files is equally easy and the player looks minimal and is quite nice.

For example:
https://archive.org/details/Callide-System_Shock_Mix_Series_Vol3

```
<iframe src="https://archive.org/embed/Callide-System_Shock_Mix_Series_Vol3" width="800" height="150" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen></iframe>
```

image

If everybody is happy with this approach, I'll upload all the the videos & audio files to archive.org then and update the PR accordingly.

I've noticed we already have a "DOSBox staging team" user (with bad capitalisation 😂) with a single upload, should be keep using this? Or shall I create a new one? @kcgen?

https://archive.org/details/dosbox-staging-v0.79.0

**Review by kcgen — APPROVED** [review]
Archive.org sounds like a perfect approach, @johnnovak !
I'm not sure who created that account; suggest you make a new one (and maybe we can ask archive.org to drop the other one).

**Comment by johnnovak** [comment]
> Archive.org sounds like a perfect approach, @johnnovak ! I'm not sure who created that account; suggest you make a new one (and maybe we can ask archive.org to drop the other one).

Sounds like a plan! And sorry for the information overload; I swear I wanted to spend 10 minutes on my "quick comments" in the above post... then it became a 90 minute exercise 🤦🏻

**Comment by GranMinigun** [comment]
TuxFamily anyone?

**Comment by kcgen** [comment]
> > Archive.org sounds like a perfect approach, @johnnovak ! I'm not sure who created that account; suggest you make a new one (and maybe we can ask archive.org to drop the other one).
> 
> Sounds like a plan! And sorry for the information overload; I swear I wanted to spend 10 minutes on my "quick comments" in the above post... then it became a 90 minute exercise 🤦🏻

I appreciate it; it's great to have this on record if anyone has questions or if we want to change things, we can revisit the reasoning that lead to this point. 

Archive is especially nice with the Python PIP client. It's very easy to perform all sorts of operations on a collection from the CLI.

Not sure if this is all set for merge (if the blobs have been removed from the branch?). Please merge when you feel it's all good, @johnnovak.

**Comment by johnnovak** [comment]
> Archive is especially nice with the Python PIP client. It's very easy to perform all sorts of operations on a collection from the CLI.

About collections, it seems like you need to have at least 50 items of the same time until you are eligible to ask for a collection to be created for you (it's a manual process, you need to send the admins an email).

Then when the collection has been created, you can add admins to it (again, by asking the IA admins).

So it appears to me we don't need a shared "DOSBox Staging" account or something, but instead I should just upload these files using my own account ("John Novak"), then once we've reached the 50-item limit we can apply for a "DOSBox Staging" collection. After that, we can have our personal IA accounts added to that collection so we can all manage it?

Sounds about right @kcgen? (I'm unfamiliar with this whole collections business yet)

**Comment by shermp** [comment]
If possible, wouldn't it be better to use direct links to files rather than embedded iframes? HTML5 has the `<video>` and `<audio>` tags to provide basic player support. This would also mean minimal user facing changes if we ever decided to host the files elsewhere.

**Comment by johnnovak** [comment]
> If possible, wouldn't it be better to use direct links to files rather than embedded iframes? HTML5 has the `<video>` and `<audio>` tags to provide basic player support. This would also mean minimal user facing changes if we ever decided to host the files elsewhere.

I fully agree, and looks like it's actually possible by linking to the "download" link of the mp3/mp4 directly, I just haven't tried hard enough :) I'll do it like that.

**Comment by Torinde** [comment]
Comparing the current and new websites:
- I didn't see RSS in new: https://dosbox-staging.github.io/rss.xml
- I didn't see the "Content on this site is licensed under a ..." and "DOSBox Staging is licensed under a ..."
 
Both sites have two broken links:
- A summary of technical and feature differences is [here](https://github.com/dosbox-staging/dosbox-staging#summary-of-differences-compared-to-upstream).
- We plan to add the features listed in [the backlog](https://github.com/dosbox-staging/dosbox-staging/projects/3).

Related to the last point - I see there are 4 github projects:
image
But when clicking on that tab I get only one - "0.81 Project". In the past I think there were "ECE patches", "retroeXo features", "backlog", but now I don't see any of those?

**Comment by johnnovak** [comment]
> Comparing the current and new websites:
> 
>     * I didn't see RSS in new: https://dosbox-staging.github.io/rss.xml

I don't think RSS would make much sense until we have a proper blog, so dropping it altogether for now.

>     * I didn't see the "Content on this site is licensed under a ..." and "DOSBox Staging is licensed under a ..." in new About.

Thanks, I'll add that.

> Both sites have two broken links in About/Vision:
> 
>     * A summary of technical and feature differences is [here](https://github.com/dosbox-staging/dosbox-staging#summary-of-differences-compared-to-upstream).
> 
>     * We plan to add the features listed in [the backlog](https://github.com/dosbox-staging/dosbox-staging/projects/3).

Cheers, I'll fix those—I just copied the links and apparently never tried them if they work at all :) That actually reminds me to run the site through a dead link checker service once it's published.

> Related to the last point - I see there are 4 github projects: image But when clicking on that tab I get only one - "0.81 Project". In the past I think there were "ECE patches", "retroeXo features", "backlog", but now I don't see any of those?

Not sure, maybe @kcgen can answer?

**Comment by kcgen** [comment]
GitHub's has had two project types for a couple years, the "new" style seen in the 0.8x projects, and the "old" style in the now-missing projects. 

It could be that GitHub finally "sunsetted" those older ones and is pushing the new style. But we can see the quantity is still 4.. so I just have to figure out how to show the old-style projects, too (and probably convert them to the new style).

**Comment by Torinde** [comment]
Maybe Github is disabling the "Projects (classic)" gradually - right now I see those in other repositories:
image

**Comment by johnnovak** [comment]
I've removed the link to the "backlog" altogether because, well, we don't seem to have one anyway 😄

**Comment by kcgen** [comment]
> Related to the last point - I see there are 4 github projects:
> image
> But when clicking on that tab I get only one - "0.81 Project". In the past I think there were "ECE patches", "retroeXo features", "backlog", but now I don't see any of those?

@Torinde - found the toggle to (re)enable the old-style projects. Hopefully you can see all four now.

**Comment by johnnovak** [comment]
Okay, I'll put the link back to the backlog then, after all. That alright with you @kcgen?
https://github.com/dosbox-staging/dosbox-staging/projects/3

Personally, I like that board; it gives you a nice overview of what's in-flight, planned, etc.

**Comment by kcgen** [comment]
> Okay, I'll put the link back to the backlog then, after all. That alright with you @kcgen? https://github.com/dosbox-staging/dosbox-staging/projects/3

Definitely; please do!

> Personally, I like that board; it gives you a nice overview of what's in-flight, planned, etc.

I also prefer the Kannan. 

Not sure why GitHub is trying to phase it out, and is pushing the original so hard.

Hmm.. could be that Microsoft is trying to underpin it with their web-Excel system, and likely tie it into whatever management tools they have. 🤦‍♂️

**Comment by johnnovak** [comment]
> I also prefer the Kanban.

Oh yeah, I also prefer things that work (notice the subtext... 😏)

> Not sure why GitHub is trying to phase it out, and is pushing the new style so hard (they even describe it as excel-like).
>
> Hmm.. could be that Microsoft is trying to underpin it with their web-Excel system, and tie it into eMsOffice suite? 🤦‍♂️

Micro$oft being Micro$oft, I wouldn't be surprised.

This reminds me of a Hungarian saying that could be translated into this hilarious English sentence: "The dog can't turn into a bacon." (= some things just never change, no matter what)

**Comment by Torinde** [comment]
old-style projects are visible now, yes.

**Comment by johnnovak** [comment]
All audio files, videos and images files used in the release notes are now hosted on archive.org under my account:
https://archive.org/details/@john_novak

I've removed these binary files from the initial commit so they won't clog up our history once this is merged.

The generated website can be viewed here:
https://www.johnnovak.net/dosbox-staging-new-website/

If everyone's happy, let's merge this, then I'll create the deploy actions, workflows or whatever is needed in a separate PR later.

**Comment by kcgen** [comment]
Checked the sizes, and confirmed all the big media files are now gone from the branch (and history); which is perfect. 

For the commits - would it be possible to take a pass through and combine the repeated commits that roughly cover the same themes? (Like maybe all the "move image/video/audio to archive.org" could be collapsed into one commit?)

Just wanting to reduce some visual churn, given (I don't think) we'll need to bisect into these individually to diagnose regressions in the website.

**Comment by kcgen** [comment]
All looks good from my side, @johnnovak.  Clear for you to merge, when you like.

**Comment by johnnovak** [comment]
Thanks @kcgen , I've just pushed the big button! 😎

**Pull request merged**
