### PR TITLE
Render video lines one-by-one even in high resolution modes

### LINKED ISSUE #3248: Microsoft Space Simulator (1994)
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.0a

### What Operating System are you using?

Windows 11

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This game seems to suffer from two other issues that still haunt Staging and most other Dosbox forks.

1. Its a flickering mess from the moment you are in the cockpit. As per #3244, #2905 & #2950 the copy of Daum included in eXoDOS fixes it.
2. There is a speed issue as per #2751. At around 50k you can move around fine (maybe even a bit slowly) while the Earth is in view. The second Earth is of screen you flick around in the blink of an eye to have the Earth back on screen

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play the game in Staging 81.0a
2.
3.

### Download URL of affected game or software

_No response_

### Your configuration

_No response_

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
# Description

Previously, high resolution (800×600 and up) video modes were rendered out from the emulated video card as whole frames. That is, we waited until vblank at which point the entire block of the emulated video card's memory (as indicated by the game) was rendered out by the emulated card.

The _rendering out_ process emulates the video card's DAC pipeline by reading a row from memory (written by the DOS application) and scanning it out to the CRT. This is where line and row doubling may happen, such as when VGA 320×200 modes are doubled at the analog signal level up to 640×400 which hits the CRT.

(To clarify for readers: the above is all still in hardware emulation - the vga_draw* and render* code, and comes before any involvement with the host presentation side such as SDL, OpenGL, shaders, etc.)

This commit changes that behaviour to render out at the row level (per row of digital pixel data in the video card's memory). Each row has a PIC timer setup to render the row as soon as the time comes when it would be drawn to the CRT. This is similar to how lower resolutions are handled.  It allows sophisticated games to start writing the next frame's line data “behind the beam”.

This fixes a regression in Microsoft's Space Simulator that was flickering at 800×600 with the previous whole frame approach.

There's a performance hit on memory-limited systems like the Pi 4: Quake at 800×600 drops from 11.5 fps to 7.8 fps, but this is simply the cost of doing things correctly (and it's critical for games that rely on this more accurate behaviour).

On faster systems, the performance hit is in the noise, so overall users won't be affected because Pi 4 users typically run games in their lowest, highest performance resolution anyway.

## Related issues

Fixes #3248 

# Manual testing

## Microsoft Space Simulator

Microsoft Space Simulator is an early 1994 real-mode game with only 386 CPU requirements. In addition to this rendering issue, its physics engine can run away at high cycle counts, so needs to be held back to reasonable period-correct rates.

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/ba07e066-ba2c-46ac-9d8c-765818255063

- **`dosbox.conf`**:
    
    ```ini
    [cpu]
    cycles = max 100% limit 60000
    ```

- **`SETUP.EXE` configured**:

    1. 800×600
    2. VESA 1.2

- **In-game settings**:
    Preferences -> precision -> max level 8

    [SPACESIM/SPACESIM.INI](https://github.com/dosbox-staging/dosbox-staging/files/13745230/SPACESIM.INI.ZIP)

    The precision can be directly set on line 34 of the `SPACESIM/SPACESIM.INI` text file. A host tool, like GNU `sed`, can be used to set it:

    ```shell
    sed -i '34s/.*/08/' SPACESIM/SPACESIM.INI
    ```

---

Regression tested Quake, VBETEST, and Screamer without issue.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by kcgen** [comment]
(Suggest we cherry-pick this into 0.81.0-rc2 or final)

**Comment by Grounded0** [comment]
Since performance is now better than in 0.80.1 we can be more accurate too.

**Review by Grounded0 — APPROVED** [review]

**Comment by johnnovak** [comment]
Great quick fix @kcgen 🎉 The performance hit is not too bad either. Yeah best not to do it as a last minute RC1 change.

**Review by johnnovak — APPROVED** [review]

**Comment by johnnovak** [comment]
One question, though. Do we understand why this was a regression, and why this is fixing it? In 0.80.1, this was not flickering even without the render-by-line approach.

**Comment by kcgen** [comment]
> One question, though. Do we understand why this was a regression, and why this is fixing it? In 0.80.1, this was not flickering even without the render-by-line approach.

Yup, 0.80.1 and prior (through to upstream SVN and 0.74) emulates the rendering out to the CRT in chunks of rows, where the chunk was a quarter of the total number of vertical lines. This chunked approach is a coarser version of the per-line approach: it works so long as the game doesn't start drawing the next frame's content at the start of the chunk by the time you grab the memory at the end of the chunk (and no doubt: quarter sized chunked was probably the sweet spot).

**Comment by johnnovak** [comment]
Thanks for the explanation @kcgen. With this change we're not just restoring previous correct behaviour then, but we're potentionally increasing compatibility for all other programs that use SVGA / VESA modes. Nice! 🎉

**Comment by Grounded0** [comment]
Can someone run Quake 800x600 benchmarks with this against 0.81 RC1 and report the results on a half decent machine like Intel Skylake. Thanks.

**Review by johnnovak — APPROVED** [review]
Nice improvement 👍🏻

**Comment by kcgen** [comment]
With 0.82 in place, merging.

**Pull request merged**
