### PR TITLE
Fix a minor leak in the paging module

### PR DESCRIPTION
**Pull request by kcgen**
Reproduce by building the latest source as follows:

**macOS**

Use the command-line `leaks` tool after building the binary with `meson setup build-debug -Doptimization=0 -Dbuildtype=debug`

**Linux**

``` shell
CC="ccache gcc" CXX="ccache g++" \
meson setup -Dbuildtype=debug -Db_sanitize=address,undefined \
    -Doptimization=0 -Db_lundef=false -Dc_args=-fsanitize-recover=all \
    -Dcpp_args=-fsanitize-recover=all -Ddefault_library=static \
    -Dfluidsynth:enable-floats=true -Dfluidsynth:try-static-deps=true \
    build/gcc-ausan

meson compile -C build/gcc-ausan
```

Run Quake, then exit from its menu back to the command line, and then close the program.

Rebuild this PR branch `kc/paging-leak-1` with the same settings. It should exit clean.

### CODE REVIEW

**Comment by kklobe** [comment]
I'm unable to confirm a leak using `meson setup build-debug -Doptimization=0 -Dbuildtype=debug`

```
Process:         dosbox [20450]
Path:            /Users/USER/*/dosbox
Load Address:    0x100ee8000
Identifier:      dosbox
Version:         ???
Code Type:       ARM64
Platform:        macOS
Parent Process:  leaks [20449]

Date/Time:       2021-08-07 22:03:21.518 -0500
Launch Time:     2021-08-07 22:02:52.010 -0500
OS Version:      macOS 11.5.1 (20G80)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
Analysis Tool Version:  Xcode 12.5.1 (12E507)

Physical footprint:         115.1M
Physical footprint (peak):  133.8M
----

leaks Report Version: 4.0
Process 20450: 34367 nodes malloced for 24896 KB
Process 20450: 0 leaks for 0 total leaked bytes.
```

**Comment by kcgen** [comment]
@kklobe, on Linux, I found that Clang wasn't able to detect it either.

I wonder if GCC has ASAN and UBSAN on macOS?

`CC="ccache gcc" CXX="ccache g++" meson setup -Dbuildtype=debug -Db_sanitize=address,undefined  -Doptimization=0 -Db_lundef=false -Dc_args=-fsanitize-recover=all -Dcpp_args=-fsanitize-recover=all ...`

**Comment by kklobe** [comment]
The GCC setup isn't building for me properly (GCC 11 via homebrew), but I will confirm that the branch also shows no leaks!

**Comment by kcgen** [comment]
> The GCC setup isn't building for me properly (GCC 11 via homebrew), but I will confirm that the branch also shows no leaks!

Darn. Maybe the *SAN stuff isn't working on macOS for GCC. It's a challenge to get good leak detection on mac these days! 

Thankfully this is only 16-bytes, one-time per run.. so zero consequence. If you look at `paging.cpp` line 890` (from the screenshot), it's a simple `new` but without matching delete in the destructor.

**Review by kklobe — COMMENTED** [review]
Looks good to me. I cannot reproduce the leak itself on macOS, but I can also confirm that the fix also does not produce a leak!

**Pull request merged**
