### PR TITLE
Add C++ Core Guidelines analysis to CI

### PR DESCRIPTION
**Pull request by kcgen**
This adds [C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md) analysis to the CI Analysis workflow.

Here are some typical warnings:

- `C26460: The reference argument 'pathname' for function 'CDROM_Interface_Image::GetRealFileName' can be marked as const (con.3)`

- `C26496: The variable 'pos' is assigned only once, mark it as const (con.4)`

- `C26440: Function 'CDROM_Image_Destroy' can be declared 'noexcept' (f.6)`

- `C26486: Don't pass a pointer that may be invalid to a function. Parameter 0 '@track_file' in call to 'icall' may be invalid (lifetime.3)`

- `C26447: The function is declared 'noexcept' but calls function 'StopAudio()' which may throw exceptions (f.6)`

The warning number can be looked up here `https://docs.microsoft.com/en-us/cpp/code-quality/c<number>`, which sometimes contains a bit more info than the document. The trailing `(x.z)`notation refers to chapter and subsection in the guidelines document.

The goal is that this will offload some code-review burden (even before PRs get to the review phase), as these warnings  are quite thorough and catch different issues versus `effc++`, for example.

Right now the workflow isn't gated: I couldn't figure out how to get the Python issue-counter to include them despite them following the same pattern as normal VS warnings.  However, the goal will be to gate on them.

Although the full analysis tallies to over ~20k warnings, typically developers will be focusing on just a couple files they're working on - and in that case, it's quite manageable.

Here's the full-log of a run: [dosbox_staging_cpp_core_guidelines.txt.gz](https://github.com/dosbox-staging/dosbox-staging/files/5114621/dosbox_staging_cpp_core_guidelines.txt.gz)

Because the analysis requires compilation and post-binary analysis, it does take longer than a typical build (roughly 9 minutes).  Fortunately the analysis takes slightly less time than the current cache-enabled Windows workflow; so overall should not push out our CI times either.

### CODE REVIEW

**Comment by kcgen** [comment]
This build is now failing with: `cl : command line error D8040: error creating or communicating with child process`, which is a bug in the compiler (https://developercommunity.visualstudio.com/content/problem/254324/cl-command-line-error-d8040.html).

It was passing last week, so the only explanation I have is that VisualStudio has introduced this in their latest updates (which would be apart of this week's VM).  If this persists next week I'll figure out how to submit a bug report to the VS team.

**Comment by MasterO2** [comment]
What's the status of this PR then, @kcgen ?

**Comment by kcgen** [comment]
Let give it another spin on the current GitHub VM's (presumably using the latest VS 2019 update).
If it's still broken, I'll take down this PR and try to submit an issue to Microsoft.

**Comment by MasterO2** [comment]
> 
> 
> Let's give it another spin on the current GitHub VMs (presumably using the latest VS 2019 update).
> If it's still broken, I'll take down this PR and try to submit an issue to Microsoft.

@kcgen Looks like it's still broken: ```Code analysis / C++ Core Guidelines analysis (push) Failing after 10m```

**Comment by kcgen** [comment]
Taking this PR down due to Microsoft's compiler crashing with this configuration.

**Comment by dreamer** [comment]
@kcgen Thank you for closing this PR.

I was somewhat dismayed by the quality of the reports generated by C++ Core Guidelines analyzer. I looked at some of those issues reported and… they were hamifisting modern C++ into code, that would be much better served/easier to optimize/**easier to read and understand** with plain C types.

I still believe Core Guidelines in general are good, but I prefer to keep dosbox-staging as "C-like C++".

**Comment by kcgen** [comment]
Sounds good @dreamer, and thanks for stating your thoughts. 

 Good point.. definitely some portion of the issues were trying to C++'ify some C-like statements with little value added.  While others (when directed purely at c++ constructs), were more constructive.  So I saw it offering value there.  

I think as each warning is numbered, we could have added exclusions for those unhelpful ones and just kept the high-value set.

**Pull request closed without merging**
