### PR TITLE
Fix compilation for devkit pro toolchain

### PR DESCRIPTION
**Pull request by dreamer**
It's a GCC cross-compiler targeting PPC intended for homebrew development for
various Nintendo devices (like GameCube).

Imported-from: https://www.vogons.org/viewtopic.php?p=845410#p845410

### CODE REVIEW

**Comment by dreamer** [comment]
@realnc I noticed you submitted this patch upstream and decided it might be handy to merge it in even earlier.

I also noticed you submitted a different patch: https://www.vogons.org/viewtopic.php?p=848624#p848624 - but we don't need that one, as we made exactly the same fix several months ago.

**Comment by realnc** [comment]
phcoder should be tagged as the author of this patch:

https://github.com/libretro/dosbox-svn/commit/8efdec84cb45a03c8bc2d59ce4d365f5d2b87c2c

**Comment by dreamer** [comment]
@realnc thank you! I updated the author info and used commit subject from the original commit.

**Comment by dreamer** [comment]
Well, this is nice :) It seems like other dosbox-derived projects care about such "mundane" fixes, and not only us ;)

Thanks for a quick review!

**Pull request merged**
