### PR TITLE
Revert the event throttle PR

### PR DESCRIPTION
**Pull request by kcgen**
This caused unexpected input lag for some users, as reported here: https://github.com/dosbox-staging/dosbox-staging/commit/ff42c8e400e46f8f2f4a2b66738d5b8d7e1a6d7e#commitcomment-54450525

Will retest on all platforms before merging.

Will also plan to backport to 0.77.1.

### CODE REVIEW

**Comment by 0mnicydle** [comment]
I just wanted to report that this branch indeed fixed my mouse issues. Thank you so much for being open to making this change!

**Comment by kcgen** [comment]
As this simply reverts to a previously working state (now with regressions addressed), I'm inclined to merge this to get this bug off our plate, and ensure it's not "tangled up" with other ongoing PRs.

**Comment by dreamer** [comment]
@kcgen I agree with reverting this change; we need to spend a bit more time on testing it with following scenarios:

- for users with variable refresh rate
- for users with refresh rate that's not exactly an integer (e.g. often 59.94Hz is being reported in various places as 60Hz - calculation in the code was using integer math)

**Review by dreamer — APPROVED** [review]

**Comment by kcgen** [comment]
@dreamer  - great points regarding variable and non-integer refresh rates. This is something we can try to better accommodate and test in the future, if we want to re-introduce this feature.

Unfortunately we already had cranked up event queries to a fixed-200 Hz in the last update (independent of screen refresh rates); and that still didn't do the trick for some users; so we're back to the full 1000 Hz.

**Pull request merged**
