### PR TITLE
LTO build fix

### PR DESCRIPTION
**Pull request by FeralChild64**
# Description

Fix for LTO build, as described in the related issue. Just renamed few types (search&replace development).

## Related issues

Fixes https://github.com/dosbox-staging/dosbox-staging/issues/3519

# Manual testing

SiSoft Sandra 2001 CPU benchmark shows a 3%-5% performance increase for the LTO build on my system

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by weirddan455 — APPROVED** [review]
Looks good to me

**Review by johnnovak — APPROVED** [review]

**Comment by johnnovak** [comment]
Nice one @FeralChild64. Wasn't aware the fix is this simple! 😄

**Comment by FeralChild64** [comment]
We should probably add appropriate flags to one or more jobs to make sure we won’t break the LTO again.

**Comment by weirddan455** [comment]
Yeah, I think we have LTO enabled for the release builds already.  Adding the extra warning flags is a good idea.

**Pull request merged**
