### PR TITLE
Fix a couple of FPU emulation issues

### PR DESCRIPTION
**Pull request by kklobe**
# Description

Since the memcpy trick fix for vertical bars is only required when `C_FPU_X86` is false, don't compile in the extra arrays and associated logic when they aren't needed.

There were also a couple of places where I had missed setting the `use_regs_memcpy[]` array element to `false` when the corresponding`fpu.tags[]` element is set to `TAG_Empty`, specifically with the `FFREE` instruction, which so far I've only seen used by `PERF_DOS`.

# Manual testing

I tested Carmageddon, Sunflower, and MCPDIAG on:

- macOS arm64, normal and dynamic cores
- macos x86-64, normal and dynamic cores
- Windows MSYS2 x64-86, normal and dynamic core

If anyone can run through the Linux builds for normal and dynamic core, that would be appreciated.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by kcgen — APPROVED** [review]
Very nice cleanup, @kklobe !

**Comment by kcgen** [comment]
> If anyone can run through the Linux builds for normal and dynamic core, that would be appreciated.

Calling in @FeralChild64 and @weirddan455 for help! (my repo is currently in bisect land; thanks guys!)

**Comment by kcgen** [comment]
With a couple new fixes, we should probably get this backported to 0.81.0-rc2, I think?

**Comment by johnnovak** [comment]
> With a couple new fixes, we should probably get this backported to 0.81.0-rc2, I think?

I think so, yeah.

**Review by johnnovak — APPROVED** [review]
Looks good man, but I'm not close to this code so I'll trust you on it 😄

**Comment by FeralChild64** [comment]
Checked MCPDIAG, Quake, and GTA (both normal and 3dfx) - both dynamic and normal core, Linux build. No problems found.

Non-3dfx GTA on normal core is too slow to be playable, unfortunately.

**Pull request merged**
