### PR TITLE
Update dependencies and macOS CI runner version

### PR DESCRIPTION
**Pull request by kcgen**
Updates all existing meson wraps. 
Leverages meson wraps and vcpkg when they can provide dependencies.
Bumps the macOS CI running from 10.15 (EOL in Oct/Nov) to 11.0, because GitHub is "browning out" the older VMs causing job failures.

### CODE REVIEW

**Comment by kcgen** [comment]
With newer dependencies on all systems (plus macOS's CI being updated), any help in confirmating the code still builds and runs on your system(s).

**Comment by Grounded0** [comment]
Waiting for @Burrito78 to report in results from his macOS 10.15 system.

**Comment by FeralChild64** [comment]
> With newer dependencies on all systems (plus macOS's CI being updated), any help in confirmating the code still builds and runs and/or CI binaries still runs on your system(s), would be appreciated!

Gentoo Linux, AMD64, GCC 11.3.0 - builds, seems to work correctly. But there are some compilation warnings:

```
[128/246] Compiling C++ object src/hardware/libhardware.a.p/adlib_gold.cpp.o
In file included from ../subprojects/iir1-1.9.3/Iir.h:53,
                 from ../src/hardware/adlib_gold.h:26,
                 from ../src/hardware/adlib_gold.cpp:21:
../subprojects/iir1-1.9.3/iir/RBJ.h: In constructor 'constexpr Iir::RBJ::RBJbase::RBJbase()':
../subprojects/iir1-1.9.3/iir/RBJ.h:66:26: warning: 'Iir::RBJ::RBJbase::state' should be initialized in the member initialization list [-Weffc++]
   66 |         struct DllExport RBJbase : Biquad
      |                          ^~~~~~~
In file included from ../src/hardware/adlib_gold.cpp:21:
../src/hardware/adlib_gold.h: At global scope:
../src/hardware/adlib_gold.h:114:57: note: synthesized method 'constexpr Iir::RBJ::RBJbase::RBJbase()' first required here
  114 |         std::array<Iir::RBJ::LowShelf, 2> lowshelf   = {};
      |                                                         ^
[171/246] Compiling C++ object src/hardware/libhardware.a.p/opl.cpp.o
In file included from ../subprojects/iir1-1.9.3/Iir.h:53,
                 from ../src/hardware/adlib_gold.h:26,
                 from ../src/hardware/opl.h:27,
                 from ../src/hardware/opl.cpp:19:
../subprojects/iir1-1.9.3/iir/RBJ.h: In constructor 'constexpr Iir::RBJ::RBJbase::RBJbase()':
../subprojects/iir1-1.9.3/iir/RBJ.h:66:26: warning: 'Iir::RBJ::RBJbase::state' should be initialized in the member initialization list [-Weffc++]
   66 |         struct DllExport RBJbase : Biquad
      |                          ^~~~~~~
In file included from ../src/hardware/opl.h:27,
                 from ../src/hardware/opl.cpp:19:
../src/hardware/adlib_gold.h: At global scope:
../src/hardware/adlib_gold.h:114:57: note: synthesized method 'constexpr Iir::RBJ::RBJbase::RBJbase()' first required here
  114 |         std::array<Iir::RBJ::LowShelf, 2> lowshelf   = {};
      |      
```

**Comment by kcgen** [comment]
> here are some compilation warnings

Thanks @FeralChild64 ; [PR'd this upstream](https://github.com/berndporr/iir1/pull/39). When the next iir1 release comes out, we can bump the Meson wrap and these warnings will be fixed up.

**Comment by Burrito78** [comment]
> Waiting for @Burrito78 to report in results from his macOS 10.15 system.

@kcgen I will test compatibility on 10.15 but can't do so before Aug. 15th as i'm out of office right now. You can merge if you want earlier and i will open a new issue if there are any problems.

**Comment by kcgen** [comment]
> You can merge if you want earlier and i will open a new issue if there are any problems.

With CI passing and builds also passing on @johnnovak , @FeralChild64 , and @brandonrobertz's systems, I think this is a reasonable approach.

**Comment by johnnovak** [comment]
Forgot to comment, but I tried it on Windows yesterday and it was fine in Visual Studio too.

**Pull request merged**
