### PR TITLE
Load keyboard and codepage files on-demand, and use uncompressed EGA18 codepage

### LINKED ISSUE #1880: Codepage doesn't switch back to 437 after using 858.
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

Mac OS

### If Other OS, please describe

_No response_

### Relevant hardware info

_No response_

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Codepage can be changed to 858 but not back to 437 afterwards (858 is an example).

### Steps to reproduce the behaviour.

-Change the active codepage using 'keyb gr' to 858. 
-See change in font in DOSBox info box (kerning of 'f' character, width of 'v' character).
-Try to change codepage back using 'keyb gr 437' or 'keyb us'.
-The codepage doesn't change back.

### Your configuration

```ini
default config
```

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
Fixes #1880 ; thanks for reporting this @FeralChild64 .

Can flip-flip between code pages, and it seems to work (can you check it, @Burrito78 ?):

Screenshot from 2022-08-24 18-56-23

I only know the basics though, so more help testing is appreciated!

### CODE REVIEW

**Review by FeralChild64 — COMMENTED** [review]
Why only EGA18.CPX got decompressed? Maybe it would make more sense to decompress all the files, for uniformity?

**Comment by Grounded0** [comment]
I agree better to decompress all font files for maximum robustness.

**Comment by kcgen** [comment]
The code has handled both compressed or uncompressed CP files. It looks for the magic UPX header, and if found, runs the self-extractor inside DOS.

EGA18's UPX executable COM header doesn't exit when run inside the core; maybe it's too small? I'm not sure. But extracting it avoids having to run the self extractor and instead the code just parses it's data. 

All the other files are twice as big, and have no problem having their COM headers run and self-extract (into memory). 

Currently the CPX files take up about 150 KB of binary space in the repo; but they swell to over 1MB when saved in expanded form. 

I think it's fine if just EGA18 is unpacked. The closer the other files are to upstream (freedoms), the better (easy to diff and check).

**Comment by kcgen** [comment]
@FeralChild64 , this works with `keyb br 3848`

**Review by Grounded0 — APPROVED** [review]
Looks like a nice cleanup of this 20 year old code.

**Review by Burrito78 — APPROVED** [review]

**Comment by Burrito78** [comment]
It does work for changing codepages now, see example below. But the behavior of the not toggling 'v' character in the DOSBox info box isn't changed.

Freshly started DOSBox, no codepage change. Notice narrow 'v' character:
Bildschirmfoto 2022-08-25 um 10 23 12

Entered 'keyb gr', CP 858 loaded, Entered several '€' (Euro symbol) characters, entered 'keyb us', CP 437 loaded.
Notice codepage did change according to changed '€' (Euro symbol) characters. 
But also notice how the 'v' character in the info box didn't change back.
Bildschirmfoto 2022-08-25 um 10 23 44

Maybe that's expected in this case but i wanted to mention it because it's strange behavior to me.

**Comment by Grounded0** [comment]
I wouldn't do any default codepage changes now. It's a piecemeal approach as Euro should be rolled back on them all. That can follow with later releases. Consistency matters:

https://en.wikipedia.org/wiki/Code_page#DOS_code_pages

**Comment by kcgen** [comment]
> I wouldn't do any default codepage changes now. It's a piecemeal approach as all Euro codepages should be rolled back at the same time for consistency. That can follow later. Search for euro:
> 
> https://en.wikipedia.org/wiki/Code_page#DOS_code_pages

In 0.78.1, the codepage number like 858 had to be provided explicitly: `keyb gr 850` or `keyb gr 858`

In the upcoming release, the Western Eurpean countries will default to 850: `keyb gr` because that's what mid-90s DOS did.

We're still backward compatibile for those providing an explicit codepage number (batch file, autoexec lines, and muscle memory). For example `keyb gr 850` or `keyb gr 858` will do exactly as requested.

**Comment by Burrito78** [comment]
I tested again using german versions of Norton Commander 3.0 and 4.0.
NC 3.0 needs CP 437 and NC 4.0 needs CP 850 to display line characters correctly. NC 5.5 adapts to available CP.

Switching between 437, 850 and 858 works as expected using the latest changes on this branch.

**Comment by kcgen** [comment]
Thanks for the thorough testing, @Burrito78 !

**Comment by Grounded0** [comment]
808 – Russian with euro (same without euro: 866)
848 – Ukrainian with euro (same without euro: 1125)
849 – Belorussian with euro (same without euro: 1131)
867 – Hebrew + euro (same without euro: 862)
872 – Cyrillic with euro (same without euro: 855)
1161 – Thai with Low Tone Marks & Ancient Chars with euro (same without euro: 874)
1370 – Traditional Chinese MIX (Big5 encoding) (1114 + 947 + euro) (same without euro: 950)

Work is in progress on these if they are supported by us.

**Comment by kcgen** [comment]
Got em', thanks @Grounded0.

- [x] Russian without euro: 866
- [x] Ukrainian without euro: 1125
- [x] Belorussian without euro: 1131
- [x] Hebrew without euro: 862
- [x] Cyrillic without euro: 855

> Thai with Low Tone Marks & Ancient Chars with euro (same without euro: 874)
> Traditional Chinese MIX (Big5 encoding) (1114 + 947 + euro) (same without euro: 950)

The Thai and Chinese languages aren't supported, because the EGA codepage files don't contain these character set.

**Comment by kcgen** [comment]
Thanks for the feedback and testing, @Burrito78 and @Grounded0.
Let's go ahead with this.

**Pull request merged**
