### PR TITLE
Add a placeholder program (#1258)

### PR DESCRIPTION
**Pull request by kcgen**
Can be used as many times as needed to inform users that a 3rd party program should be acquired and installed.

Any number of programs can be added in `dos_programs`:

``` c++
PROGRAMS_MakeFile("FAVORITE.COM", PLACEHOLDER_ProgramStart);
PROGRAMS_MakeFile("OTHRPROG.COM", PLACEHOLDER_ProgramStart);
PROGRAMS_MakeFile("POPULAR.COM", PLACEHOLDER_ProgramStart);
```

And so on.

Calling the placeholder will pause execution and produce a helpful message both on the DOS console and in the log output:

Fixes (#1258)

Thank you @Burrito78 for this suggestion!

### CODE REVIEW

**Review by Burrito78 — APPROVED** [review]
I'm not sure about the wording. It seems overly complicated somehow. :)
Maybe slim it down a little bit and be more precise (exact name of Wiki page etc.).

I straight up failed to install debug.com from FreeDOS, so i will open a ticket discussing this issue on its own.

**Comment by Burrito78** [comment]
The DEBUG stub doesn't work with the Tie Fighter (german) installer as expected.

The text output of DEBUG is redirected to fix.out instead.

image

**Comment by Burrito78** [comment]
image

**Comment by kcgen** [comment]
Until we can bundle add-on tools, please make sure the PATH to your own `DEBUG` program comes _**before**_ other paths (like shown in the screenshot example).

**Pull request closed without merging**
