### PR TITLE
Update Italian (it-it) translation

### PR DESCRIPTION
**Pull request by Kappa971**

### CODE REVIEW

**Comment by kcgen** [comment]
Thank you, @Kappa971 !

**Comment by kcgen** [comment]
@Kappa971 , I've added write access for you, so you can branch and push directly to and from the main repo. Thank you!

**Comment by Kappa971** [comment]
Nice, thanks 🙂

**Comment by kcgen** [comment]
>  I must have accidentally deleted your comment

:laughing: at least we know write-access works!

**Pull request merged**
