### PR TITLE
[DRAFT] Python script for character limit to help translators out!

### PR DESCRIPTION
**Pull request by ThomasEricB**
This will be a useful tool for translators, as it calculates the character limit of each line, excluding the characters present between squared brackets. If a line exceeds the character limit in the input file, it will print the corresponding line and its number on the terminal, plus it will create a line break on the newly generated output file.

Marking this as a Draft PR, because I want to hear from y'all what we should do to improve the shell script, and also, because this is missing the following two key features that I feel that are important to be implemented before merging into main:

- [x] ~~Support for the different boxes spawned into PROGRAM_INTRO_MOUNT_WINDOWS (73 character box), PROGRAM_INTRO_MOUNT_OTHER (70 character box) and SHELL_STARTUP_BEGIN, SHELL_STARTUP_CGA, SHELL_STARTUP_CGA_MONO, SHELL_STARTUP_HERC, SHELL_STARTUP_DEBUG, SHELL_STARTUP_END (68 character box).~~ (Too hard for my skill level, made it so that it ignores these lines.)
- [ ] Current behavior creates the line break at the character limit. I want to change that so that line break doesn't split words, and instead it creates the split before the infringing word.
- [ ] Make the Script automatically look inside the "utf-8" folder (Suggestion from @Kappa971)
- [x] ~~Convert the .sh to .bat (Suggestion from @Kappa971)~~ **(No longer needed, as I'm making a python script)**
- [x] Make `outputfile` optional (Suggestion from @Kappa971)
- [x] Remove sections containing `:TITLEBAR_` from the check (Suggestion from @Kappa971)
- [x] Consider the viability to swap to Python instead of using .bat and .sh (Suggestion from @dreamer)
- [x] Swap to Python (Suggestion from @dreamer)
- [ ] Grab improvements from regex at line 245 in ansi_code_markup.cpp (Suggestion from @shermp)

mintty_w4Wc9HZhGt

### CODE REVIEW

**Comment by FeralChild64** [comment]
Is the script able to properly calculate length of the line like this?

`	        "  [color=green]tree[reset] [color=cyan][DIRECTORY][reset] [/a] \\[/b] [/f] [/p] [/da] [/df] [/dh] [/o[color=white]ORDER[reset]]\n"`

Simply skipping the content of square brackets is not enough.

----

BTW. Such a tool can indeed be useful, if it works right :)

**Comment by Kappa971** [comment]
A script that checks for files not exceeding the 80-column limit seems like a great idea to me.
I have some considerations:
1. the script should automatically look in the "utf-8" folder
2. a native Windows script (a batch file) would also be useful (like `encode.sh` and `encode.bat`)
3. `outputfile` shouldn't be specified by the user
4. I think the following should be removed from the check:
```
:TITLEBAR_CYCLES_MS
cicli/ms
.
:TITLEBAR_HINT_PAUSED
(PAUSA)
.
:TITLEBAR_HINT_NOMOUSE
modalità senza mouse
.
:TITLEBAR_HINT_CAPTURED_HOTKEY
mouse catturato, %s+F10 per rilasciarlo
.
:TITLEBAR_HINT_CAPTURED_HOTKEY_MIDDLE
mouse catturato, %s+F10 o pulsante centrale del mouse per rilasciarlo
.
:TITLEBAR_HINT_RELEASED_HOTKEY
per catturare il mouse premere %s+F10
.
:TITLEBAR_HINT_RELEASED_HOTKEY_MIDDLE
per catturare il mouse premere %s+F10 o pulsante centrale del mouse
.
:TITLEBAR_HINT_RELEASED_HOTKEY_ANY_BUTTON
per catturare il mouse premere %s+F10 o fare clic su qualsiasi pulsante
.
:TITLEBAR_HINT_SEAMLESS_HOTKEY
mouse senza soluzione di continuità, %s+F10 per catturarlo
.
:TITLEBAR_HINT_SEAMLESS_HOTKEY_MIDDLE
mouse senza soluzione di continuità, %s+F10 o pulsante centrale del mouse per catturarlo
.
```

**Comment by dreamer** [comment]
I know the first implementation is ready, but the script is still considerably small (<100 LOC), so I'll say it:

Consider rewriting it in Python, seriously. It will be much easier than processing files in bash and relying on Perl for regexes... And probably you'll avoid a ton of bugs and the result will be much easier to extend with other features in the future.

For example how to work with regexes and processing file, look at python scripts named `count-<something>.py` in `scripts/`, e.g. [count-warnings.py](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/count-warnings.py) - they do a similar thing, but your script will be much, much simpler (you don't need to process streams, just files, and you don't need any argument handling in the first iteration) :)

**Comment by ThomasEricB** [comment]
> ` " [color=green]tree[reset] [color=cyan][DIRECTORY][reset] [/a] \\[/b] [/f] [/p] [/da] [/df] [/dh] [/o[color=white]ORDER[reset]]\n"`
In this phrase, it would only see the `tree` in the beginning and `\n` at the end, I believe.

**Comment by ThomasEricB** [comment]
@Kappa971 said:

> A script that checks for files not exceeding the 80-column limit seems like a great idea to me. I have some considerations:
> 
>     1. the script should automatically look in the "utf-8" folder
> 
>     2. a native Windows script (a batch file) would also be useful (like `[encode.sh](http://encode.sh)` and `encode.bat`)
> 
>     3. `outputfile` shouldn't be specified by the user
> 
>     4. I think the following should be removed from the check:
> 

And @dreamer said:

> Consider rewriting it in Python, seriously. It will be much easier than processing files in bash and relying on Perl for regexes... And probably you'll avoid a ton of bugs and the result will be much easier to extend with other features in the future.

Added both your considerations above, as I find them valid. However, in the specific case of @dreamer 's suggestion I'm not promising to swap to python just yet, only to study the viability to me to do so.

**Comment by shermp** [comment]
@ThomasEricB have a look at the regex in `src/misc/ansi_code_markup.cpp`. That's the regex used to find the markup tags. If you replicate it in Python, you should be able to match what Dosbox is doing.

**Comment by kcgen** [comment]
Suggest its default mode of operation take in one filename and report long lines if found. 
If the file is good (no long lines), then it should exit with a successful  return code (0) to the shell. 

If the file is bad (one or more long lines found), then it should return a non-zero return code (1) to the shell.

**Comment by kcgen** [comment]
Script needs to pass pylint checks to get it back in a reviewable state:

```
contrib/resources/translations/line_length_utility.py:8:0: C0301: Line too long (134/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:9:0: C0301: Line too long (116/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:11:0: C0301: Line too long (160/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:20:0: C0301: Line too long (111/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:21:0: C0301: Line too long (107/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:23:0: C0301: Line too long (130/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:70:0: C0301: Line too long (110/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:74:30: C0303: Trailing whitespace (trailing-whitespace)
contrib/resources/translations/line_length_utility.py:77:30: C0303: Trailing whitespace (trailing-whitespace)
contrib/resources/translations/line_length_utility.py:91:0: C0301: Line too long (138/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:97:0: C0304: Final newline missing (missing-final-newline)
contrib/resources/translations/line_length_utility.py:1:0: C0114: Missing module docstring (missing-module-docstring)
contrib/resources/translations/line_length_utility.py:6:0: C0116: Missing function or method docstring (missing-function-docstring)
contrib/resources/translations/line_length_utility.py:11:0: C0116: Missing function or method docstring (missing-function-docstring)
contrib/resources/translations/line_length_utility.py:11:0: R0913: Too many arguments (6/5) (too-many-arguments)
contrib/resources/translations/line_length_utility.py:11:17: W0621: Redefining name 'line' from outer scope (line 76) (redefined-outer-name)
contrib/resources/translations/line_length_utility.py:11:28: W0621: Redefining name 'max_line_length' from outer scope (line 40) (redefined-outer-name)
contrib/resources/translations/line_length_utility.py:11:50: W0621: Redefining name 'input_line_num' from outer scope (line 71) (redefined-outer-name)
contrib/resources/translations/line_length_utility.py:11:71: W0621: Redefining name 'output_line_num' from outer scope (line 72) (redefined-outer-name)
contrib/resources/translations/line_length_utility.py:11:93: W0621: Redefining name 'skip_line' from outer scope (line 73) (redefined-outer-name)
contrib/resources/translations/line_length_utility.py:11:118: W0621: Redefining name 'skip_reason' from outer scope (line 75) (redefined-outer-name)
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.BaseException' ?) instead.
contrib/resources/translations/line_length_utility.py:19:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
contrib/resources/translations/line_length_utility.py:34:0: C0103: Constant name "inputfile" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:37:8: C0103: Constant name "outputfile" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:40:16: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:45:12: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.Exception' ?) instead.
contrib/resources/translations/line_length_utility.py:49:12: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:55:4: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:58:4: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:64:4: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:71:8: C0103: Constant name "input_line_num" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:72:8: C0103: Constant name "output_line_num" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:73:8: C0103: Constant name "skip_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:74:8: C0103: Constant name "skip_next_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:75:8: C0103: Constant name "skip_reason" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:78:16: C0103: Constant name "skip_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:79:16: C0103: Constant name "skip_reason" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:80:16: C0103: Constant name "skip_next_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:82:16: C0103: Constant name "skip_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:83:16: C0103: Constant name "skip_reason" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:84:16: C0103: Constant name "skip_next_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:86:16: C0103: Constant name "skip_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:87:16: C0103: Constant name "skip_reason" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:89:16: C0103: Constant name "skip_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:90:16: C0103: Constant name "skip_reason" doesn't conform to UPPER_CASE naming style (invalid-name)
```

After that, ensure the regex is expanded and documented.

Those are the two major hurdles for this PR.

At that point, if the script is working correctly (and translators can use it reliably), you could propose it for merging (or address more comments).

**Review by kcgen — CHANGES_REQUESTED** [review]
Script needs to pass pylint checks to get it back in a reviewable state:

```
contrib/resources/translations/line_length_utility.py:8:0: C0301: Line too long (134/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:9:0: C0301: Line too long (116/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:11:0: C0301: Line too long (160/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:20:0: C0301: Line too long (111/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:21:0: C0301: Line too long (107/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:23:0: C0301: Line too long (130/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:70:0: C0301: Line too long (110/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:74:30: C0303: Trailing whitespace (trailing-whitespace)
contrib/resources/translations/line_length_utility.py:77:30: C0303: Trailing whitespace (trailing-whitespace)
contrib/resources/translations/line_length_utility.py:91:0: C0301: Line too long (138/100) (line-too-long)
contrib/resources/translations/line_length_utility.py:97:0: C0304: Final newline missing (missing-final-newline)
contrib/resources/translations/line_length_utility.py:1:0: C0114: Missing module docstring (missing-module-docstring)
contrib/resources/translations/line_length_utility.py:6:0: C0116: Missing function or method docstring (missing-function-docstring)
contrib/resources/translations/line_length_utility.py:11:0: C0116: Missing function or method docstring (missing-function-docstring)
contrib/resources/translations/line_length_utility.py:11:0: R0913: Too many arguments (6/5) (too-many-arguments)
contrib/resources/translations/line_length_utility.py:11:17: W0621: Redefining name 'line' from outer scope (line 76) (redefined-outer-name)
contrib/resources/translations/line_length_utility.py:11:28: W0621: Redefining name 'max_line_length' from outer scope (line 40) (redefined-outer-name)
contrib/resources/translations/line_length_utility.py:11:50: W0621: Redefining name 'input_line_num' from outer scope (line 71) (redefined-outer-name)
contrib/resources/translations/line_length_utility.py:11:71: W0621: Redefining name 'output_line_num' from outer scope (line 72) (redefined-outer-name)
contrib/resources/translations/line_length_utility.py:11:93: W0621: Redefining name 'skip_line' from outer scope (line 73) (redefined-outer-name)
contrib/resources/translations/line_length_utility.py:11:118: W0621: Redefining name 'skip_reason' from outer scope (line 75) (redefined-outer-name)
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.BaseException' ?) instead.
contrib/resources/translations/line_length_utility.py:19:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
contrib/resources/translations/line_length_utility.py:34:0: C0103: Constant name "inputfile" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:37:8: C0103: Constant name "outputfile" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:40:16: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:45:12: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
pylint: Command line or configuration file:1: UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.Exception' ?) instead.
contrib/resources/translations/line_length_utility.py:49:12: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:55:4: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:58:4: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:64:4: C0103: Constant name "max_line_length" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:71:8: C0103: Constant name "input_line_num" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:72:8: C0103: Constant name "output_line_num" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:73:8: C0103: Constant name "skip_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:74:8: C0103: Constant name "skip_next_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:75:8: C0103: Constant name "skip_reason" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:78:16: C0103: Constant name "skip_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:79:16: C0103: Constant name "skip_reason" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:80:16: C0103: Constant name "skip_next_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:82:16: C0103: Constant name "skip_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:83:16: C0103: Constant name "skip_reason" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:84:16: C0103: Constant name "skip_next_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:86:16: C0103: Constant name "skip_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:87:16: C0103: Constant name "skip_reason" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:89:16: C0103: Constant name "skip_line" doesn't conform to UPPER_CASE naming style (invalid-name)
contrib/resources/translations/line_length_utility.py:90:16: C0103: Constant name "skip_reason" doesn't conform to UPPER_CASE naming style (invalid-name)
```

After that, ensure the regex is expanded and documented.

Those are the two major hurdles for this PR.

At that point, if the script is working correctly (and translators can use it reliably), you could propose it for merging (or address more comments).

**Comment by ThomasEricB** [comment]
While, I haven't committed the newest updates to my .py script, I managed to make the script break at the beginning of each word instead of breaking it in half. Still needs a complete overhaul tho.

**Comment by kcgen** [comment]
@ThomasEricB , this PR has sat 3 weeks without movement. 

I'm going to back-burner it for now, just to get it off the active set. 

When the comments are addressed it can be re-opened (without any loss of content; just click 'Open'). 

Hopefully you can get to it when time permits!

**Pull request closed without merging**
