### PR TITLE
Re-create CurMode iterator after backing array has been changed

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

I think my #3374 PR was just bad after @johnnovak submitted 2 PRs fixing crashes caused by it.  I've reverted that and the previous workaround.

Rather than trying to pick a place (somewhat arbitrarily in `INT10_Init`) to initialize this thing, leave the global init  just re-create it when it gets invalidated.  This happens exactly once in the code in SVGA_S3 init.

The real problem here was the edge case when the iterator gets invalidated.  So just fix the edge case rather than trying to dive into this init mess so close to the 0.81 release.

## Related issues

#3374
#3386
#3387

# Manual testing

Tested with all machine types to confirm no more crashes.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
Thanks @weirddan455. I agree this is for the better and is the least invasive for now. I'm closing my second fix.

I think when we refactor the whole codebase to introduce proper modularisation and init order, that will be a better time to despaghettify all this global init stuff. Especially my last PR seemed a bit arbitrary too; it might be not necessary with better modularisation and init order.

**Comment by Grounded0** [comment]
This would be the final PR before 0.81.0 next week.

**Comment by johnnovak** [comment]
> This would be the final backported PR before 0.81.0 next week.

If we don't find something else, yeah.

**Review by johnnovak — APPROVED** [review]
We got there in the end @weirddan455 😅 I appreciate your persistence 👍🏻

**Pull request merged**
