### PR TITLE
Kill the transliteration/romanization rules with fire 🔥🔥🔥

### PR DESCRIPTION
**Pull request by FeralChild64**
# Description

When introducing our Unicode engine, I have added several rules to transliterate Cyrillic/Greek/etc. strings to Latin-only ones.  This romanization scheme was very limited - it could only replace a non-Latin letter with a single Latin character, and the rules were the same for all the languages (while in reality rules for i..e. Russian and Bulgarian should be different) - but it served the purpose well, to keep the translated messages readable no matter what code page was set.

This rule set is now obsolete, as we fall back to English messages if the code page does not suite the non-Latin translation.

This PR removes almost all the transliteration rules (with very few exceptions, like the digits or homograph punctuation marks), as they are probably useless now.

I have kept the code point definitions in `ASCII.TXT` file on purpose:
- this is an indication that the code point is fully supported by the engine (we have decomposition rules, upper/lower case conversion rules, etc.)
- in the future I intend to extend this file with additional data, needed to generate DOS collation tables

# Release notes

(no need to advertise this - there is already a release notes proposal for using English as a fallback)

# Manual testing

1. Copy some Greek text to your host OS clipboard, like this piece of [Wikipedia](https://el.wikipedia.org/wiki/DOSBox):
> Το DOSBox είναι εξομοιωτής που εξομοιώνει έναν συμβατό υπολογιστή IBM PC εκτελώντας ένα λειτουργικό σύστημα DOS, μαζί με συμβατές κάρτες γραφικών και ήχου, που σημαίνει πως κανονικά προγράμματα DOS, συμπεριλαμβανόμενων και παιχνιδιών υπολογιστή, παρέχουν ένα περιβάλλον στο οποίο μπορούν να τρέξουν σωστά, παρόλο που οι σύγχρονοι υπολογιστές έχουν σταματήσει να υποστηρίζουν αυτό το περιβάλλον. Το DOSBox είναι ελεύθερο λογισμικό, γραμμένο κυρίως στη γλώσσα C++ και διανέμεται υπό την Γενική Άδεια Δημόσιας Χρήσης GNU.

2. Inside DOSBox, execute command `keyb us`, afterwards execute command `clip` - it should paste the text, replacing most Greek letters with question marks:
Screenshot-US

3. Inside DOSBox, execute command `keyb el`, afterwards execute command `clip` - it should paste the text, keeping the Greek letters:
Screenshot-EL

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [x] Linux (trivial)

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by FeralChild64** [comment]
Sorry, but I don't want to do this.

The current transliteration is crap. For text editing we would need a proper transliteration code, based on the official romanization rules for various languages. Too much effort. Plus, we are improving a gaming-oriented emulator - not a fancy text processor.

**Comment by johnnovak** [comment]
A worthy new episode of the prestigious "kill with fire" series 😎🤘🏻🔥🔥🔥 You even met the criteria of upsetting at least one regular user... 🤣 Boom! 💥 

Jokes aside, I'm with @FeralChild64 on this, @Torinde. Let's not loose focus of the project goals.

I assume the ability to store extended ASCII characters as UTF-8 symbols looking the same way for CP437 on the host filesystem is not related to this? That would be just a simple 127-element mapping table. See here, I'm intending to implement this to do simple high-ASCII code to UTF8 and back mapping:

- https://github.com/dosbox-staging/dosbox-staging/issues/2619

Just for CP437, nothing else! But that will get all demoscene prods with weird filenames and a few games that put high-ASCII chars in filenames running natively, without the need for real DOS in a HDD image.

**Review by johnnovak — APPROVED** [review]
You're the expert, so whatever 😄

**Comment by FeralChild64** [comment]
> I assume the ability to store extended ASCII characters as UTF-8 symbols looking the same way for CP437 on the host filesystem is not related to this? That would be just a simple 127-element mapping table.

No, it's not.

> See here, I'm intending to implement this to do simple high-ASCII code to UTF8 and back mapping

Sure, just call:

```C++
auto output = utf8_to_dos(const std::string& str,
                          DosStringConvertMode::NoSpecialCharacters, 
                          UnicodeFallback::EmptyString,
                          437);
                          
auto output = dos_to_utf8(const std::string& str,
                          DosStringConvertMode::NoSpecialCharacters,
                          437);
```

**Comment by johnnovak** [comment]
> > I assume the ability to store extended ASCII characters as UTF-8 symbols looking the same way for CP437 on the host filesystem is not related to this? That would be just a simple 127-element mapping table.
> 
> No, it's not.
> 
> > See here, I'm intending to implement this to do simple high-ASCII code to UTF8 and back mapping
> 
> Sure, just call:
> 
> ```c++
> auto output = utf8_to_dos(const std::string& str,
>                           DosStringConvertMode::NoSpecialCharacters, 
>                           UnicodeFallback::EmptyString,
>                           437);
>                           
> auto output = dos_to_utf8(const std::string& str,
>                           DosStringConvertMode::NoSpecialCharacters,
>                           437);
> ```

Cheers, thanks for the tip.

**Pull request merged**
