### PR TITLE
Add a detailed help page for the imgmount command

### PR DESCRIPTION
**Pull request by kcgen**
(PR authored on behalf of @MasterO2)  
This PR improves imgmount's (currently vacant) help output with a thorough list of arguments, their descriptions, and corresponding examples. 

Background discussion is here: https://github.com/dosbox-staging/dosbox-staging/issues/567

As suggested: 

> (@dreamer) please create a pull request so we could discuss specific lines.

This PR will let us review and refine.  Thanks for the suggestion and commit content @MasterO2.

### CODE REVIEW

**Comment by kcgen** [comment]
Let for me to do:
1. Determine when we should use the one-line 'short help', if at all. 
2. Assign authorship to @MasterO2
3. Consider color coding arguments and examples by the three mount types (floppy, cdrom, and hdd image).

**Comment by MasterO2** [comment]
@kcgen Can I assume imgmount will also require both a ? and -help switch, as you're doing for autotype?

**Comment by kcgen** [comment]
@MasterO2 , yes. Currently I've set it to print your full message when no arguments are provided, or when '?' is provide, or when '-help' is provided.

**Comment by kcgen** [comment]
(latest revision)

**Comment by nemo93** [comment]
Looks amazing, so much clearer. I'd like to add something into the Wiki as well (if that makes sense). Do you have a text version of the screenshot above? Alternatively I'll look into the code.

Does it mean `-t iso` will be deprecated in favour of `-t cdrom`?

**Comment by kcgen** [comment]
Thanks @nemo93! 

Yes, the only text version is from the commit, but its quite populated with conreol characters: https://github.com/dosbox-staging/dosbox-staging/issues/567

Regarding iso vs cdrom, I believe `-t cdrom` works as a universal replacement for iso, correct?

 If we want me to list `iso` too, then I will include it in the first whale mount line.

**Comment by dreamer** [comment]
> Does it mean `-t iso` will be deprecated in favour of `-t cdrom`?

*Not judging one way or another, only explaining:*

Pedantically speaking, **`-t iso`** is the correct value, `-t cdrom` is the incorrect one: [link](https://github.com/dosbox-staging/dosbox-staging/blob/master/src/dos/dos_programs.cpp#L1208) (based on this line and certain error messages).

`-t cdrom` is a parameter to **`mount`** command, used to work around some bugs when mounting physical CD (I think it's some bug related to labels, but I don't know).

`imgmount` supports 3 `-fs` values: `-fs none` (as mentioned in help), but also `-fs fat`, and… `-fs iso`.

So it's really confusing - `floppy, hdd, cdrom` ("incorrect") makes more sense than `floppy, hdd, iso` ("correct"), particularly not when working with `.cue` files. Also, people were probably confused about `iso` being value for both `-t` and `-fs`.

Upstream decided to make `imgmount -t cdrom` an alias for `imgmount -t iso`.

**Comment by nemo93** [comment]
Thanks both. As usual crystal-clear and complete details! I fully agree that `-t floppy, hdd, cdrom` makes total sense. I'll stick to that from now on.

**Comment by MasterO2** [comment]
@kcgen Regarding ```Mounts a CDROM, floppy, or HDD image to a drive letter in DOS```

Why is the text color gray?  Shouldn't it be white or yellow there?

**Comment by kcgen** [comment]
We could sacrifice one of the example lines, if we wanted to discuss the `-fs` flags too; but I find them functionally redundant and they merely add confusion when mingled with -t.

The only unique value -fs has is in when settjng up a new blank HDD images which is when you need '-fs none'.

**Comment by kcgen** [comment]
That first description line started gray.. but after running the command many times it felt too prominent and a bit distracting.. so the de-emphasis still lets it exist, but without feeling too cluttered at the top and also delineates it relative to the Usage line. 

If we had more vertical space, I would prefer a blank separating line, which would visually have a similar effect of adding blackness and a nice delineation.. but alas.. we can't afford a single blank line here.

**Comment by kcgen** [comment]
Also wanted to say that the darker gray description also "gets out of the way", because the majority of invocations will be users who only need a syntax refresher and perhaps a working example, typically because they forgot it.  So we prioritize this common usecase visually.

**Review by dreamer — CHANGES_REQUESTED** [review]
Overall this turned out great - my requests below are really pedantic :)

I really liked the subtle usage of grey colour, but unfortunately - it will need to go :( Consider following screenshots:

hercules - Screenshot from 2020-08-31 18-16-37
cga_mono - Screenshot from 2020-08-31 18-18-12

In all others modes the text was clearly readable - only in `ega` we have distortion, but that's #228 

Also, 4 colours is ok and it serves a purpose (colour is a cue for which parameter is which in examples). With 5 colours I think we might be introducing visual clutter.

(BTW, I noticed we have a bug in `ls` command when used in hercules and cga_mono - but that should be a quick fix - not related to this PR of course).

We can't really get rid of `Usage:` word (it will cause the description to merge with the text and the usage lines will look bad justified), so I suggest following changes:

Suggestion 1:

- Make the first line normal colour, add an empty line before (`Usage:`)
- Remove one other line: I suggest removing note about `-fs none`

Suggestion 2 (much, much, more work):

We could forget about the requirement of 1 screen (but let's make it 2 screens max), and invoke `pause` command (same as in `dir/p`) - this would allow us to fit more text (which is actually needed for this help message). But the implementation would be non trivial, and then we would throw it away when we'll implement `less` as pager anyway…

I prefer **Suggestion 1** myself, but would love to hear other's opinions.

Other requests:

- Change 2 spaces into 1 space between `DRIVE` and `CDROM-SET` (and in subsequent lines)
- Add all valid values to `-fs` description in Usage (`-fs fat` is important)
- Make the first line in imperative mood and end it with a dot. I suggest:

> Mount a CD-ROM, floppy, or disk image to a drive letter.

(disk instead of HDD because it's human description; it also reads better thant "CD-ROM, FDD, or HDD image"; removed in DOS, because I think it's implied)

*One might wonder why I am so pedantic about this - after this PR I think we'll have a great template to reuse for programs on Z: drive, and perhaps also a template to use for shell command instead of adhering to DOS-like formatting.*

**Comment by dreamer** [comment]
Oh, and I'm not sure we can mount multiple `-t hdd` images, as in 3rd usage line? This could be good candidate for removal as well.

**Comment by MasterO2** [comment]
@dreamer @kcgen  I have one small change:  

```imgmount e cd/quake1.cue -t cdrom```

The e should be changed to a **d**, because DOS games that use CD Audio  look for the first CD Drive, which is usually D.

**Comment by kcgen** [comment]
>Consider following screenshots (using hercules and cga_mono):

Great catch @dreamer!

I went with **Suggestion 1** as we all preferred it.

Other requests are in.

> The e should be changed to a d, because DOS games that use CD Audio look for the first CD Drive, which is usually D.

Great catch!

> Oh, and I'm not sure we can mount multiple -t hdd images, as in 3rd usage line? This could be good candidate for removal as well (instead of a note).

Yup, multiple hard disk images can be mounted:



Let's take another critical look; here's what we've got:



@MasterO2, thanks for taking the initiative to take the plunge on GitHub make this happen with your first pull request :100:

**Review by dreamer — APPROVED** [review]
Looks great :) Thank you, @kcgen @MasterO2 !

**Pull request merged**
