### PR TITLE
Remove Fedora Linux related build instructions

### PR DESCRIPTION
**Pull request by johnnovak**
# Description

As per @oturpe's suggestion (see [here](https://github.com/dosbox-staging/dosbox-staging/pull/3692#issuecomment-2127918370
)), we're removing the Fedora Linux related contribs scripts as they're outdated and no one actively keeps them up-to-date.

I'm also removing all Fedora-related build info from the website in separate commits; let me know if you think these should stay. @FeralChild64 @weirddan455 @Grounded0 I can restore it if you think it's still needed.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by weirddan455** [comment]
I don't think we should be removing Fedora build instructions.  We might get someone who wants to contribute on Fedora and wants to build from source.  This is different than Fedora _packaging._  I have no problem with removing the `contrib/fedora` files.

On the website, I think we should leave the dependency instructions as well.  A user might be on Fedora 39 which is still maintained for another 6 months or so and wants to install v0.81.1.  Fedora 39 still packages v0.80.1 in the repos.  You could put a note near that section that Fedora is in the official repos if we want to promote that.  We do mention it further down on the page but it's not the first thing the user will see.

**Comment by Grounded0** [comment]
People should be pointed out to official packages as a priority.

**Comment by johnnovak** [comment]
> I don't think we should be removing Fedora build instructions. We might get a Fedora user who wants to contribute and needs to to build from source to do so. This is different than Fedora _packaging._ I have no problem with removing the `contrib/fedora` files.
> 
> On the website, I think we should leave the dependency instructions as well. A user might be on Fedora 39 which is still maintained for another 6 months or so and wants to install v0.81.1. Fedora 39 still packages v0.80.1 in the repos. 

Good points @weirddan455, yeah I wasn't sure. I was thinking Fedora is some niche distro no one uses these days. This makes sense, I'll keep the build instructions as you suggested.

> You could put a note near that section that Staging is in the official repos of Fedora if we want to promote that. We do mention it further down on the page but it's not the first thing the user will see.

Yeah, I agree, I will come up with something.

**Comment by weirddan455** [comment]
>  I was thinking Fedora is some niche distro no one uses these days.

It's hard to find accurate usage statistics for distro usage but Fedora is one of the big ones.  It's probably 2nd to Ubuntu based distros if I had to guess.

**Comment by johnnovak** [comment]
Updated. Leaving the Linux page as-is as I think we should point people to our tested binary releases. We have no control over how the distro maintainers repackage our stuff; those are "secondary" artifacts and might contains bugs and all sorts of weirdnesses (e.g., mismatching SDL2 lib versions).

**Comment by weirddan455** [comment]
Mismatching SDL2?  If anything, our binary release would be more prone to that as that's a dynamically linked dependency.  Distributions will compile with the same SDL2 version that their users will actually be using.

Changing build flags is more of a concern here (see #3686 although that bug only affects PPC which we don't even ship a binary release for).

**Comment by johnnovak** [comment]
> Mismatching SDL2? If anything, our binary release would be more prone to that as that's a dynamically linked dependency. Distributions will compile with the same SDL2 version that their users will actually be using.
> 
> Changing build flags is more of a concern here (see #3686 although that bug only affects PPC which we don't even ship a binary release for).

Yeah, I take it back. I always forget we're not shipping our own SDL2 lib on Linux. I just can't get over that "random library version" delivery model, apparently 😆

**Review by weirddan455 — APPROVED** [review]
In any case, removing `contrib/fedora` is fine as it's unmaintained and the Fedora downstream isn't using it.

**Pull request merged**
