### PR TITLE
Fixed errors preventing ww/voodoo-3dfx-2 to build in VS

### PR DESCRIPTION
**Pull request by ThomasEricB**
This is my first pull request, I don't know what I'm doing, help @kcgen @Wengier

### CODE REVIEW

**Comment by ThomasEricB** [comment]
One of the two errors in Virtual Studio: devenv_IXdxUoEEHL

What it looks like after your apply these fixes: 
devenv_v9MaGpE4SJ

**Comment by kcgen** [comment]
Looks good, @ThomasEricB !

One small suggestion: can you slightly re-word the two commits messages to use the command voice (or the imperative mood)? 

See: https://cbea.ms/git-commit/#imperative

**Comment by ThomasEricB** [comment]
> One small suggestion: can you slightly re-word the two commits messages to use the command voice (or the imperative mood)?

Sure but... I don't know how to edit the commit messages!

**Comment by kcgen** [comment]
Looks like some tips here: https://stackoverflow.com/questions/64660410/changing-content-from-an-unpushed-git-commit-in-visual-studio

(although it's an old question) worth trying, but shout if it's not doable (worst case, I will merge it anyway, because this isn't going to `main`).

**Comment by ThomasEricB** [comment]
@kcgen Is this fine?
GitExtensions_F7cFAfVUMI

**Comment by kcgen** [comment]
Perfect :+1: !

**Comment by ThomasEricB** [comment]
I'll redo this pull with the correct sentences

**Pull request closed without merging**
