### PR TITLE
Fix `pause_when_inactive` mouse behavior for macOS and Linux

### PR DESCRIPTION
**Pull request by FeralChild64**
Fixes https://github.com/dosbox-staging/dosbox-staging/issues/2255

First commit is the actual fix, second is a minor cleanup (function/variable naming harmonization).

### CODE REVIEW

**Comment by kcgen** [comment]
Looks great @FeralChild64 , and I really like the naming harmonization - now very can directly mentally match the concepts between source files :+1: 

Added a commit to `main` to print the log on setup failure, when you have a chance to rebase.

**Comment by kcgen** [comment]
The log revealed the issue:

```
2023-01-31T19:53:34.1755880Z Initialized empty Git repository in /home/runner/work/dosbox-staging/dosbox-staging/subprojects/gvdb/.git/
2023-01-31T19:53:34.9622053Z fatal: unable to access 'https://gitlab.gnome.org/GNOME/gvdb.git/': The requested URL returned error: 503
```

Literally every time we've had dependency fetch failures, it's because Gnome's gitlab server is failing and the guy who maintains it needs to reboot it. 

(reflect on using GitHub: It's sure nice having this stress off our shoulders!)

**Comment by FeralChild64** [comment]
@kcgen There is still some dependency error:

 ```
 WARNING: Variable '-libpcre2_8' in the subproject 'subprojects/pcre2-10.40' is not found
Dependency libpcre2-8 from subproject subprojects/pcre2-10.40 found: NO
Dependency libpcre2-8 from subproject subprojects/pcre2-10.40 found: YES 10.40
Using subprojects/glib-2.74.1/subprojects/gvdb.wrap
Message: You can disable this dependency with: -Duse_slirp=false

subprojects/glib-2.74.1/meson.build:2089:0: ERROR: Git command failed: ['/usr/bin/git', 'fetch', '--depth', '1', 'origin', '0854af0fdb6d527a8d1999835ac2c5059976c210']
Error: Process completed with exit code 1.

 ```

**Comment by kcgen** [comment]
> @kcgen There is still some dependency error:
> 
> ```
> WARNING: Variable '-libpcre2_8' in the subproject 'subprojects/pcre2-10.40' is not found
> Dependency libpcre2-8 from subproject subprojects/pcre2-10.40 found: NO
> Dependency libpcre2-8 from subproject subprojects/pcre2-10.40 found: YES 10.40
> Using subprojects/glib-2.74.1/subprojects/gvdb.wrap
> Message: You can disable this dependency with: -Duse_slirp=false
> 
> subprojects/glib-2.74.1/meson.build:2089:0: ERROR: Git command failed: ['/usr/bin/git', 'fetch', '--depth', '1', 'origin', '0854af0fdb6d527a8d1999835ac2c5059976c210']
> Error: Process completed with exit code 1.
> ```

Yes, it's stemming from gvdb. 

In the failing Linux release workflow, click the gear icon and select 'view raw log', which is the full stdout and stderr. 

Search it for 'gvdb', and you'll see git getting a 503 failure fetching it from gitlab's repo. 

Then if you go back to the last successful `main` Linux release workflow, gvdb is fetched and compiled without issue. 

I'll go poke around in gnome's gitlab and see if I can learn more.

**Comment by kcgen** [comment]
https://gitlab.gnome.org/GNOME/gvdb

I can't even connect to the web front 😢

**Comment by FeralChild64** [comment]
@kcgen, @johnnovak: I have found a regression: with seamless mouse enabled, the internal mouse cursor does not move any more if DOSBox window loses focus. This is not a desirable behavior, I need to fix it.

**Comment by kcgen** [comment]
Gnome's server is back online.

Added a ticket here: https://gitlab.gnome.org/GNOME/glib/-/issues/2906

**Comment by FeralChild64** [comment]
@kcgen, @johnnovak: Regression fixed - ready for review again.

**Review by kcgen — APPROVED** [review]
All looks good @FeralChild64!

(I've pushed an update for the unrelated pylint warning coming from the code analysis workflow.)

**Pull request merged**
