### PR TITLE
Add support for FreeBSD and OpenBSD

### PR DESCRIPTION
**Pull request by kcgen**
Also re-enables the PPC dynrec cores that were unfortunately disabled in the 2021 commit 515161087c8e66b57f8c73ec289ae4b3a4f4548a as a result of some refactoring in SVN r4424, which broke the PPC backends. It's nice to finally revisit PPC land now that I have working hardware again.

2023-03-13-140628_1280x854_scrot

Using the normal core, I tested the following:
 - lots of video modes (4-bit, 8-bit, 15-bit, 16-bit, 24-bit, 32-bit)
 - all the CDDA codecs (Wav, Vorbis, FLAC, Opus, MP3, and Sony Wave64)
 - MIDI - both Fluidsynth and MT-32
 - audio devices: PC Speaker, Tandy, PS/1, CMS, SB*, Adlib, Adlib Gold 
 - image mounts (CDROM and floppy)

They're all (still) working on big-endian, so that's good!

As for the PPC dynamic core, it now builds - but the OpenBSD kernel blocks it at runtime with an ABORT. OpenBSD has strict `mmap` requirements regarding R+W+X permission flags, despite Staging complying w/ W^X memory tagging using `mprotect`, so  I'll have to switch to Linux or FreeBSD to get further.

### CODE REVIEW

**Comment by kcgen** [comment]
Only 122 MB of RAM consumed for the entire OS plus DOSBox Staging :exploding_head: :sunglasses:

**Comment by johnnovak** [comment]
Nice to see that BSD support gets some well-deserved love! I much more prefer the BSD-philosophy than the Linux one (well-designed vs "organically grown", to be diplomatic about it 😅), so this is a welcome improvement! 🎉

**Comment by johnnovak** [comment]
Does this thing even support OpenGL? If not, it will be a nice testbed for the software renderer backend of the OSD/UI stuff.

**Comment by kcgen** [comment]
Installing Gentoo Linux on the Powerbook G4; hopefully will have better luck being able to run and test the PPC dynrec core.

**Review by johnnovak — APPROVED** [review]
Looking good @kcgen , nice build instructions. Out of interest, does the Linux binary run in the Linux compatibility mode of BSD? (I've just heard there is such a thing 😄 )

**Comment by kcgen** [comment]
> Looking good @kcgen , nice build instructions. Out of interest, does the Linux binary run in the Linux compatibility mode of BSD? (I've just heard there is such a thing smile )

Oh yes! I forgot the BSDs' have a Linux compatibility mode - so didn't try running it.  But I would imagine it's libc's MMAP wrapper would hit the same blocks in the OpenBSD kernel (and similar to prevent acceess to the memory). 

If I ever revisit OpenBSD, will have to remember to try. Thanks, @johnnovak !

**Comment by kcgen** [comment]
I'm not hitting any regressions testing other dyn rec cores: x86, armV7, and aarch64, so will go ahead with the merge.

**Pull request merged**
