### PR TITLE
Use std::atomic for CaptureState enum

### LINKED ISSUE #3927: Thread sanitiser reports data races when capturing audio and video
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

`main`

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

**Data race during audio capture:**

```
WARNING: ThreadSanitizer: data race (pid=1811804)
  Read of size 4 at 0x0000013b84cc by thread T17 (mutexes: write M0):
    #0 CAPTURE_IsCapturingAudio() ../../src/capture/capture.cpp:70
    #1 mix_samples ../../src/hardware/mixer.cpp:2450
    #2 mixer_thread_loop ../../src/hardware/mixer.cpp:2562
    #3 void std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) /usr/include/c++/13/bits/invoke.h:61
    #4 std::__invoke_result<void (*)()>::type std::__invoke<void (*)()>(void (*&&)()) /usr/include/c++/13/bits/invoke.h:96
    #5 void std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/13/bits/std_thread.h:292
    #6 std::thread::_Invoker<std::tuple<void (*)()> >::operator()() /usr/include/c++/13/bits/std_thread.h:299
    #7 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run() /usr/include/c++/13/bits/std_thread.h:244
    #8 <null> <null> (libstdc++.so.6+0xeabb3)

  Previous write of size 4 at 0x0000013b84cc by main thread:
    #0 CAPTURE_AddAudioData(unsigned int, unsigned int, short const*) ../../src/capture/capture.cpp:432
    #1 capture_callback ../../src/hardware/mixer.cpp:2510
    #2 TIMER_AddTick() ../../src/hardware/pic.cpp:629
    #3 Normal_Loop ../../src/dosbox.cpp:192
    #4 DOSBOX_RunMachine() ../../src/dosbox.cpp:450
    #5 CALLBACK_RunRealInt(unsigned char) ../../src/cpu/callback.cpp:117
    #6 device_CON::Read(unsigned char*, unsigned short*) ../../src/dos/dev_con.h:89
    #7 DOS_Device::Read(unsigned char*, unsigned short*) ../../src/dos/dos_devices.cpp:329
    #8 DOS_ReadFile(unsigned short, unsigned char*, unsigned short*, bool) ../../src/dos/dos_files.cpp:665
    #9 DOS_Shell::ReadCommand[abi:cxx11]() ../../src/shell/shell_misc.cpp:140
    #10 DOS_Shell::InputCommand(char*) ../../src/shell/shell_misc.cpp:79
    #11 DOS_Shell::Run() ../../src/shell/shell.cpp:492
    #12 SHELL_Init() ../../src/shell/shell.cpp:1430
    #13 Config::StartUp() ../../src/misc/setup.cpp:1669
    #14 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:5035
    #15 main ../../src/main.cpp:30

  Location is global 'capture' of size 88 at 0x0000013b84a0

  Mutex M0 (0x00000193f630) created at:
    #0 pthread_mutex_lock ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1341 (libtsan.so.2+0x5910c)
    #1 __gthread_mutex_lock /usr/include/aarch64-linux-gnu/c++/13/bits/gthr-default.h:749
    #2 __gthread_recursive_mutex_lock /usr/include/aarch64-linux-gnu/c++/13/bits/gthr-default.h:811
    #3 std::recursive_mutex::lock() /usr/include/c++/13/mutex:120
    #4 MIXER_LockMixerThread() ../../src/hardware/mixer.cpp:311
    #5 MIXER_Init(Section*) ../../src/hardware/mixer.cpp:2805
    #6 Section::ExecuteInit(bool) ../../src/misc/setup.cpp:1358
    #7 Config::Init() const ../../src/misc/setup.cpp:1330
    #8 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:5021
    #9 main ../../src/main.cpp:30

  Thread T17 'dosbox:mixer' (tid=1811822, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1022 (libtsan.so.2+0x5a267)
    #1 std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) <null> (libstdc++.so.6+0xeac88)
    #2 Section::ExecuteInit(bool) ../../src/misc/setup.cpp:1358
    #3 Config::Init() const ../../src/misc/setup.cpp:1330
    #4 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:5021
    #5 main ../../src/main.cpp:30

SUMMARY: ThreadSanitizer: data race ../../src/capture/capture.cpp:70 in CAPTURE_IsCapturingAudio()
```

**Data race during video capture:**

```
WARNING: ThreadSanitizer: data race (pid=1811924)
  Write of size 4 at 0x0000013b84d4 by main thread:
    #0 CAPTURE_StartVideoCapture() ../../src/capture/capture.cpp:359
    #1 handle_capture_video_event ../../src/capture/capture.cpp:557
    #2 CHandlerEvent::Active(bool) ../../src/gui/sdl_mapper.cpp:1853
    #3 CTriggeredEvent::ActivateEvent(bool, bool) ../../src/gui/sdl_mapper.cpp:158
    #4 CBind::ActivateBind(long, bool, bool) ../../src/gui/sdl_mapper.cpp:272
    #5 CBindGroup::ActivateBindList(std::__debug::list<CBind*, std::allocator<CBind*> >*, long, bool) ../../src/gui/sdl_mapper.cpp:1430
    #6 CKeyBindGroup::CheckEvent(SDL_Event*) ../../src/gui/sdl_mapper.cpp:448
    #7 MAPPER_CheckEvent(SDL_Event*) ../../src/gui/sdl_mapper.cpp:2781
    #8 GFX_Events() ../../src/gui/sdlmain.cpp:4165
    #9 Normal_Loop ../../src/dosbox.cpp:188
    #10 DOSBOX_RunMachine() ../../src/dosbox.cpp:450
    #11 CALLBACK_RunRealInt(unsigned char) ../../src/cpu/callback.cpp:117
    #12 device_CON::Read(unsigned char*, unsigned short*) ../../src/dos/dev_con.h:89
    #13 DOS_Device::Read(unsigned char*, unsigned short*) ../../src/dos/dos_devices.cpp:329
    #14 DOS_ReadFile(unsigned short, unsigned char*, unsigned short*, bool) ../../src/dos/dos_files.cpp:665
    #15 DOS_Shell::ReadCommand[abi:cxx11]() ../../src/shell/shell_misc.cpp:140
    #16 DOS_Shell::InputCommand(char*) ../../src/shell/shell_misc.cpp:79
    #17 DOS_Shell::Run() ../../src/shell/shell.cpp:492
    #18 SHELL_Init() ../../src/shell/shell.cpp:1430
    #19 Config::StartUp() ../../src/misc/setup.cpp:1669
    #20 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:5035
    #21 main ../../src/main.cpp:30

  Previous read of size 4 at 0x0000013b84d4 by thread T17 (mutexes: write M0):
    #0 CAPTURE_IsCapturingVideo() ../../src/capture/capture.cpp:96
    #1 mix_samples ../../src/hardware/mixer.cpp:2450
    #2 mixer_thread_loop ../../src/hardware/mixer.cpp:2562
    #3 void std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) /usr/include/c++/13/bits/invoke.h:61
    #4 std::__invoke_result<void (*)()>::type std::__invoke<void (*)()>(void (*&&)()) /usr/include/c++/13/bits/invoke.h:96
    #5 void std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/13/bits/std_thread.h:292
    #6 std::thread::_Invoker<std::tuple<void (*)()> >::operator()() /usr/include/c++/13/bits/std_thread.h:299
    #7 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run() /usr/include/c++/13/bits/std_thread.h:244
    #8 <null> <null> (libstdc++.so.6+0xeabb3)

  Location is global 'capture' of size 88 at 0x0000013b84a0

  Mutex M0 (0x00000193f630) created at:
    #0 pthread_mutex_lock ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1341 (libtsan.so.2+0x5910c)
    #1 __gthread_mutex_lock /usr/include/aarch64-linux-gnu/c++/13/bits/gthr-default.h:749
    #2 __gthread_recursive_mutex_lock /usr/include/aarch64-linux-gnu/c++/13/bits/gthr-default.h:811
    #3 std::recursive_mutex::lock() /usr/include/c++/13/mutex:120
    #4 MIXER_LockMixerThread() ../../src/hardware/mixer.cpp:311
    #5 MIXER_Init(Section*) ../../src/hardware/mixer.cpp:2805
    #6 Section::ExecuteInit(bool) ../../src/misc/setup.cpp:1358
    #7 Config::Init() const ../../src/misc/setup.cpp:1330
    #8 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:5021
    #9 main ../../src/main.cpp:30

  Thread T17 'dosbox:mixer' (tid=1811944, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1022 (libtsan.so.2+0x5a267)
    #1 std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) <null> (libstdc++.so.6+0xeac88)
    #2 Section::ExecuteInit(bool) ../../src/misc/setup.cpp:1358
    #3 Config::Init() const ../../src/misc/setup.cpp:1330
    #4 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:5021
    #5 main ../../src/main.cpp:30

SUMMARY: ThreadSanitizer: data race ../../src/capture/capture.cpp:359 in CAPTURE_StartVideoCapture()

```

### Steps to reproduce the behaviour

1. Compile a TSAN build using GCC as followed:

```shell
meson setup --wipe \
 -Dbuildtype=debugoptimized \
 -Db_sanitize=thread \
 -Dwarning_level=0 \
 -Db_ndebug=true \
 -Duse_zlib_ng=false \
 -Ddefault_library=static \
 -Db_lundef=false \
 -Dunit_tests=disabled \
 -Duse_fluidsynth=false \
 -Duse_sdl2_net=false \
 -Duse_mt32emu=false \
 -Duse_slirp=false \
 -Duse_alsa=false \
 -Duse_opengl=false \
 --wrap-mode=forcefallback \
 build/tsan

export TSAN_OPTIONS=second_deadlock_stack=1 atexit_sleep_ms=200 flush_memory_ms=2000 history_size=7"

export LIBGL_ALWAYS_SOFTWARE=1
```

2. Launch the TSAN build

3. Press **Ctrl+F6** (for audio recording) or **Ctrl+F7** (for video recording)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

More TSAN warning fixes.  I had to write a `reset()` function since `= {}` would not compile as `std::atomic` has the assignment operator deleted.

## Related issues

Fixes #3927

# Release notes

Nothing user facing.  Just more TSAN fixes.

# Manual testing

Ran a TSAN build and captured audio and video in Doom.  No more warning are shown.  I actually never got a warning on my system for audio but I did for video.  The video warning had a different callstack but it was these same enum variables that were the problem.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by interloper98** [comment]
Tap Ctrl+F6 or Ctrl+F7 back to back (start-stop-start-stop, doesn't have to be too fast), I get overlapping calls to SDL's timer routines (SDL_AddTimer, SDL_TimerThread), which is coming from Staging's titlebar recording animation being started and stopped.

(Just thinking out loud -- maybe the titlebar [rec] could be PIC-timed, too? -- or maybe just needs some thread-safety added to the state variables, too)

**Comment by weirddan455** [comment]
>  This should report overlapping calls to SDL's timer routines (`SDL_AddTimer`, `SDL_TimerThread`) coming from Staging's titlebar recording animation functions.

I'm confused.  What's the actual problem you're getting?  More TSAN warnings?  If so I cannot reproduce this.

`SDL_AddTimer` gets called inside `GFX_RefreshTitle` which is only called by the main thread.  I don't know what `SDL_TimerThread` is.  We don't call that directly (grep comes up empty).  If there's any threading issues with those function calls, it must be inside SDL code.

**Comment by interloper98** [comment]
Yes, TSAN warnings. `maybe_start_animation()` (step `#4 in the backtrace) is our titlebar function, and that's using some SDL timers which ultimately triggers the TSAN issue. 

But yeah - I'm compiling SDL itself with TSAN too using the wrap (repro instructions here: https://github.com/dosbox-staging/dosbox-staging/issues/3927, but maybe this is moot if we're 100% legal on our side!).

```
WARNING: ThreadSanitizer: data race (pid=21888)
  Read of size 4 at 0x000001963320 by main thread (mutexes: write M0):
    #0 SDL_AtomicTryLock_REAL ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:75
    #1 SDL_AtomicLock_REAL ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:176
    #2 SDL_AddTimer_REAL ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:283
    #3 SDL_AddTimer ../../subprojects/SDL2-2.30.6/src/dynapi/SDL_dynapi_procs.h:519
    #4 maybe_start_animation ../../src/gui/titlebar.cpp:154
    #5 GFX_RefreshTitle() ../../src/gui/titlebar.cpp:387
    #6 GFX_NotifyVideoCaptureStatus(bool) ../../src/gui/titlebar.cpp:418
    #7 CAPTURE_StartVideoCapture() ../../src/capture/capture.cpp:370
    #8 handle_capture_video_event ../../src/capture/capture.cpp:567
    #9 CHandlerEvent::Active(bool) ../../src/gui/sdl_mapper.cpp:1855
    #10 CTriggeredEvent::ActivateEvent(bool, bool) ../../src/gui/sdl_mapper.cpp:158
    #11 CBind::ActivateBind(long, bool, bool) ../../src/gui/sdl_mapper.cpp:274
    #12 CBindGroup::ActivateBindList(std::__debug::list<CBind*, std::allocator<CBind*> >*, long, bool) ../../src/gui/sdl_mapper.cpp:1432
    #13 CKeyBindGroup::CheckEvent(SDL_Event*) ../../src/gui/sdl_mapper.cpp:450
    #14 MAPPER_CheckEvent(SDL_Event*) ../../src/gui/sdl_mapper.cpp:2783
    #15 GFX_Events() ../../src/gui/sdlmain.cpp:4165
    #16 Normal_Loop ../../src/dosbox.cpp:188
    #17 DOSBOX_RunMachine() ../../src/dosbox.cpp:450
    #18 CALLBACK_RunRealInt(unsigned char) ../../src/cpu/callback.cpp:117
    #19 device_CON::Read(unsigned char*, unsigned short*) ../../src/dos/dev_con.h:89
    #20 DOS_Device::Read(unsigned char*, unsigned short*) ../../src/dos/dos_devices.cpp:329
    #21 DOS_ReadFile(unsigned short, unsigned char*, unsigned short*, bool) ../../src/dos/dos_files.cpp:665
    #22 DOS_Shell::ReadCommand[abi:cxx11]() ../../src/shell/shell_misc.cpp:140
    #23 DOS_Shell::InputCommand(char*) ../../src/shell/shell_misc.cpp:79
    #24 DOS_Shell::Run() ../../src/shell/shell.cpp:492
    #25 SHELL_Init() ../../src/shell/shell.cpp:1430
    #26 Config::StartUp() ../../src/misc/setup.cpp:1669
    #27 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:5046
    #28 main ../../src/main.cpp:30

  Previous atomic write of size 4 at 0x000001963320 by thread T1:
    #0 SDL_AtomicUnlock_REAL ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:190
    #1 SDL_TimerThread ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:130
    #2 SDL_RunThread ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:333
    #3 RunThread ../../subprojects/SDL2-2.30.6/src/thread/pthread/SDL_systhread.c:76

  Location is global 'SDL_timer_data' of size 208 at 0x000001963280

  Mutex M0 (0x720c00000c00) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1315 (libtsan.so.2+0x58bfd) (BuildId: 64c1e8de04b11a7d960abd7e45f94f3b277b7779)
    #1 SDL_CreateMutex_REAL ../../subprojects/SDL2-2.30.6/src/thread/pthread/SDL_sysmutex.c:58
    #2 SDL_AtomicTryLock_REAL ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:72
    #3 SDL_AtomicLock_REAL ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:176
    #4 SDL_GetErrBuf ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:275
    #5 SDL_ClearError_REAL ../../subprojects/SDL2-2.30.6/src/SDL_error.c:72
    #6 SDL_InitSubSystem_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:222
    #7 SDL_InitSubSystem_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:217
    #8 SDL_Init_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:394
    #9 SDL_Init ../../subprojects/SDL2-2.30.6/src/dynapi/SDL_dynapi_procs.h:88
    #10 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:4921
    #11 main ../../src/main.cpp:30

  Thread T1 'SDLTimer' (tid=21890, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1022 (libtsan.so.2+0x5a267) (BuildId: 64c1e8de04b11a7d960abd7e45f94f3b277b7779)
    #1 SDL_SYS_CreateThread ../../subprojects/SDL2-2.30.6/src/thread/pthread/SDL_systhread.c:116
    #2 SDL_CreateThreadWithStackSize_REAL ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:401
    #3 SDL_CreateThreadInternal ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:452
    #4 SDL_TimerInit ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:227
    #5 SDL_InitSubSystem_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:256
    #6 SDL_InitSubSystem_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:217
    #7 SDL_Init_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:394
    #8 SDL_Init ../../subprojects/SDL2-2.30.6/src/dynapi/SDL_dynapi_procs.h:88
    #9 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:4921
    #10 main ../../src/main.cpp:30

SUMMARY: ThreadSanitizer: data race ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:75 in SDL_AtomicTryLock_REAL
==================
==================
WARNING: ThreadSanitizer: data race (pid=21888)
  Read of size 8 at 0x000001963330 by main thread:
    #0 SDL_AddTimer_REAL ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:329
    #1 SDL_AddTimer ../../subprojects/SDL2-2.30.6/src/dynapi/SDL_dynapi_procs.h:519
    #2 maybe_start_animation ../../src/gui/titlebar.cpp:154
    #3 GFX_RefreshTitle() ../../src/gui/titlebar.cpp:387
    #4 GFX_NotifyVideoCaptureStatus(bool) ../../src/gui/titlebar.cpp:418
    #5 CAPTURE_StartVideoCapture() ../../src/capture/capture.cpp:370
    #6 handle_capture_video_event ../../src/capture/capture.cpp:567
    #7 CHandlerEvent::Active(bool) ../../src/gui/sdl_mapper.cpp:1855
    #8 CTriggeredEvent::ActivateEvent(bool, bool) ../../src/gui/sdl_mapper.cpp:158
    #9 CBind::ActivateBind(long, bool, bool) ../../src/gui/sdl_mapper.cpp:274
    #10 CBindGroup::ActivateBindList(std::__debug::list<CBind*, std::allocator<CBind*> >*, long, bool) ../../src/gui/sdl_mapper.cpp:1432
    #11 CKeyBindGroup::CheckEvent(SDL_Event*) ../../src/gui/sdl_mapper.cpp:450
    #12 MAPPER_CheckEvent(SDL_Event*) ../../src/gui/sdl_mapper.cpp:2783
    #13 GFX_Events() ../../src/gui/sdlmain.cpp:4165
    #14 Normal_Loop ../../src/dosbox.cpp:188
    #15 DOSBOX_RunMachine() ../../src/dosbox.cpp:450
    #16 CALLBACK_RunRealInt(unsigned char) ../../src/cpu/callback.cpp:117
    #17 device_CON::Read(unsigned char*, unsigned short*) ../../src/dos/dev_con.h:89
    #18 DOS_Device::Read(unsigned char*, unsigned short*) ../../src/dos/dos_devices.cpp:329
    #19 DOS_ReadFile(unsigned short, unsigned char*, unsigned short*, bool) ../../src/dos/dos_files.cpp:665
    #20 DOS_Shell::ReadCommand[abi:cxx11]() ../../src/shell/shell_misc.cpp:140
    #21 DOS_Shell::InputCommand(char*) ../../src/shell/shell_misc.cpp:79
    #22 DOS_Shell::Run() ../../src/shell/shell.cpp:492
    #23 SHELL_Init() ../../src/shell/shell.cpp:1430
    #24 Config::StartUp() ../../src/misc/setup.cpp:1669
    #25 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:5046
    #26 main ../../src/main.cpp:30

  Previous write of size 8 at 0x000001963330 by thread T1:
    #0 SDL_TimerThread ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:122
    #1 SDL_RunThread ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:333
    #2 RunThread ../../subprojects/SDL2-2.30.6/src/thread/pthread/SDL_systhread.c:76

  Location is global 'SDL_timer_data' of size 208 at 0x000001963280

  Thread T1 'SDLTimer' (tid=21890, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1022 (libtsan.so.2+0x5a267) (BuildId: 64c1e8de04b11a7d960abd7e45f94f3b277b7779)
    #1 SDL_SYS_CreateThread ../../subprojects/SDL2-2.30.6/src/thread/pthread/SDL_systhread.c:116
    #2 SDL_CreateThreadWithStackSize_REAL ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:401
    #3 SDL_CreateThreadInternal ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:452
    #4 SDL_TimerInit ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:227
    #5 SDL_InitSubSystem_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:256
    #6 SDL_InitSubSystem_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:217
    #7 SDL_Init_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:394
    #8 SDL_Init ../../subprojects/SDL2-2.30.6/src/dynapi/SDL_dynapi_procs.h:88
    #9 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:4921
    #10 main ../../src/main.cpp:30

SUMMARY: ThreadSanitizer: data race ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:329 in SDL_AddTimer_REAL
```

**Comment by interloper98** [comment]
The titlebar code uses SDL_AddTimer to run a callback in the future (similar to DOBox's own PIC approach); but the docs https://wiki.libsdl.org/SDL2/SDL_AddTimer mention the callback is run on a separate thread.

I guess SDL itself is having some iternal TSAN issues in its timer-callback handling?

**Comment by weirddan455** [comment]
Ok, that warning is coming entirely from SDL code as I suspected.  It also should not be a regression from the work I did on the mixer as I didn't touch anything in that control flow that updates the titlebar.

Looks like they have their own custom spinlock implementation.  If you want to go down the rabbit hole of debugging this fun file filled with inline assembly be my guest :smile: 

https://github.com/libsdl-org/SDL/blob/release-2.30.x/src/atomic/SDL_spinlock.c

**Comment by interloper98** [comment]
> Looks like they have their own custom spinlock implementation. If you want to go down the rabbit hole of debugging this fun file filled with inline assembly be my guest 😄
> 
> https://github.com/libsdl-org/SDL/blob/release-2.30.x/src/atomic/SDL_spinlock.c

Thanks for the gentle nudge :rabbit: :rabbit2: :hole: I've fallen in :laughing: !

**Review by interloper98 — APPROVED** [review]
This fixes it!

**Review by johnnovak — APPROVED** [review]
Nice one @weirddan455

**Pull request merged**
