### PR TITLE
Fix for debugger BP command

### PR DESCRIPTION
**Pull request by dreamer**
Addresses #960 
Some context in here: https://www.vogons.org/viewtopic.php?f=32&t=37854

### CODE REVIEW

**Comment by LowLevelMahn** [comment]
currently compiling :)

can you add something like #define BP_COMPARE_LINEAR_ADDR to the patch - default on - so it can be disabled?

**Comment by dreamer** [comment]
@LowLevelMahn No, I am not fond of parametrizing behaviour using defines - it's always a baggage. If someone wants different behaviour configurable during build time… then simply `git revert <commit>` is the way to go.

Do you want me to merge this change in the form as it is currently (I believe it works ok?).

**Comment by LowLevelMahn** [comment]
> @LowLevelMahn No, I am not fond of parametrizing behaviour using defines - it's always a baggage. If someone wants different behaviour configurable during build time… then simply `git revert <commit>` is the way to go.

all the debugger feature are very special - some of them only work with core=normal - but that gets never checked - its the dark corner of dosbox :)

even the debugger itself is activated using define + another define for heavy-debug feautures (that killing too much cpu time when part of the compilation)
 
> Do you want me to merge this change in the form as it is currently (I believe it works ok?).

it works but i still would add a local #if 1 around the new code with "ripsaw8080" comment

**Comment by kcgen** [comment]
Can we try to disposition this?

Given the greater overhead in enabling this debugging feature, I think that qualifies it as a 'heavy' feature.

@LowLevelMahn , if we turned this on for heavy debugging (and off for 'normal' debugging), would that be an acceptable compromise?

**Comment by kcgen** [comment]
Merging, given the content and @dreamer's comment here: https://github.com/dosbox-staging/dosbox-staging/issues/960#issuecomment-809904289 and @LowLevelMahn also reporting positive results in 

If it does turn out that CPU overhead is too much, we can retain the original "loose" search results for non-heavy and use "exact" criteria for heavy builds:

``` c++
if ((bp->GetType() == BKPNT_PHYSICAL) && bp->IsActive() &&
#if defined(C_HEAVY_DEBUG) # ex
    (bp->GetLocation() == GetAddress(seg, off)) {
#else
    (bp->GetSegment()==seg) && (bp->GetOffset()==off)) {
#endif
```

But as processors get faster and faster, hopefully (potential) the need for this similarly disappears.

**Pull request merged**
