### PR TITLE
Update Italian (it-it) translation

### PR DESCRIPTION
**Pull request by Kappa971**
# Description

_Describe a summary of your changes clearly and concisely, including motivation and context._
_Breaking changes need extra explanation on backward compatibility considerations._

_Feel free to include additional details, but please respect the reviewer's time and keep it brief._

I changed the sentence like this:
```
:SHELL_CMD_MIXER_HELP_LONG
  - I comandi di riverbero e coro applicano, rispettivamente, anche i valori
    predefiniti di riverbero e coro nei canali in cui tali effetti non sono
    ancora abilitati.
```

```
:SHELL_CMD_MIXER_HELP_LONG
  - The reverb and chorus commands also apply the default reverb and chorus
    values, respectively, to channels where these effects are not yet enabled.
```

## Related issues

_Related issues can be listed here (remove the section if not applicable.)_

# Manual testing

_Please describe the tests that you ran to verify your changes._

_Provide clear instructions so the reviewers can reproduce and verify your results._

_Include relevant details for your test configuration, operating system, etc._

_Ideally, you would also test your changes with a [sanitizer build](https://github.com/dosbox-staging/dosbox-staging/blob/main/BUILD.md#make-a-sanitizer-build) and confirm no issues were found._

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [ ] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [ ] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by kcgen** [comment]
I think you can eliminate that wording @Kappa971.

The current behavior is intuitive and doesn't need extra clarification, which I think harms and confuses the subject. 

For example, we could create similar contrived wording for volumes and code-pages:

- The master volume level is also applied, respectively, to channels which have not yet been enabled.

- The configured code-page is also applied, respectively, to characters that have not yet been printed to the screen.

**Comment by Kappa971** [comment]
> I think you can eliminate that wording @Kappa971.
> 
> The current behavior is intuitive and doesn't need extra clarification.
> 
> For example, we could create similar contrived wording for volumes and code-pages:
> 
>     * The master volume level is also applied, respectively, to channels which have not yet been enabled.
> 
>     * The configured code-page is also applied, respectively, to characters that have not yet been printed to the screen.

I have already removed the other 3 sentences, this one is still present in the English version, it is a fourth sentence that has not been removed so I thought it should be kept.

I will remove it from the translation tomorrow.

**Comment by kcgen** [comment]
> this one is still present in the English version

Oh, thanks @Kappa971.

**Review by kcgen — APPROVED** [review]
Looks good, @Kappa971.
Squashing the three commits and will merge.

**Pull request merged**
