### PR TITLE
Use NOMINMAX to prevent std::min failing in MSVC

### PR DESCRIPTION
**Pull request by dreamer**
I restarted this job about 10 times today. MSYS2 keeps failing over and over again.

### CODE REVIEW

**Comment by kcgen** [comment]
I haven't looked into the MSVC issues in detail, but see the more recent VS change here:

commit e9637575   2 days ago (master) Adjust VS solution filters

(related?)

**Comment by dreamer** [comment]
> I haven't looked into the MSVC issues in detail, but see the more recent VS change here:
> 
> commit [e963757](https://github.com/dosbox-staging/dosbox-staging/commit/e96375754eab436315d0990650e4509aba872114) 2 days ago (master) Adjust VS solution filters
> 
> Edit: _I can't see how this would would cause it to not find `SDL2/SDL.h`, likewise and that PR passed all tests - so I think it's unrelated._

MSYS2 is failing. MSVC is fine.

**Comment by dreamer** [comment]
Merging this in - this should take away a compilation problem on MSVC in serial port cleanup (rebase please). As for MSYS2… I am thinking about removing these jobs because they are not helping.

**Comment by kcgen** [comment]
> As for MSYS2… I am thinking about removing these jobs because they are not helping.

Yeah; with Ubuntu available more natively under Windows, MSYS/Cygwin is likely to keep losing traction. Plus, I opened that issue for GitHub to add Clang and GCC/G++ to their Windows VMs (which they did), so in theory it should be pretty straight forward to use; just need to put the time in to figure it out.

**Pull request merged**
