### PR TITLE
Improve batch file to convert GOG cp437 config files to UTF-8

### PR DESCRIPTION
**Pull request by Kappa971**
# Description

_Describe a summary of your changes clearly and concisely, including motivation and context._
_Breaking changes need extra explanation on backward compatibility considerations._

_Feel free to include additional details, but please respect the reviewer's time and keep it brief._

More "advanced" version of this: https://github.com/dosbox-staging/dosbox-staging/pull/3031
It probably could be written better but that's the best I can do, sorry.
If you want to test it, I share the complete package: [conf437-utf8.zip](https://github.com/dosbox-staging/dosbox-staging/files/13064874/conf437-utf8.zip)

There is also a simpler alternative version: https://github.com/dosbox-staging/dosbox-staging/pull/3031#issuecomment-1773873351

If you don't like it, you can close the PR.

# Manual testing

### Without recursive (no `/R`):

- [x] convert single CP437 conf in given directory
- [x] convert multiple CP437 confs in given directory
- [x] convert UTF-8 conf in given directory (it should skip it)
- [x] convert multiple UTF-8 confs in given directory (it should skip them)
- [x] convert mixed CP437 confs with some UTF-8 confs in given directory (it should skip the UTF-8s but convert the CP437s)

### With recursion (`/R`):

Same as above test, but with confs inside nested directories under the given path:

- [x] convert single CP437 conf inside nested directory
- [x] convert multiple CP437 confs spread in nested directories
- [x] convert UTF-8 conf inside nested directory (it should skip it)
- [x] convert multiple UTF-8 confs inside nested directories (it should skip them)
- [x] convert mixed CP437 confs with some UTF-8 confs inside nested directories (it should skip the UTF-8s but convert the CP437s)

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by kcgen** [comment]
> It probably could be written better but that's the best I can do, sorry.

As long as the script:
1. Adds value for general users (and GOG users are a big group!),
2. Is clearly described and tested (does what it says it does)
3. Doesn't cause harm

Then that's sufficient for inclusion in the community contribution area.

No need to apologize; this is open-source, so taking the initiative to move the bar forward in an area is all that's needed.  If someone else has a better implemention, then they're free to add/improve it.

I've edited the PR text body and listed some test cases.

Can you setup those scenarios and run them?

Then simply click the check-box to "check" them when you've confirmed.

**Comment by Kappa971** [comment]
> - [ ] convert single CP437 conf in given directory

The batch file can convert a single `dosbox*.conf` file (both with and without **/R**) but only if there is only one file in that folder.
Currently you can't specify a single file, the batch file will convert those starting with `dosbox` with `.conf` extension and that are not UTF-8 (assuming that the source file is cp437).

**Comment by Kappa971** [comment]
If @OpenRift412 could give me some feedback, it would be helpful.

**Comment by OpenRift412** [comment]
What does this version do differently than the previous one?

**Comment by Kappa971** [comment]
> What does this version do differently than the previous one?

Now it has two search methods to convert conf files, and you don't have to copy the config files to the batch program folder:
1. Normal search. You give it a game directory (e.g. D:\DOS_GAMES\DOOM) and the batch will convert all files starting with "dosbox" with a ".conf" extension (but only those that are not UTF-8);
2. Recursive search. It does the same thing, but in this case you can give it the root directory (e.g. D:\DOS_GAMES) and it will convert the conf files of all GOG games contained in that directory.

I've tested it and it works but if you could give me some feedback, it would be helpful (maybe I missed something).

**Comment by kcgen** [comment]
With all those test cases confirmed, we're safe to merged.

Then @OpenRift412 will be able to test it in the latest dev build.

**Review by kcgen — APPROVED** [review]

**Comment by OpenRift412** [comment]
> > What does this version do differently than the previous one?
> 
> Now it has two search methods to convert conf files, and you don't have to copy the config files to the batch program folder:
> 
> 1. Normal search. You give it a game directory (e.g. D:\DOS_GAMES\DOOM) and the batch will convert all files starting with "dosbox" with a ".conf" extension (but only those that are not UTF-8);
> 2. Recursive search. It does the same thing, but in this case you can give it the root directory (e.g. D:\DOS_GAMES) and it will convert the conf files of all GOG games contained in that directory.
> 
> I've tested it and it works but if you could give me some feedback, it would be helpful (maybe I missed something).

I tested it and it seems to work alright. Don't think you missed anything. I'll let you know if I run into any more problems.

**Pull request merged**
