### PR TITLE
Bound and pin dependency versions

### PR DESCRIPTION
**Pull request by kcgen**
## VCPKG

vckpg, as a git repo, offers all prior versions, so  we can pin our dependencies down to current version, and continue to march the manifest forward as the versions evolve. 

To help us with this, this PR adds a python script that takes in our dependency list, parses the latest versions from vcpkg, and generates an up-to-date manifest.

This script is run in the Windows MSVC CI workflow and provides us a diff if the manifest is outdated (along with exactly what we need to change). 

## Linux, Homebrew, MSYS2

Pinning these versions to an exact version is not possible for two reasons:

1) Breakage on distros: different Linux repositories have different versions of libraries at any given time. Distros only support the current bug-fixed, latest-security patched version.

2) Breakage when bisecting: Linux repositories are responsible for library security and therefore do not allow applications to specify installation of prior (known-vulnerable) versions of libraries. If a package will only compile with SDL 2.0.5 but the distro's current patched version of SDL is 2.0.18, then the package is simply removed from the repo.

Fortunately we can still benefit by constraining dependencies to less than their next major version because Linux packages generally adhere to API compatibility within the same minor version per the  SemVer specification (either formally or informally).

For example: as of this commit, we are confident DOSBox Staging will compile with any SDL 2.x releases, even those in the future.

However, let's say it's now the year 2029 and most Linux systems are running SDL 5.x. If someone then needs to bisect back to this commit, the '< 3' bounding will cause Meson to (try) to find the most recent 2.x available (if possible) - and will not allow SDL 5.x.

---

Suggest reviewing commit-by-commit.

### CODE REVIEW

**Comment by kcgen** [comment]
Going to merge this and get it out of the queue.

It's zero risk, because the pinned versions match the current/latest versions we're already using.

The only code is helper stand-alone python script to parse VCPKG JSON records; so also no-impact to the executable.

**Comment by johnnovak** [comment]
That's a very informative summary of the Linux situation @kcgen. I wasn't thinking of the security implications of keeping older, known-to-be-compromised libraries in the repos, but it makes sense to remove them, in the grand scheme of things (even if it breaks bisecting).

**Comment by kcgen** [comment]
Edit: even though this is true:

> ... so we can pin our dependencies down to current version, and continue to march the manifest forward as the versions evolve.

Unfortunately the repos hosting the actual packages don't offer all prior versions for download, and they routinely roll off buggy/vulerable versions. So the above plan is just a pie in the sky: historic commits that pin versions won't actually be able the packages in the future (just as we hit with libtool).

**Comment by shermp** [comment]
In the vcpkg libtool case, it seems to be a consequence of vcpkg relying on msys2 *which specifically does not guarantee keeping older package versions for long*

**Comment by kcgen** [comment]
Msys2 was the first - but looks like it kept going down through more mirrors:

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://repo.msys2.org/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404 

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404 

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://mirrors.ustc.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12007 [D:\a\dosbox-staging\dosbox-staging\src\libs\zmbv\zmbv.vcxproj]

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12007 [D:\a\dosbox-staging\dosbox-staging\src\libs\zmbv\zmbv.vcxproj]

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12007 [D:\a\dosbox-staging\dosbox-staging\src\libs\zmbv\zmbv.vcxproj]

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12007 [D:\a\dosbox-staging\dosbox-staging\src\libs\zmbv\zmbv.vcxproj]

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://mirror.selfnet.de/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404

C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404 

(raw log: https://pipelines.actions.githubusercontent.com/serviceHosts/2382ad32-0206-4e79-b5d8-85555a77d3b8/_apis/pipelines/1/runs/88745/signedlogcontent/5?urlExpires=2023-01-13T23%3A20%3A17.2016645Z&urlSigningMethod=HMACV1&urlSignature=%2FnGb3vtT5zV25uCMUcb81Qg%2FJhs7c%2FFdgx5sWU2vxKM%3D)

**Comment by shermp** [comment]
Notice they are all msys2 packages. I imagine the mirrors just keep their packages in sync with the master list.

**Comment by kcgen** [comment]
Oh yes! - great catch.

**Pull request merged**
