### PR TITLE
Implement DOS mouse driver function 0x32

### PR DESCRIPTION
**Pull request by FeralChild64**
- implement one more informational function of the DOS mouse driver - might help applications to determine which functions our driver implements
- manually clean-up some indentation

### CODE REVIEW

**Review by johnnovak — APPROVED** [review]
Looks okay, although I have no idea what this is doing 😄 Did you test it with something that uses this?

**Review by kcgen — APPROVED** [review]
Looks good, @FeralChild64 - and nice logging refinements.

**Comment by FeralChild64** [comment]
> Looks okay, although I have no idea what this is doing smile Did you test it with something that uses this?

It returns a bitfield telling which functions the mouse driver supports. Unfortunately, I haven't found anything that uses it - but the implementation itself is rather trivial.
In fact, some software SHOULD call this function, but it doesn't - for example, MSD.EXE calls function 0x34 to get the MOUSE.INI file path information, not checking first whether the driver supports function 0x34 or not :/

**Comment by johnnovak** [comment]
> > Looks okay, although I have no idea what this is doing smile Did you test it with something that uses this?
> 
> It returns a bitfield telling which functions the mouse driver supports. Unfortunately, I haven't found anything that uses it - but the implementation itself is rather trivial. In fact, some software SHOULD call this function, but it doesn't - for example, MSD.EXE calls function 0x34 to get the MOUSE.INI file path information, not checking first whether the driver supports function 0x34 or not :/

Thanks for the explanation @FeralChild64.

**Pull request merged**
