### PR TITLE
Cleanup formatting of a couple markdown tables

### PR DESCRIPTION
**Pull request by kcgen**
# Description

Cleanup table formatting (white-space / table tokens) in a couple markdown files using an auto-formatter.  No content changes.

## Related issues

The latest update of the markdown linter catches MD055 and MD057, which are flagged:

```text
README.md:26: MD055 Table row doesn't begin/end with pipes
README.md:27: MD055 Table row doesn't begin/end with pipes
README.md:28: MD055 Table row doesn't begin/end with pipes
README.md:29: MD055 Table row doesn't begin/end with pipes
README.md:30: MD055 Table row doesn't begin/end with pipes
README.md:31: MD055 Table row doesn't begin/end with pipes
README.md:32: MD055 Table row doesn't begin/end with pipes
README.md:33: MD055 Table row doesn't begin/end with pipes
README.md:34: MD055 Table row doesn't begin/end with pipes
README.md:35: MD055 Table row doesn't begin/end with pipes
README.md:36: MD055 Table row doesn't begin/end with pipes
README.md:37: MD055 Table row doesn't begin/end with pipes
README.md:38: MD055 Table row doesn't begin/end with pipes
README.md:39: MD055 Table row doesn't begin/end with pipes
README.md:51: MD055 Table row doesn't begin/end with pipes
README.md:52: MD055 Table row doesn't begin/end with pipes
README.md:53: MD055 Table row doesn't begin/end with pipes
README.md:54: MD055 Table row doesn't begin/end with pipes
README.md:55: MD055 Table row doesn't begin/end with pipes
README.md:56: MD055 Table row doesn't begin/end with pipes
README.md:57: MD055 Table row doesn't begin/end with pipes
README.md:58: MD055 Table row doesn't begin/end with pipes
README.md:59: MD055 Table row doesn't begin/end with pipes
README.md:60: MD055 Table row doesn't begin/end with pipes
README.md:61: MD055 Table row doesn't begin/end with pipes
README.md:62: MD055 Table row doesn't begin/end with pipes
README.md:63: MD055 Table row doesn't begin/end with pipes
README.md:64: MD055 Table row doesn't begin/end with pipes
README.md:65: MD055 Table row doesn't begin/end with pipes
README.md:66: MD055 Table row doesn't begin/end with pipes
README.md:67: MD055 Table row doesn't begin/end with pipes
README.md:68: MD055 Table row doesn't begin/end with pipes
README.md:69: MD055 Table row doesn't begin/end with pipes
README.md:70: MD055 Table row doesn't begin/end with pipes
README.md:71: MD055 Table row doesn't begin/end with pipes
README.md:72: MD055 Table row doesn't begin/end with pipes
README.md:73: MD055 Table row doesn't begin/end with pipes
README.md:74: MD055 Table row doesn't begin/end with pipes
README.md:75: MD055 Table row doesn't begin/end with pipes
README.md:76: MD055 Table row doesn't begin/end with pipes
README.md:77: MD055 Table row doesn't begin/end with pipes
README.md:78: MD055 Table row doesn't begin/end with pipes
README.md:79: MD055 Table row doesn't begin/end with pipes
README.md:80: MD055 Table row doesn't begin/end with pipes
README.md:81: MD055 Table row doesn't begin/end with pipes
README.md:82: MD055 Table row doesn't begin/end with pipes
README.md:83: MD055 Table row doesn't begin/end with pipes
README.md:27: MD057 Table has missing or invalid header separation (second row)
README.md:52: MD057 Table has missing or invalid header separation (second row)
website/docs/downloads/release-notes/0.76.0.md:40: MD055 Table row doesn't begin/end with pipes
website/docs/downloads/release-notes/0.76.0.md:41: MD055 Table row doesn't begin/end with pipes
website/docs/downloads/release-notes/0.76.0.md:42: MD055 Table row doesn't begin/end with pipes
website/docs/downloads/release-notes/0.76.0.md:43: MD055 Table row doesn't begin/end with pipes
website/docs/downloads/release-notes/0.76.0.md:41: MD057 Table has missing or invalid header separation (second row)
website/docs/getting-started/dark-forces.md:135: MD055 Table row doesn't begin/end with pipes
website/docs/getting-started/dark-forces.md:136: MD055 Table row doesn't begin/end with pipes
website/docs/getting-started/dark-forces.md:137: MD055 Table row doesn't begin/end with pipes
website/docs/getting-started/dark-forces.md:138: MD055 Table row doesn't begin/end with pipes
website/docs/getting-started/dark-forces.md:139: MD055 Table row doesn't begin/end with pipes
website/docs/getting-started/dark-forces.md:140: MD055 Table row doesn't begin/end with pipes
website/docs/getting-started/dark-forces.md:136: MD057 Table has missing or invalid header separation (second row)
```

# Manual testing

`mkdocs serve` shows correct table rendering:

---

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [x] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
Thanks for looking into this @kcgen.

The starting and ending pipe chars of Markdown table rows are entirely optional, so the new MD055 warning is about increasing compatibility with various renderers:

https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md055---table-row-doesnt-beginend-with-pipes

I've been leaving the ending pipes off because I've been aligning tables manually and doing that by hand is a pain, but I think it's better to start using a plugin for all that 😄 This one seems promising: 

https://thoughtbot.com/blog/align-github-flavored-markdown-tables-in-vim

Another thought: should we pin the version of the linter too, just like I have pinned the versions for the rest of the doco generation toolchain? My use case for doing that it due to my use of custom templates, MkDocs updates that change the template semantics might silently break some functionality (the search did break once this way and it took me a while to figure out). No such danger with a simple linter, but then the upgrade model would be consistent for the doco toolchain.

**Review by johnnovak — APPROVED** [review]
Nice quick fix 🎉

**Comment by kcgen** [comment]
Yeah, the markdown table formatters are really handy.. I write them as lazy as possible without any manual formatting:

```markdown
Col_A | Col_B
--- | ---
val_a1 | val_b1
```

And the formatter blasts out a tidy table:

```
| Col_A  | Col_B  |
|--------|--------|
| val_a1 | val_b1 |
```

Which is easier to read in ascii-mode too, so I can see the justification for these handy warning. 

As for pinning analyzer versions.. I don't think it's possible because we're just installing current version in the repo.

If @shermp moves most of CI into docker containers, then the image will get stale with time, and in that sense, the versions will be pinned until the next major ungraded of the container images. 

I tend to prefer latest versions of analyzers and linters though because they don't alter our release.

Also, I've seen a lot of cases where versions get pinned.. and after N years the team upgrades in a "big bang" approach, and get a big rude awakening with lots of build failures, linter warnings and failures, and so on. 

Someone wrestles with the critical path (just getting the code built, which is the most important) and then when faced with all the linters, the team is quick to "blame the linter" and vote it to be removed entirely "well, this is obviously a lot of pain and a nuisance, so let's just get rid of it instead of every dealing with that again". 

So I'd rather do these little one-off tweaks as they come to mitigate against big-bang human behavior. 

(I've had a hard enough time lobbying the team to keep warning levels high.. so the less obstacles the better😂).

**Comment by johnnovak** [comment]
> Also, I've seen a lot of cases where versions get pinned.. and after N years the team upgrades in a "big bang" approach, and get a big rude awakening with lots of build failures, linter warnings and failures, and so on.

Oh yeah, me too 😅  I guess a like a more controlled approach these days: scheduled upgrades. I just don't like when the CI loop gives me tasks 😄 Pencil in a "patch week" every 3-4 months in the calendar, but then that requires more discipline, true.

The problem with letting main autoupgrade is that it forces you to fix it, otherwise you can't merge stuff before that. Which one might say is by design, but I see patching more like a long term goal (unless it's security patching), so the CI loop elevates this long term goal to number one prority if there's a breakage. I don't like that, hence my preference for scheduled upgrades.

Ideally, you'd have a "canary" build that is not on main, just to give you a heads up about potential breakages but not actually break anything in main
 But that's maybe too much automation for us 😄 

Plus, like I said, in sime cases autoupdating is actively dangerous because stuff will not break but misbehave, like with MkDocs (there is room for a lot of subtle regressions even though your stuff compiles... like SDL? 😅 )

**Comment by kcgen** [comment]
> Ideally, you'd have a "canary" build that is not on main, just to give you a heads up about potential breakages but not actually break anything in main. But that's maybe too much automation for us 😄

Oh that's perfect; a handful of canary builds plus the pinned CI container images. 

We could set these canary jobs to run in cron, say once a month, on each platform just using GitHub's current compilers and linters. It would represent a typical users building on their home system and give us that early warning system about breakages that will eventually hit the next rev of containters. 

(Adding @shermp to bring the container goodness 🚢 !)

**Comment by johnnovak** [comment]
> We could set these canary jobs to run in cron, say once a month, on each platform just using GitHub's current compilers and linters. It would represent a typical users building on their home system and give us that early warning system about breakages that will eventually hit the next rev of containters.

Yes, that would be my preference; I think that solution would hit the best overall balance. Hopefully, it wouldn't complicate things too much, but yeah, I'm 100% onboard 🚀

**Pull request merged**
