### PR TITLE
Load front-page images from `static/images` instead of archive.org

### PR DESCRIPTION
**Pull request by johnnovak**
# Description

As discussed, I'm experimenting with hosting the front page images in our GitHub Pages site instead of archive.org. I think it's definitely faster this way.

I copied the images into the `static/images` dir of our org level GitHub Pages repo:
https://github.com/dosbox-staging/dosbox-staging.github.io/tree/master/_images

This is where the website gets published, so I've extended the workflow to ignore the `static` dir on deploys. The idea is that if this works well, I will move all files over, then we could have `static/files`, `static/audio`, `static/video`, etc. 

# Manual testing

Deployed this as the preview website to https://dosbox-staging.github.io/preview/dev/

Verified that there are no links to archive.org on the front page. The screenshots now all live in GitHub pages, e.g.:

```
https://dosbox-staging.github.io/static/images/front-page/legend-of-kyrandia.jpg
```

It feels faster to me. Let me know what you think.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [x] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by kklobe — APPROVED** [review]
huge improvement @johnnovak! Tested on three devices with five different browsers

**Comment by shermp** [comment]
A massive improvement in load times here. Loading the thumbnails on the home page is near instantaneous for me now.

**Comment by shermp** [comment]
And yes, I think a `static` (or similar) dir is probably the way to go.

**Review by weirddan455 — APPROVED** [review]
Looks good to me

**Comment by weirddan455** [comment]
@johnnovak Another problem I'm seeing here with your CI changes though.  The checks got skipped which is expected since this PR does not touch C++ code.  However, the merge button is grayed out because of that.  I suppose you probably have permissions to over-ride that but wanted to bring it to you attention.

merge-button

**Review by shermp — APPROVED** [review]

**Comment by johnnovak** [comment]
> @johnnovak Another problem I'm seeing here with your CI changes though. The checks got skipped which is expected since this PR does not touch C++ code. However, the merge button is grayed out because of that. I suppose you probably have permissions to over-ride that but wanted to bring it to you attention.
> 
> merge-button

It's not that. I've rebased to main to retrigger the workflows and it's all green now.

All workflows got triggered by this PR because I've changed a wirkflow file as well. Then I cancelled thosebuild workflows manually because I knew the changes are website only. I got the habit of doing that because the long running build workflows often starve the deploy website workflow from available runners. Then you gotta wait 5-10 minutes for the deploy website to run which usually takes around a minute or so.

So yeah, it was me, and there's no issue with the new workflows 😄

**Comment by johnnovak** [comment]
> And yes, I think a `static` (or similar) dir is probably the way to go.

I'll do that before merging.

**Comment by johnnovak** [comment]
Okay, further changes:

- Moved images files from `_images` to `static/images`
- Updated the documentation guide
- Also created a `README.md` in our [GitHub Pages repo](https://github.com/dosbox-staging/dosbox-staging.github.io) with a few important pointers
- Updated the [preview website](https://dosbox-staging.github.io/preview/dev/)—still looking good

I will shovel over all the files currently hosted on archive.org into `static` in the coming weeks as this is working really well. That's a lot easier to manage than the archive.org uploads anyway and anyone from the team will be able to do it.

**Pull request merged**
