### PR TITLE
Apply an efficient audio envelope to initial channel data on start

### PR DESCRIPTION
**Pull request by kcgen**
This applies an expanding envelope to the first 5-ms of audio when a channel starts feeding samples to the mixer.  

Well behaved audio isn't affected; it's only initial spikes / pops / clicks / or square-waves that may exceed the bounds of the envelope, and even they aren't affected too much: only their volume is capped to the permitted instantenous envelope edge; the frequencies aren't affected nor are lower adjacent samples.

This was implemented in a very efficient manner:
1. The envelope parameters are pre-computed once when the channel is configured
2. The envelope itself consists of a integer clamp() and two integer increments.
3. Once the envelope is done processing the first ~100 or so samples, it's replaced with a no-op function so completely gets out of the way.

An example can be seen here, up very close so we can see individual samples.  This channel wants to starts straight into playing a square wave; we see the the envelope controls the volume on the first ~hundred samples - and by the time the second square wave is generate the envelope is out of the picture (and peak volume is permitted).

Screenshot at 2020-06-05 20-15-27
  
Here's an example with well-behaved audio.  

Screenshot at 2020-06-05 20-25-03

The vertical highlighted sliver represents the enveloped 5ms region where the game, if it wanted to, could have ramped the volume all the way to the edges; however we see the audio isn't even close to that.. the game developer has faded in the audio on a far greater time scale, and at volumes not even close to peak.

So in this example, the envelope isn't even used; and infact, that's exactly what we want.  The envelope is the worst-case fallback.

This is based on top of the PCM-zero DC PR; so suggest we review and merge that first.  I've also layered this commit-by-commit, so hopefully easy to review. (the "impact" to the mixer.cpp and header is just a couple lines each.. it's not much code, and quite self-contained).

### CODE REVIEW

**Comment by dreamer** [comment]
Seems like it would be appropriate to rebase this PR on top of the newest master?

**Comment by kcgen** [comment]
> Seems like it would be appropriate to rebase this PR on top of the newest master?

Will do :-)

**Comment by kcgen** [comment]
Weird - GitHub's showing 52 commits for this PR (is this a UI change for just me - or are you seeing that too?)

When I rebased, it just had conflicts with our adjustments to the PC-Speaker PR - which were easy enough to adjust.

Code builds and works fine (and I'm seeing the initial evenlope per the PR notes above).  Can you tell if I did something wrong?

**Comment by dreamer** [comment]
Not sure how it exactly happened (I can imagine several scenarios ;) ), but just now I noticed that GitHub wants to merge this branch into `kc/zero-offset-speaker-1` - which is wrong, we want to merge this to `master`; in result, commits from master got picked up as changes for `kc/zero-offset-speaker-1`.

I'm afraid the only way to fix the review is by creating new PR. Following steps should clear out merge commit we don't want and prepare new, clean branch:

```
git checkout kc/envelope-channel-on-start-1
git checkout -b kc/envelope-channel-on-start-2
git reset --hard d9cbd3675311f1b356f6e341500c0f08309c22d3
git fetch
git rebase origin/master
# once branch has exactly the changes you want, create a new PR out of kc/envelope-channel-on-start-2 and make sure it's targetting master branch
```

(when doing test rebase to get a hang of what conflicts are there I noticed some commits should probably be dropped during conflict resolution - the version of these commits as originally appeared in `kc/zero-offset-speaker-1` was probably slightly different than version after review)

**Comment by kcgen** [comment]
Worked flawlessly; thanks for those steps that got me promptly back on track! 
Moving this over to the the new `-2` PR.

**Pull request closed without merging**
