### PR TITLE
Minor country and help fixes

### PR DESCRIPTION
**Pull request by FeralChild64**
# Description

1. Fix two comments in country data definitions (data is OK; it is the comments which are wrong) - noticed by @rderooy 
2. Fix problem I have discovered while updating Polish translation - to determine UTF-8 string length in characters we need something much more sophisticated than `strlen` or C++ counterparts (they give us length in bytes, and a single Unicode character might need many bytes to be encoded); it is much easier to rely on the translator to put a proper number of minuses (as a title underscore). 

Screenshot-Bug

# Manual testing

Execute `dosbox --list-countries` and `dosbox --list-glshaders` commands

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
> to determine UTF-8 string length in characters we need something much more sophisticated than strlen or C++ counterparts

Oh man... don't tell me this is still an unsolved problem in the C++ std lib... Like every lowly scripting language had this for 20 years now...😞

**Comment by FeralChild64** [comment]
> Oh man... don't tell me this is still an unsolved problem in the C++ std lib...

Unfortunately, it is.
- There is `std::wstring`, but it is not portable, on Windows it is 16-bit only. AFAIK not much standard library functions can deal with it.
- We have `std::u32string`, which can be used to deal with UTF-32 encoding, not really useful for us. Moreover, `size()` will tell us the number of code points, while we need the number of graphemes here (and a grapheme can be made, for example, from one code point telling about a base Latin letter + two other telling about combining marks; IIRC Baltic languages are particularly nasty here).
- C++20 has `std::u8string` to deal with UTF-8. But the standard library offers nothing to handle it. Might be useful to us once we migrate to C++20, but only for type checking.

I could implement UTF-8 compliant `strlen`, by asking my Unicode engine to convert UTF-8 to ASCII and then run a regular string size check - but this is too risky, I might improve my Unicode engine in the future to cooperate with emulated DOS more closely, and at this point we don't have DOSBox fully initialized - I'm not sure if I'll remember to test this particular use case like 2 or 3 years in the future.

IMHO better ask the translator to do the job.

**Comment by johnnovak** [comment]
> Moreover, size() will tell us the number of code points, while we need the number of graphemes here (and a grapheme can be made, for example, from one code point telling about a base Latin letter + two other telling about combining marks; IIRC Baltic languages are particularly nasty here).

Actually, I take my statement back that "every other stdlib" can do this 😅 I'm pretty sure most other languages offer the same basic support only, i.e., they only count "code points", or "runes" (they're called runes in Nim, for instance). But not that wacky situation you described.

Also some libs just shit themselves when dealing with 4-byte UTF-8 emojis which are super popular among Asian audiences (talking from real world experience here; 4-byte UTF-8 emojis caused so many headaches for me in the past...)

**Review by kcgen — APPROVED** [review]
Tha is for the thorough discussion and explanation, @FeralChild64 !

Makes sense.

**Pull request merged**
