### PR TITLE
Use `main` as Staging's default branch

### PR DESCRIPTION
**Pull request by kcgen**
Suggest reviewing commit-by-commit. 
I was able to test the import script using a local `main` branch. 

All that's left is to [select `main` as the default branch in the project settings](https://github.com/github/renaming#renaming-existing-branches).

GitHub takes care of the rest:
-    Re-targets any open pull requests
-   Updates any draft releases based on the branch
-    Moves any branch protection rules that explicitly reference the old name
-    Updates the branch used to build GitHub Pages, if applicable
-    Shows a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
-    Shows a notice to contributors who git push to the old branch
-    Redirects web requests for the old branch name to the new branch name
-    Returns a "Moved Permanently" response in API requests for the old branch name

### CODE REVIEW

**Comment by kcgen** [comment]
`main` is the default branch in [GitHub](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/), [GitLab](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/), and recommended by the (SFC)[https://sfconservancy.org/news/2020/jun/23/gitbranchname/].

In additional, git maintainers  are also actively transitioning git the default to `main`, a large amount of this work   involves updating all existing tests in the Git project.
 - https://lore.kernel.org/git/xmqqa6vf437i.fsf@gitster.c.googlers.com/T/#t
 - https://lore.kernel.org/git/pull.656.v4.git.1593009996.gitgitgadget@gmail.com/

**Comment by kcgen** [comment]
SDL is using `main`:

**Comment by kcgen** [comment]
The fast-version of the script that pulls commits from DOSBox SVN was cited as the only area needing change to accommodate a `main` branch, as currently it contains hardcoded aspect that tie it to @dreamer's account.

To progress this issue, last month I carried out the `main` rename on my own kcgen/dosbox-staging using a modified slow-version of the import script where the default branch is now parameterized as logged in this PR's commits:



This updated slow-version successfully performed the commit imports (per the import procedure [here](https://github.com/dosbox-staging/dosbox-staging/wiki/Maintenance-and-Release-Notes#41-pulling-svn-revisions)).  I also tested the many other git operations, and they worked without issue.

**Comment by kcgen** [comment]
@dreamer ,  regarding the timeframe to get the fast-version of the import script parameterized with a `main` branch, if we set an Oct 1 cutoff for this PR - is that something that works for your schedule?

**Comment by GXTX** [comment]
This seems like a change for change sake. Does this offer anything in return?

**Comment by kcgen** [comment]
> This seems like a change for change sake. Does this offer anything in return?

In this case, our primary branch will no longer be named `master`.  New git projects by default use `main`: `master` is deprecated.

**Comment by GXTX** [comment]
> I will delete them in a couple days to no degrade the signal to noise ratio.

Had there been an issue opened before this PR was issued I'd have commented there.

I see this change as a non-useful change which offers no benefits to the project as a whole, and is just change for the sake of change.

**Comment by kcgen** [comment]
> Are there branch naming collisions when using master as default? 

Why would there be collisions, when branch names are unique in a given repo? 

> Does dosbox-staging intend to do anything with master after switching to main?

The branch will simply be renamed.  It will not exist after renaming.  

When existing users `git pull`, the change will be reflected in their local repo without any action needed on their part.  This is no different than any other branch rename.

 Git allows any branch to be defined as the default; it just happens that master became popular because the Linux kernel devs started using it. 

> offers no benefits to the project as a whole, and is just change for the sake of change.

I've renamed variables many times before, because I felt I could improve the name.  Just as I intent to rename this variable, from master to main, because I feel it's a more accurate description of the branch's role. 

In all of the above cases, a rename was (and will be) carried out satisfy my own personal preferences. 

Just as you are now telling me that my opinion as a maintainer serve no value to the project, where have you been in all the other prior instances where again, I carried out a rename purely to satisfy my own personal preferences?

Please stick around, because there will be many more renames still to come that are based on my opinion.

I should ask: The SDL project's GitHub repo similarly is using a main default branch.  I take it that decision also stirs the same objections with you? 

 If not: how is it that SDL can carry out such a decision of value and yet this decision here is without value? (When both produce the same end state).

Now getting back to something slightly pragmatic: 
If you have tools or software that cannot handle branches other than master: then please let me know.

**Comment by GXTX** [comment]
> Why would there be collisions, when branch names are unique in a given repo?

I ask this because I fail to see why this change is needed. `I carried out a rename purely to satisfy my own personal preferences` seems to be the call here.

> because [...] it's a more accurate description of the branch's role

Could you explain why?

> where have you been in all the other prior instances

I only recently found out about this project. Thank you and everyone else for bringing legacy code up-to-date! Seriously incredible work.

> SDL

If I cared more about SDL and were around when they were going through the change I might've commented.

I feel like we're just arguing here. I just can't see the reason for the change beyond it's what you want (as you've stated has happened in the past), and it's what some others have done. I only wished to comment while this was still in the process of being merged.

**Comment by kcgen** [comment]
> > Why would there be collisions, when branch names are unique in a given repo?
> 
> I ask this because I fail to see why this change is needed. `I carried out a rename purely to satisfy my own personal preferences` seems to be the call here.
> 

That's exactly the call here. 

I don't know if you're new to open source or volunteer development efforts: but literally everything done to a project stems from the same origin, and those reasons might not be logical or justified to you. 

> > because [...] it's a more accurate description of the branch's role
> 
> Could you explain why?

Logically, master implies control or dominion over a subordinate.  Infact, the master branch has neither over its subbranches: Infact, the subbranches instead Inact their change overtop of the master. So even in the true sense of 'being a master': it's not.

Main doesn't imply control or dominion. It simply implies central or default, and being main means it's not a derivative.

Second: It's also shorter to type. 

Third: because it's a name that I don't want to use anymore.  Given the choice: I also prefer to use names like block-list and allow-list versus blacklist and whitelist. 

Any one of those is reason enough, to me, to go-ahead. 

However, even if I just said " I prefer it better, it just has a better ring to it".  That might be good enough too, because sometimes that's all it takes to rename variables.  

Will you inspect every commit and object and ask for justification on those too?

> If I cared more about SDL and were around when they were going through the change I might've commented.
> 

Please don't. Unless you're contributing value to a project, running around and asking random projects maintainers to justify variable names is only going waste time. 

> I feel like we're just arguing here. I just can't see the reason for the change beyond it's what you want (as you've stated has happened in the past), and it's what some others have done. I only wished to comment while this was still in the process of being merged.

We'll, I've given you many reasons in this post why I will be renaming master to main. 

As a random user who has zero influence or history of providing any value here, are you going to accept those reasons? If you don't accept them: willl you fork the project so you can keep using a master branch? (You are absolutely free to do so and I encourage it if this is causing you grief).

**Comment by kcgen** [comment]
On the other hand, I hope that this is just an unfortunate first post on a very personal PR.

 If you'd like to contribute in some capacity - please see pass PR that involved valuable technical discussion and test feedback. Also see ongoing tickets where team members have done extensive testing and given extensive feedback.  All of this type of work is very welcome.

**Comment by Grounded0** [comment]
This was debated months ago and general consensus was to go ahead.

**Comment by MasterO2** [comment]
@kcgen What's the status on this PR?

**Pull request merged**
