### PR TITLE
Fix for macOS runners

### PR DESCRIPTION
**Pull request by kklobe**
# Description

These fixes allow the macOS runner setup on my local Mac to build all the artifacts. I definitely consider this a temporary hack to get 0.82 out the door.

This setup requires a separate runner for each architecture, X64 and arm64; you must install the X64 runner for X64 builds.

# Manual testing

I have run the built Mac artifacts on my local system.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by johnnovak — APPROVED** [review]
Nice work @kklobe, and yeah, we'll have plenty of time to figure out a more robust solution once 0.81 final is out 🎉

**Comment by Grounded0** [comment]
Hopefully core optimisations are the same in this temporary fix to get the 0.81.0 out like optimising binaries for speed instead of size etc. At least we got the money so this is mainly for releasing 0.81.0 finally.

**Comment by Grounded0** [comment]
Connected issues and PRs:

- #3323

**Comment by johnnovak** [comment]
> Hopefully core optimisations are the same in this temporary fix to get the 0.81.0 out like optimising binaries for speed instead of size and minimum deployment target being macOS 10.15 for x86-64. At least we got the money so this is mainly for releasing 0.81.0 finally.

There have been no changes to any of that. Nothing has changed in those points you mentioned, we've executed the same build process. Those fixes are just some path adjustments, etc.

**Pull request merged**
