### PR TITLE
[DRAFT] Website - Linux Untested builds, Development builds - architecture

### PR DESCRIPTION
**Pull request by Torinde**
Replacement for #2798
- development-builds.md - Linux and macOS architectures mentioned
- linux.md - add section for the Untested snapshot builds - Platforms.yml

### CODE REVIEW

**Comment by johnnovak** [comment]
We're almost there @Torinde but this needs a few more adjustments 😄 

1. First of all, not sure if you're aware that you can easily test your documentation changes locally. Please follow these instructions:
https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally

2. The markup of the untested builds section is screwed up. This is what's get generated:

image

I suggest the following format instead:

image

Just use the following markup:

```markdown
### Currently running builds

<div class="compact" markdown>

- 32-bit ARMv6 and ARMv7-
- 64-bit ARM
- Power ISA low endian
- IBM z

</div>

### Currently disabled builds

<div class="compact" markdown>

- 32-bit Power ISA
- 64-bit Power ISA big endian
- MIPS
- RISC-V

</div>
```

3. The download links don't work; that table is stuck forever in "loading mode" and there's tons of output in the JavaScript console. So please fix up the JavaScript.

image

4. Some further wording improvements:

- "These are unstable development snapshots intended for testing. "

Let's say "intended for hardening". It's in the "Untested snapshot builds" section, so saying these are intended for "testing" is a contradiction 😎 

- "You can also refer to the [Build related documentation](https://github.com/dosbox-staging/dosbox-staging/tree/main/docs)."

"Please refer the Build related documentation for further details." would read better.

5. Commit log messages.

Commit messages related to the website are prefixed with `website: `. Then in general don't prefix other commit messages with the filename; we can see what file it refers to from the commit log. So please rewrite the messages to this:

- website: Add untested snapshot builds to the Linux downloads page
- website: Mention Linux and macOS architectures on the development builds page


"development-builds.md - Linux and macOS architectures mentioned"

---

Thanks @Torinde, let me know when you're done!

**Comment by Torinde** [comment]
Agree with that. I'll do another shot at it, but later...

> If someone just merges your PR without testing

Wait, I thought that won't happen, reviews and all... but now that you mention... it's possible on cursory look it's good, when actually it isn't. Sorry for that.

Now on the lists:
My sources are the Github actions
image
Then, some comments from @kcgen about G4, MIPS, then some RISC-V mention elsewhere, then your edits above, then the files at https://github.com/dosbox-staging/dosbox-staging/tree/main/src/cpu/core_dynrec

image


So, as you see these sources have some conflicts:
- IBM z: s390 (32-bit) is not mentioned, only s390x (64-bit) is in Actions
- 64-bit Power ISA big-endian, RISC-V - I don't see those in core_dynrec, but maybe RISC-V should be encouraged anyway
- core_dynrec has files "risc_x86" (AMD64 32-bit backend) and "risc_x64" - adding to the fun
- MIPSel32 is in core_dynrec, so it's 32-bit only?
- ARMv6 and v7 are in Actions, but not in core_dynrec
- multiple ARMv4 are in core_dynrec

My current _guess_ is the following:

Currently running builds
- 32-bit ARMv6 and ARMv7
- 64-bit ARM
- 64-bit Power ISA little-endian
- 64-bit IBM z

Currently disabled builds
- 32-bit ARMv4
- 32-bit Power ISA
- 64-bit Power ISA big-endian
- 32-bit MIPS
- RISC-V

Do you know a good place to see a list of Linux CPU architecture abbreviations and their meaning? s390x, ppc64le, mipsel32, etc.

**Comment by johnnovak** [comment]
> Wait, I thought that won't happen, reviews and all... but now that you mention... it's possible on cursory look it's good, when actually it isn't. Sorry for that.

Yeah, but pushing a doco change without even looking at it how it looks when rendered is similar to doing a code change and not even trying to compile it 😄  Please read that linked DOCUMENTATION.md.

> Do you know a good place to see a list of Linux CPU architecture abbreviations and their meaning? s390x, ppc64le, mipsel32, etc.

No, but let's not overdo it @Torinde. _Roughtly_ mentioned what these experimental builds do will be fine. It's a very niche thing, please realise that. If you can find it our alone these details, then fine, but I'm afraid we don't have the capacity to figure out these obscure and frankly rather unimportant details. Listing those experimental targets loosely will be sufficient for now, so people at least know about them.

**Comment by Torinde** [comment]
Just to mention that it seems there are three .yml files that we need to link to from the table, not only one:
- https://github.com/dosbox-staging/dosbox-staging/actions/workflows/platforms.yml
- https://github.com/dosbox-staging/dosbox-staging/actions/workflows/debian-docker-build.yml
- https://github.com/dosbox-staging/dosbox-staging/actions/workflows/linux-debian-cross.yml

**Comment by johnnovak** [comment]
How's it going @Torinde? If any of the DOCUMENTATION.md instructions are unclear, let me know.

**Comment by Torinde** [comment]
Busy with other stuff, sorry.

**Comment by Grounded0** [comment]
@Torinde 

Do you have time to finish this off? Looks good to me.

**Comment by Torinde** [comment]
I want to try the procedure for pre-viewing the changes (so that I can try to "fix the Javascript")... but I'm not sure when I can get to that.

If you can be faster - go forward. In the comments above are some additional corrections from johnnovak and myself - I can check your PR to see if all of those are in...

**Comment by Grounded0** [comment]
I generally don't like to lord over other people's work but i have a good rule to follow. Try to keep it as simple as possible so its less likely to blow up on our faces.

**Comment by johnnovak** [comment]
I take it you'll never finish this properly @Torinde. I might finish the job this time, but please don't do this in the future... If you start something, please follow it through.

**Comment by Torinde** [comment]
Sorry for that, but I have an issue with my DOSbox/Github setup right now, while also not having the time to look into it.
The task above may look straightforward to you, but for me it would've been a learning exercise.

If you don't want PRs staying open/inactive for too long - I don't mind closing that one and coming back to it when I can - or somebody else proceeding with it.

**Comment by johnnovak** [comment]
> Sorry for that, but I have an issue with my DOSbox/Github setup right now, while also not having the time to look into it. The task above may look straightforward to you, but for me it would've been a learning exercise.
> 
> If you don't want PRs staying open/inactive for too long - I don't mind closing that one and coming back to it when I can - or somebody else proceeding with it.

I appreciate that, @Torinde. Checking manual and website changes locally is a hard requirement if you raise a PR, so you'll need to get that setup done if you intend to raise similar PRs in the future.

Alternatively, if you don't wanna raise a PR and do the actual work, but only want to notify us of things that need correction on the website or in the manual, please raise a regular issue ticket then someone will pick that up and do the doco change.

It's alright for this one, I'll just finish it. You raised this one before the new PR template was put in place that spells all this out, so this is a special case 😄

**Comment by johnnovak** [comment]
Merged this minus the "unpublished snapshot builds" part into the dev site. Will be published to the main site o 22 Dec with the new release.

If you want to tinker with the snapshot builds @Torinde , feel free. I couldn't get that table to work in 10 minutes and I have better things to do. You'd also need to extract the JavaScript then to a common file, not just copy paste it from the dev builds page. Anyway, job for later, and it's really low priority. Raise a PR please if you ever get it to work, then we'll discuss.

**Pull request closed without merging**
