### PR TITLE
Fix VGA draw address calculation

### LINKED ISSUE #3449: VGA regressions in some Majic 12 demos
The zoom rotator parts in [Face](https://www.pouet.net/prod.php?which=2523) and [Show](https://www.pouet.net/prod.php?which=1158) have regressed in 0.78.0. Somehow an offset is applied to the lines, so the image is shifted horizontally and it wraps around (maybe some initial line offset thing?)

These parts were rendered correctly in 0.77.1, and they're still correct in the latest DOSBox SVN.

The good news is that games don't seem to be affected by this bug.

## Show

image

image

image

image

## Face

image

image

### PR DESCRIPTION
**Pull request by interloper98**
# Description

In some demos by the Majic 12 group (Show and Face), the rotor zoom effect was offset by roughly half the screen.

This bisected to 5a5d8f and then further bisecting at the line-level isolated it to this order-of-operation change.

## Related issues

Fixes #3449.

# Release notes

The offset rotor zoom effect in the Show and Face demos by Majic 12  is fixed.

# Manual testing

Tested a handful of demos and games. Will try to work through these test programs here too - https://github.com/dosbox-staging/dosbox-staging/wiki/Video-emulation-tests#minimum-recommended-set-of-tests

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
@interloper98 Oh man, I'm very happy you've found the root cause for this! 🥳 

I was a Majic 12 member back in the day, so these zoom rotator regressions in Show and Face have always bothered me a bit. Great stuff, I'll give it some testing today! 🚀

**Comment by interloper98** [comment]
> I was a Majic 12 member back in the day, so these zoom rotator regressions in Show and Face have always bothered me a bit.

:metal: right on! In that case, it's even more important we keep those faces spinning :smile:

**Comment by johnnovak** [comment]
> > I was a Majic 12 member back in the day, so these zoom rotator regressions in Show and Face have always bothered me a bit.
> 
> 🤘 right on! In that case, it's even more important we keep those faces spinning 😄

Yeah, I wrote the chiptune for Face (elijah/Majic 12 was my handle).

**Review by johnnovak — APPROVED** [review]
Oh yeah, the zoom rotators look all correct now! 😎 🤘🏻 Thanks for fixing this, @interloper98 💯

**Pull request merged**
