### PR TITLE
Drop the libspeexdsp workaround for vcpkg

### PR DESCRIPTION
**Pull request by kcgen**

### CODE REVIEW

**Comment by shermp** [comment]
Should we bump the vcpkg baseline to give local users a hint to upgrade their vcpkg version?

**Comment by kcgen** [comment]
> bump the vcpkg baseline

I thought we always used "latest" (including for local users)?

vcpkg.json:

```json
{
    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
    "name": "dosbox-staging",
    "description": "DOSBox Staging is a fork of the DOSBox project that focuses on ease of use, modern technology and best practices.",
    "version": "0.79.0",
    "dependencies": [
        "libpng",
        "sdl2",
        "sdl2-net",
        "libmt32emu",
        "opusfile",
        "fluidsynth",
        "gtest",
        "speexdsp"
    ]
}
```

Hmm.. athough it's still failing, and not due to xcopy anymore.  This PR (xcopy failing to copy speexdsp.dll to libspeexdsp.dll) might have been a red-hearing for the failing MSVC issue, but it's a nice cleanup regardless :sweat_smile:

**Comment by kcgen** [comment]
Let's turn the crank and retry a couple more times.

**Comment by shermp** [comment]
Ah, yeah, my memory failing me. I forgot we knocked out the baseline. Sorry!

**Comment by kcgen** [comment]
> Ah, yeah, my memory failing me. I forgot we knocked out the baseline. Sorry!

And I had forgot about the speedDSP work-around, :laughing: 

Combined, the teams' memories make a whole :muscle:

**Comment by shermp** [comment]
In general, I think new line delimiting (rather than `^&` is easier to grok in Visual Studio, as it uses a multi-line editor.

**Comment by kcgen** [comment]
> In general, I think new line delimiting (rather than `^&` is easier to grok in Visual Studio, as it uses a multi-line editor.

Thanks for the tip.  Let's see if it's OK with it.

**Comment by kcgen** [comment]
@johnnovak , when you have a chance to rebase the reverb branch, it'll get this PR's fixes for a couple vcpkg and robocopy issues that had started to affected CI.

**Comment by johnnovak** [comment]
> @johnnovak , when you have a chance to rebase the reverb branch, it'll get this PR's fixes for a couple vcpkg and robocopy issues that had started to affected the MSVC CI jobs.

Sounds good.

**Pull request merged**
