### PR TITLE
Update Tracy to v0.9

### PR DESCRIPTION
**Pull request by kklobe**

### CODE REVIEW

**Comment by kcgen** [comment]
Confirmed working on Linux:

### Build DOSBox Staging w/ built-in Tracy client

`meson setup -Dbuildtype=release -Dtracy=true build/clang-tracy`

### Build the server

Prerequisite packages: `apt install libglfw3-dev libegl-mesa0 libfreetype-dev libcapstone-dev libdbus-1-dev libgbm-dev libtbb-dev libdecor-0-dev`

Build steps:
1. `git clone https://github.com/wolfpld/tracy`
2. `git checkout tags/v0.9`
3. `cd profiler/build/unix`
4. `make -j $(nproc) TRACY_NO_LTO=1`

### Profile
1.  Launch Staging.
2. Launch the server, `./Tracy-release` from where you compiled it and click 'Connect' (which defaults to localhost).

### Results

**Review by kcgen — APPROVED** [review]
Nice fix-ups for the header paths.
Confirmed good on Linux.

**Comment by kcgen** [comment]
(PR is waiting on vcpkg to bump their tracy client to v0.9)

**Review by kcgen — APPROVED** [review]

**Comment by kcgen** [comment]
Good news - I don't think we need to wait for vcpkg to include the 0.9 Tracy client because the Windows binary is provided in the Tracy 0.9 release package: https://github.com/wolfpld/tracy/releases/download/v0.9/Tracy-0.9.7z

(Merging)

**Comment by kcgen** [comment]
Thanks for the sync-up, @kklobe :+1:

**Comment by kklobe** [comment]
> 

But if Staging is built with the 0.8.2 library version that vcpkg is still on, the 0.9 binary won't allow connection.

**Comment by kcgen** [comment]
> I guess we could tell Windows users to download the old 0.8.2 binary?

Oops; indeed. (Or I suppose, they could build the MSYS2 version). 

I've submitted a version bump ticket to vcpkg: https://github.com/microsoft/vcpkg/issues/27781

**Pull request merged**
