### PR TITLE
Fix compilation errors on branch `ww/voodoo-3dfx-2` (New Version)

### PR DESCRIPTION
**Pull request by ThomasEricB**
Fixed the commit messages. @kcgen 

One of the two errors in Virtual Studio: devenv_IXdxUoEEHL

What it looks like after your apply these fixes: 
devenv_v9MaGpE4SJ

### CODE REVIEW

**Comment by kcgen** [comment]
Nice fix up, @ThomasEricB 👍

**Comment by ThomasEricB** [comment]
Way better title by the way

**Comment by kcgen** [comment]
Rebased the voodoo and fat32 branches against `main`. To get it, delete your local voodoo branch, and re-pull.

**Comment by kcgen** [comment]
> Way better title by the way

Ty 🙂 !

**Pull request merged**
