### PR TITLE
Add self-host macOS arm64 in matrix-form to CI workflow

### PR DESCRIPTION
**Pull request by kcgen**
A temporary PR share the matrixed version of the macOS self-runnet PR.

### CODE REVIEW

**Comment by kcgen** [comment]
Appears to be working.  We've assigned tags to the runner if it's willing to run debug builds and/or release builds:
---
Found online and busy self-hosted runner(s) in the current repository that matches the required labels: **'self-hosted-arm64 , debug-builds'**. Waiting for one of them to get assigned for this job.
Waiting for a self-hosted runner to pick up this job...
---
Found online and busy self-hosted runner(s) in the current repository that matches the required labels: **'self-hosted-arm64 , release-builds'**. Waiting for one of them to get assigned for this job.
Waiting for a self-hosted runner to pick up this job...
---

**Comment by kcgen** [comment]
Thanks to @dreamer for kicking off the idea of having an arm64 M1-based runner and @kklobe for putting the pieces together and co-authoring this PR (and offering his system!).

**Comment by kcgen** [comment]
## How to add a macOS arm64 runner:

1. A project administrator enters the project's settings -> actions -> runners:

    https://github.com/dosbox-staging/dosbox-staging/settings/actions/runners

2. Click 'add runner', and pass the instructions to the runner's owner.

3. When the runner appears in the list, add labels:
 - `arm64` -> this is needed because GitHub's runner software will misidentify the hosts's architecture as x64.
 - `debug-builds` -> if the runner should participate in debug builds
 - `release-builds` -> if the runner should generate release builds

Once those tags are added, the workflow will start issuing jobs to it.

**Comment by kcgen** [comment]
Builds are passing and working as expected. 
Ready for review!

**Review by kklobe — APPROVED** [review]
Looks good! We'll just need to keep in mind that the workflow will time out if I have my Mac lid closed or am otherwise offline, and will require a re-run.

**Comment by kcgen** [comment]
> Looks good! We'll just need to keep in mind that the workflow will time out if I have my Mac lid closed or am otherwise offline, and will require a re-run.

Thanks for the review @kklobe.  Fully agree:
 - For routine branch pushes, arm64 jobs are bonus if we can get them, but we'll still have our existing x64 results. 
 - For PRs, arm64 will be mandatory to ensure the code builds and that it doesn't increase warnings (without approval) - likewise, we want the testers to be able to get the latest arm64 builds.

**Pull request merged**
