### PR TITLE
Auto-exit when using instant-launch

### PR DESCRIPTION
**Pull request by kcgen**
If `startup_verbosity` is `auto` (or `low` or `quiet`) and an executable's passed on the command-line, then automatically "exit" when that program finishes up. This is equivalent to manually adding the `-exit` command-line flag.

This PR also updates the `README` to reflect this logic.

This PR also adds a 1.5 second "exit cool down period" as some protection against scenarios where an executable immediately fails *and* dosbox quits back to the host.  In these cases, the the user sees a brief flash - and then everything is gone, which is a bad user experience leaving them with nothing to help them diagnose the issue.  

This cool down should catch most of those scenarios.  Of course, using a higher verbosity (medium or high) will fully prevent auto-exit, likewise simply launch dosbox without instant-launch will also avoid the auto-exit.

### CODE REVIEW

**Comment by kcgen** [comment]
Decided to a single-file replacement of `strlen` with `safe_strlen` when possible, each in their own commit (for easy bisecting in the rare care this causes a regression).

**Comment by kcgen** [comment]
Thank you @Burrito78 for this excellent suggestion!

**Comment by Burrito78** [comment]
Copying from Discord so it doesn't get buried:

Hi @kcgen! This PR works as expected, very nice! But i found one side-effect: The "cool down" timer is always active, not only when using "instant launch".  So when i start Staging and directly enter exit then the above line "Preventing an early exit call..." is also triggered and i have to exit a second time. Is this expected and wanted behavior?

One other possible terrible idea: Maybe skip the whole autoexec section while running using instant launch to prevent mount conflicts in the first place and refer people to better use game specific config files (if needed at all) when using instant launch?

**Comment by kcgen** [comment]
> The "cool down" timer is always active, not only when using "instant launch". So when i start Staging and directly enter exit then the above line "Preventing an early exit call..." is also triggered and i have to exit a second time. Is this expected and wanted behavior?

Anytime dosbox 'instant-exits' is typically a bad thing, so I had settled on it being a general feature ... but it's indeed a changes from baseline behavior.  Perhaps there are scripts or wrappers that won't deal well with this.

I'll adjust it to only take place when instant-launching. Thanks for the help here @Burrito78 !

**Pull request merged**
