### PR TITLE
Fix core-related sanitizer issues

### PR DESCRIPTION
**Pull request by kcgen**
Fixes the following:

This PR plus the mixer left-shift PR produces clean UBSAN runs.

### CODE REVIEW

**Comment by kcgen** [comment]
@kklobe , @LowLevelMahn, appreciate any extra eyes on this, in any capacity, to double-check I didn't mix-up a value.  Don't need any context - the changes are pretty rote.

**Comment by kcgen** [comment]
I really want to get all the undefined behaviour issues fixed so we have a clean running binary.  

This will let us start using the `debugoptimized` builds + UBASAN instrumentation as a "daily debug build", and any new UBs will immediately jump out.

**Review by LowLevelMahn — APPROVED** [review]
correctly replaced code

**Review by kklobe — COMMENTED** [review]
Did not catch any incorrectly-replaced values

**Comment by kcgen** [comment]
@LowLevelMahn , @kklobe  - thanks for lending your eyes to double check this!
Merges away.

**Pull request merged**
