### PR TITLE
Meson: add unit tests

### PR DESCRIPTION
**Pull request by dreamer**
Also, some more documentation and we have unit tests running on macOS at last :)

### CODE REVIEW

**Review by kcgen — APPROVED** [review]
This is a very thorough solution offering repo provided gtest, followed by meson-wrap download and build, and finally and offline option -- all of which are nicely documented for users. 

Having unit tests running on macOS and exercising those possibly unique code branches is fantastic; thanks for getting this working, @dreamer!

``` text
1/5 gtest example      EXPECTEDFAIL   0.17s
2/5 gtest fs_utils     OK             0.07s
3/5 gtest soft_limiter OK             0.19s
4/5 gtest string_utils OK             0.19s
5/5 gtest support      OK             0.19s


Ok:                 4   
Expected Fail:      1   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0  
```

Regarding the verbose output per unit test; is that printed to stdout if we have some tests fail or timeout? (Or provide via artifacts) it would be nice to just show it.

Regarding meson's timeout - is that set to a sane limit already? (Like 60s/test?) It would be nice to clamp that down if it's a bit too generous. 

I'm looking forward to writing some FIFO unit tests :-)

**Comment by dreamer** [comment]
> Regarding the verbose output per unit test; is that printed to stdout if we have some tests fail or timeout? (Or provide via artifacts) it would be nice to just show it.

Good point! bedd9da29905027f98c244d3de0f0896902d03ec - now it is :) Only output of failing test binary is printed (which is truly good enough).

> Regarding meson's timeout - is that set to a sane limit already? (Like 60s/test?) It would be nice to clamp that down if it's a bit too generous.
https://mesonbuild.com/Reference-manual.html#test
I forgot to check that earlier; 30s.

As usual for Meson, a sane and useful setting turned on by default :)

**Comment by kcgen** [comment]
> Only output of failing test binary is printed (which is truly good enough).

Absolutely! 

> As usual for Meson, a sane and useful setting turned on by default :)

:+1:

**Comment by dreamer** [comment]
@kcgen Thanks for the quick review :)

**Comment by dreamer** [comment]
For reference: #854

**Comment by bonzini** [comment]
Hope you'll enjoy the improvements to `meson test` in 0.57 (see also mesonbuild/meson#7830) If there's anything that can be improved on that front, or if you do some testing with Meson master and find bugs, I'll be happy to help (0.57 will be enough for QEMU to switch to `meson test`, but it's always nice to help multiple projects in addition to my own).

**Pull request merged**
