### PR TITLE
Add `use_nearest_texture_filter` shader pragma and `nearest` shader

### PR DESCRIPTION
**Pull request by johnnovak**
# Description

Upscaling shaders like xbr require nearest-neighbour interpolation to function correctly. See related ticket:

- https://github.com/dosbox-staging/dosbox-staging/issues/3770

In preparation to reinstate a correctly working xbr shader that I removed because it looked like shit (with bilinear interpolation), this PR restores support for nearest neighbour interpolation that shaders can request via the `use_nearest_texture_filter` pragma.

I'm also adding a new` interpolation/nearest` shader (aliased to `nearest`), plus there's some further cleanup work.

## Related issues

_Related issues can be listed here (remove the section if not applicable.)_

# Manual testing

- Confirmed the following `glshader` settings work:
  - `none`, `sharp`, `bilinear`, `nearest`
  - `interpolation/sharp`, `interpolation/bilinear`, `interpolation/nearest`
 
- Confirmed invalid shader settings revert to the bilinear shader (e.g., `glshader = blah`).

- Tested that the CRT auto shaders still work.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by vladkosi** [comment]
Shouldn't this pragma be `force_single_scan`? https://github.com/dosbox-staging/dosbox-staging/pull/3852/commits/cfca4e187b10f0d2a35c5449f4fde46c002de7d7#diff-eb12a2033d52ccf897e449858eb778a68e0654fff85a71fa938b2db68616b62eR30

**Comment by johnnovak** [comment]
> Shouldn't this pragma be `force_single_scan`? [cfca4e1#diff-eb12a2033d52ccf897e449858eb778a68e0654fff85a71fa938b2db68616b62eR30](https://github.com/dosbox-staging/dosbox-staging/commit/cfca4e187b10f0d2a35c5449f4fde46c002de7d7#diff-eb12a2033d52ccf897e449858eb778a68e0654fff85a71fa938b2db68616b62eR30)

Well, it can only apply to VGA adapters as only VGA adapters can double-scan. What is the issue with this name, in your opinion?

**Comment by vladkosi** [comment]
It looks like a typo. The code expects `force_single_scan`, not `force_vga_single_scan`. https://github.com/dosbox-staging/dosbox-staging/pull/3852/commits/b1befca2bc73ab38257d76b3918de03c291f9f2d#diff-7a28d92a98757d0c1821d72e79c558a5a6561f8a6063eabe755462452bd1cc3aR359

**Comment by johnnovak** [comment]
> It looks like a typo. The code expects `force_single_scan`, not `force_vga_single_scan`. [b1befca#diff-7a28d92a98757d0c1821d72e79c558a5a6561f8a6063eabe755462452bd1cc3aR359](https://github.com/dosbox-staging/dosbox-staging/commit/b1befca2bc73ab38257d76b3918de03c291f9f2d#diff-7a28d92a98757d0c1821d72e79c558a5a6561f8a6063eabe755462452bd1cc3aR359)

RIght, now I got it. Well, I made an error, but the good news it's more of an "optimisation step" for this shader.

Fixing it, thanks! 😄

**Review by weirddan455 — APPROVED** [review]
This looks fine to me.  I have limited knowledge about this shader business though.

Only comment I have is it looks like that final comment was meant to be an auto-squash fixup but it got pushed as a separate commit instead.

**Comment by johnnovak** [comment]
> This looks fine to me. I have limited knowledge about this shader business though.
> 
> Only comment I have is it looks like that final comment was meant to be an auto-squash fixup but it got pushed as a separate commit instead.

Cheers, I'll fix that.

**Pull request merged**
