### PR TITLE
Remove some 'fast math' release build settings

### LINKED ISSUE #3266: Epic Pinball vertical integer scaling on 1440p monitor
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-2270-g1bd83c92c

### What Operating System are you using?

Windows 11

### If Other OS, please describe

_No response_

### Relevant hardware info

Ryzen 7 5800H, Radeon Vega iGPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Vertical integer scaling of Epic pinball only scales as high as 1280x960 when running fullscreen on a 1440p monitor. Tried with and without CRT auto shaders. The behavior is the same in either case.

Epic pinball switches into a weird 320x240 resolution during game play. The menus are 320x200, and scale appropriately to 1600x1200. Even accounting for VGA line doubling (to 480p), it should be able to scale to 1440 lines with a scale factor of 3.

### Steps to reproduce the behaviour.

Explain how to reproduce
Run Epic pinball, and get into a game (I use the Super Android table). If running a 2560x1440 monitor, you should see the game in a relatively small box in the middle.

I suspect this issue probably affects any game that uses 320x240.

### Download URL of affected game or software

_No response_

### Your configuration

```ini
[sdl]
fullscreen = true

[render]
integer_scaling = vertical
glshader = none

[cpu]
cycles = 60000

[autoexec]
mount c .
imgmount d ./cd/EPIC_PINBALL.iso -t cdrom
c:
run
```

### Provide a Log

```text
PS C:\DOSBox Programs\EpicPC95> & "C:\msys64\home\sherm\dosbox-bin-clang64\dosbox.exe" --noprimaryconf
date       time         |
2023-12-26 16:44:46.017 | arguments: C:\\msys64\\home\\sherm\\dosbox-bin-clang64\\dosbox.exe --noprimaryconf
2023-12-26 16:44:46.017 | Current dir: C:\DOSBox Programs\EpicPC95
2023-12-26 16:44:46.018 | stderr verbosity: 0
2023-12-26 16:44:46.018 | -----------------------------------
2023-12-26 16:44:46.018 | dosbox-staging version 0.81.0-alpha-2270-g1bd83c92c
2023-12-26 16:44:46.018 | ---
2023-12-26 16:44:46.018 | LOG: Loguru version 2.1.0 initialised
2023-12-26 16:44:46.021 | CONFIG: Loaded local config file 'dosbox.conf'
2023-12-26 16:44:46.021 | LANG: Using internal English language messages
2023-12-26 16:44:46.030 | SDL: version 2.28.5 initialised (windows video and wasapi audio)
2023-12-26 16:44:46.030 | DISPLAY: Initialised 1422x1066 windowed mode using bilinear scaling on display-0
2023-12-26 16:44:46.209 | OPENGL: Vendor: ATI Technologies Inc.
2023-12-26 16:44:46.209 | OPENGL: Version: 4.6.0 Compatibility Profile Context 23.11.1.231017
2023-12-26 16:44:46.209 | OPENGL: GLSL version: 4.60
2023-12-26 16:44:46.209 | OPENGL: NPOT textures supported
2023-12-26 16:44:46.210 | RENDER: Using shader 'none'
2023-12-26 16:44:46.210 | VGA: Pixel doubling enabled
2023-12-26 16:44:46.210 | VIDEO: Using the DOS video mode's frame rate
2023-12-26 16:44:46.215 | MEMORY: Using 4096 DOS memory pages (16 MB) at address: 000002C26EEEF040
2023-12-26 16:44:46.215 | VGA: Double scanning VGA video modes enabled
2023-12-26 16:44:46.215 | VIDEO: Initialised S3 Trio64 VESA 2.0 compatible with 4 MB of FP DRAM supporting 86 modes
2023-12-26 16:44:46.218 | VOODOO: Initialized with 4 MB of RAM, multithreading, and no bilinear filtering
2023-12-26 16:44:46.218 | CAPTURE: Image capturer started
2023-12-26 16:44:46.242 | MIXER: Negotiated 2-channel 48000 Hz audio of 1024-frame blocks
2023-12-26 16:44:46.242 | MIXER: Master compressor enabled
2023-12-26 16:44:46.357 | MIDI: Opened device: win32
2023-12-26 16:44:46.358 | MPU-401: Running in intelligent mode on ports 330h and 331h
2023-12-26 16:44:46.358 | OPL: Operating at 48000 Hz without resampling
2023-12-26 16:44:46.358 | OPL: Running OPL3 on ports 220h and 388h
2023-12-26 16:44:46.358 | SB16: Sound Blaster 16 OPL output filter enabled
2023-12-26 16:44:46.359 | DMA: Initialised primary controller
2023-12-26 16:44:46.359 | DMA: Initialised secondary controller
2023-12-26 16:44:46.359 | SB: Operating at 22050 Hz and upsampling to the output rate
2023-12-26 16:44:46.359 | SB16: Modern DAC output filter enabled
2023-12-26 16:44:46.359 | SB16: Setting 'BLASTER' environment variable to 'A220 I7 D1 H5 T6'
2023-12-26 16:44:46.359 | SB16: Running on port 220h, IRQ 7, DMA 1, and high DMA 5
2023-12-26 16:44:46.359 | PCSPEAKER: Operating at 48000 Hz without resampling
2023-12-26 16:44:46.359 | PCSPEAKER: Initialised discrete model
2023-12-26 16:44:46.359 | PCSPEAKER: Highpass filter enabled (18 dB/oct at 120 Hz)
2023-12-26 16:44:46.359 | PCSPEAKER: Lowpass filter enabled (12 dB/oct at 4800 Hz)
2023-12-26 16:44:46.359 | MOUSE: Will be captured after the first left or right button click
2023-12-26 16:44:46.359 | MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
2023-12-26 16:44:46.359 | MOUSE (PS/2): Standard, 3 buttons
2023-12-26 16:44:46.369 | DOS: Loaded modern locale for country 1, 'United States'
2023-12-26 16:44:46.369 | SLIRP: Slirp version: 4.7.0
2023-12-26 16:44:46.370 | SLIRP: Successfully initialized
2023-12-26 16:44:46.370 | NE2000: Initialised on port 300h and IRQ 3
2023-12-26 16:44:46.371 | CONFIG: Loaded auto-mounted drive config file 'C:\msys64\home\sherm\dosbox-bin-clang64\resources\drives\y.conf'
2023-12-26 16:44:46.371 | AUTOEXEC: Using autoexec from one or more joined sections
2023-12-26 16:44:46.451 | MAPPER: No joysticks found
2023-12-26 16:44:46.451 | MAPPER: Loaded default key bindings
2023-12-26 16:44:46.457 | SDL: Using VRR-adjusted (auto) display refresh rate of 141 Hz
2023-12-26 16:44:46.468 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz CFR, scaled to 1600x1200 pixels with 1:1.35 (20:27) pixel aspect ratio
2023-12-26 16:44:46.469 | MOUNT: Path 'C:\msys64\home\sherm\dosbox-bin-clang64\resources\drives\y' found
2023-12-26 16:44:46.470 | MOUNT: Path '.' found
2023-12-26 16:44:46.471 | IMGMOUNT: Path './cd/EPIC_PINBALL.iso' found
2023-12-26 16:44:46.471 | CDAUDIO: Operating at 48000 Hz without resampling
2023-12-26 16:44:48.029 | CHOICE: '1' (#1 of 3 choices)
2023-12-26 16:44:48.029 | MPU-401: Shutting down
2023-12-26 16:44:48.133 | CONFIG: Invalid 'mididevice' setting: 'default', using 'auto'
2023-12-26 16:44:48.234 | MIDI: Opened device: win32
2023-12-26 16:44:48.236 | MPU-401: Running in intelligent mode on ports 330h and 331h
2023-12-26 16:44:48.252 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz CFR, scaled to 1600x1200 pixels with 1:1.2 (5:6) pixel aspect ratio
2023-12-26 16:44:48.253 | SB16: DSP was reset
2023-12-26 16:44:48.253 | SB16: DSP was reset
2023-12-26 16:44:55.943 | SB16: DSP was reset
2023-12-26 16:44:55.943 | SB16: DSP was reset
2023-12-26 16:44:55.945 | SB16: DSP was reset
2023-12-26 16:44:55.946 | SB16: DSP was reset
2023-12-26 16:44:55.985 | DISPLAY: VGA 320x240 256-colour graphics mode at 59.713 Hz CFR, scaled to 1280x960 pixels with 1:1 (1:1) pixel aspect ratio
2023-12-26 16:45:08.395 | SB16: DSP was reset
2023-12-26 16:45:08.395 | SB16: DSP was reset
2023-12-26 16:45:08.396 | SB16: DSP was reset
2023-12-26 16:45:08.397 | SB16: DSP was reset
2023-12-26 16:45:08.402 | DISPLAY: VGA 320x200 256-colour graphics mode 13h at 70.086 Hz CFR, scaled to 1600x1200 pixels with 1:1.2 (5:6) pixel aspect ratio
2023-12-26 16:45:13.466 | SB16: DSP was reset
2023-12-26 16:45:13.467 | SB16: DSP was reset
2023-12-26 16:45:13.468 | CDROM: Shutting down CD-DA player
2023-12-26 16:45:13.468 | PCSPEAKER: Shutting down discrete model
2023-12-26 16:45:13.468 | OPL: Shutting down OPL3
2023-12-26 16:45:13.469 | SB16: Shutting down
2023-12-26 16:45:13.469 | MPU-401: Shutting down
2023-12-26 16:45:13.574 | CAPTURE: Image capturer shutting down
2023-12-26 16:45:13.574 | DMA: Shutting down primary controller
2023-12-26 16:45:13.574 | DMA: Shutting down secondary controller
2023-12-26 16:45:13.648 | SDL: Using standard SDI (auto) display refresh rate of 144 Hz
2023-12-26 16:45:13.649 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz VFR, scaled to 1067x800 pixels with 1:1.35 (20:27) pixel aspect ratio
2023-12-26 16:45:13.717 | atexit
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kklobe**
# Description

Removes some fast-math settings from the release build. Getting rid of `-freciprocal-math` fixes #3266, and the other options also have the potential to affect accuracy and behavior, especially in the FPU emulation.

## Related issues

#3266 

# Manual testing

Ran QTD several times and noticed no slowdown.

Also ran MCPDIAG:

CleanShot 2023-12-26 at 15 33 44@2x

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
I wonder if your rounding fixes are still necessary after this @kklobe ? There no code like no code 😎

**Comment by kklobe** [comment]
> I wonder if your rounding fixes are still necessary after this @kklobe ? There's no code like no code 😎

I actually tested this while exploring the rounding stuff, hence how quickly I guessed this was the issue. 😁

**Comment by johnnovak** [comment]
@kklobe posting your excellent find here too for posterity:

https://simonbyrne.github.io/notes/fastmath/

> I've joked on Twitter that "friends don't let friends use fast-math"

> If a sufficiently advanced compiler is indistinguishable from an adversary, then giving the compiler access to -ffast-math is gifting that enemy nukes. 

Pure gold 😂 Looks like "fast-math" is the "pixel-perfect" option of C compiler -- misleading and suggestive name combined with often perplexing results 😅

**Review by johnnovak — APPROVED** [review]
Looks good. Let me add that I would be very cautious turning FTZ off as that might cause issues with DSP filters when dealing with extremely low ouput volumes. It's a known issue in audio DSP circles.

**Pull request merged**
