### PR TITLE
[DRAFT] Quick&Dirty hack to allow Windows 3.x S3 drivers run on 8MB VRAM card

### PR DESCRIPTION
**Pull request by FeralChild64**
# Description

(experimental hack, still testing, code needs a cleanup)

_Describe a summary of your changes clearly and concisely, including motivation and context._
_Breaking changes need extra explanation on backward compatibility considerations._

_Feel free to include additional details, but please respect the reviewer's time and keep it brief._

## Related issues

_Related issues can be listed here (remove the section if not applicable.)_

# Release notes

_If this is a user-facing change that should be mentioned in the release notes, please provide a draft of the notes here._

_It doesn't have to be perfect; the person writing the release notes will expand this if needed._

_(Remove the section if no notes are needed.)_

# Manual testing

_Please describe the tests that you ran to verify your changes._

_Provide clear instructions so the reviewers can reproduce and verify your results._

_Include relevant details for your test configuration, operating system, etc._

_Ideally, you would also test your changes with a [sanitizer build](https://github.com/dosbox-staging/dosbox-staging/blob/main/BUILD.md#make-a-sanitizer-build) and confirm no issues were found._

_Non-trivial changes **must be** tested on all three OSes we support. If you can't test on a particular OS, ask the team or contributors for help._

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [ ] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [ ] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [ ] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
@FeralChild64 What's the motivation for this? What game needs this?

**Comment by FeralChild64** [comment]
8MB of VRAM can be used by the Build engine games for triple buffering even in the highest resolutions lime 1600x1200.

But once you start Windows 3.1 with S3 drivers on such configuration, the mouse cursor gets damaged. This hack fixes this problem.

**Comment by johnnovak** [comment]
> 8MB of VRAM can be used by the Build engine games for triple buffering even in the highest resolutions lime 1600x1200.

Yeah, you mentioned that (but I forgot, so thanks for reminding 😆).

> But once you start Windows 3.1 with S3 drivers on such configuration, the mouse cursor gets damaged. This hack fixes this problem.

Okay, but is running Win 3.x with 8MB of VRAM useful? I get it that you can run 1600x1200 in 24-bit true colour or whatever, but that's only useful for photo editing maybe?

I'm of the opinion that any code, and especially hacks, are complications, so if there's no good use case for it, probably best not to add complexity.

**Comment by interloper98** [comment]
We know > 4 MB VRAM breaks 100% of the time under Win3.1, so what are the options?
1. Help by auto limiting (like 256 MB HDD free space)
2. Help by quitting / informing
3. Carry on and let the user shoot their foot off (current behavior)

Given MS-DOS and Win 3.1 are the only two operating systems that DOSBox Staging runs and supports, bounding hardware sizes to their compatible ranges seems the most user friendly and reasonable - especially if it's just giving the drivers a different value.

But if that kind of help is unacceptable, as a user I want to "fail fast" so I can "fix it fast" and get back on track - instead of the software knowingly letting me enter a broken runtime situation.

**Comment by johnnovak** [comment]
> Niche??? _Duke Nukem 3D_, _Shadow Warrior_, _Blood_, _Redneck Rampage_, plus a couple of lesser known titles can make a good use of the extra VRAM. Niche, LOL :D

Yeah man, running these games in 1600x1200 is pretty niche. The games themselves aren't.

Then running these games at 1600x1200, quitting from the game, _and_ wanting to use Win3.x within the _same_ DOSBox session, _without even rebooting the emulated machine_, that's an ultra niche situation. Ready to die on this hill 😎 

I like @kcgen's idea to log a warning if someone tries to use Win3.x with more than 4MB VRAM, or forcing it to quit.

These hacks in the VGA code add up, so not willing to add more without really good reason.

I know you like to use a single DOSBox session for everything, so you can always use a batch file to set a different machine and reset/reboot the emulated machine with the nice reboot feature you did recently if the current vmem setting is 8.

**Comment by FeralChild64** [comment]
According to the latest _Steam_ survey over 25% of players have at least 1440p displays (and the number is growing) - so 1600x1200 is not that niche anymore (well, at least I tend to play games on the highest settings I can run them without having any issues). I assume we are targeting users who mostly can edit INI files by themselves :)

The reboot code is better than it was, but you still get a nasty visual effect of DOSBox window being destroyed and recreated - plus, around 30 years ago I basically stopped restarting the computer (or even the game launcher, which back then was usually the _DOS Navigator_) to run another game/app :D Seriously, restarting is always a nuisance.

A warning could be implemented, but if the user has only a VGA driver, or a "1 MB" S3 driver available in some packages, these are compatible with 8 MB VRAM cards. So we could spam our users with false warnings.

----

I'll close this PR in a moment, as I see it does not lead use into having anything useful.

**Comment by johnnovak** [comment]
@FeralChild64 

Ok, so the warning is not really feasible then. That's a shame.

> According to the latest Steam survey over 25% of players have at least 1440p displays (and the number is growing) - so 1600x1200 is not that niche anymore (well, at least I tend to play games on the highest settings I can run them without having any issues). I assume we are targeting users who mostly can edit INI files by themselves :)

Yeah, and for those people [this earlier idea of yours](https://github.com/dosbox-staging/dosbox-staging/issues/3357) would fit the bill nicely: run the emulation at custom half or quarter resolutions with the CRT shaders enabled. That would give them: a) more FPS, b) better (authentic) looking results, c) the HUD won't look like a legal disclaimer printed in 5pt hairline font on the back of a medication box 😆 

Seriously, even at 1280x1024 the HUD starts looking way to small and you can't read the smaller text in it.

- https://github.com/dosbox-staging/dosbox-staging/issues/3357

If you care about high-res and widescreen gaming, that custom resolution support would fit the bill nicely. You and I have collectively came up with a good solution in that ticket, so go for it 😎 🚀

**Comment by johnnovak** [comment]
> restarting is always a nuisance.

With reboots on a real PC, yes, 100%.

In emulators... come on, man 😏

**Comment by FeralChild64** [comment]
Build engine games handle HUDs correctly from my experience, its the Quake engine which makes them very small. On a fast PC FPS is not an issue anymore, and regarding scaled 1600x1200 vs emulated scanlines - this really depends on preferences. Keep in mind that in late 90s the first consumer LCDs started to appear.

> With reboots on a real PC, yes, 100%.
> 
> In emulators... come on, man 😏

The same, it worsens the experience.

**Pull request closed without merging**
