### PR TITLE
Add IBM PS/1 Audio support

### PR DESCRIPTION
**Pull request by kcgen**
Imports the excellent PS/1 audio support from the DOSBox-X project, which brought it in from the DOSBox Daum project, which brought it in from jmk who authored the patch.

The PR consists of many incremental commits to migrate the code base to match other Staging audio implementations. This is done in small steps to support future bisections, if needed. However, we expect to test many games to ensure no functional regressions exist.

It leaves the logic largely untouched. I figured this was a good cut-off point for this PR, and leave functional refactoring to a future PR. One areas that could be simplified would be directly measuring the DAC's FIFO fill-level instead of using bit-shifting up to byte quantities.

@dreamer , given this is a new addition, I would suggest reviewing the PR in its final-form and flag any areas that don't meet coding/naming/logic expectations. 

For play-testing, enable it with:
```
[speaker]
ps1audio = <bool>
```

The user 8-bit Keys has shared some hardware PS/1 Audio recordings here:
 https://soundcloud.com/pl212-522135920

### CODE REVIEW

**Comment by kcgen** [comment]
**DOSBox Staging IBM PS/1 Audio**

https://user-images.githubusercontent.com/1557255/115814302-a0f2cf80-a3a9-11eb-8586-9ae043e8a841.mp4

---

**Hardware**

https://www.youtube.com/watch?v=zrwhlRSixjI

**Comment by kcgen** [comment]
The PS/1 Audio card is composed on a digital-to-analog converter (DAC), typically for playing 8-bit digital sound-effects, and a 3-channel synthesizer (using the same chip as the Tandy), which is typically used for music. 

Some programs' sound effects have a different overall offset versus the rendered music, which cause cause audible pops during the transition to and from sequences.  

Here's an example Space Quest 4, where the effects are shifted below the midline: 
 


Here's a recording:

https://user-images.githubusercontent.com/1557255/116161165-275c2980-a6a8-11eb-9241-78e03febf3fc.mp4

The latest PR now includes a bias-correction to move these DAC effects back to the midline:



Results:




https://user-images.githubusercontent.com/1557255/116161261-4d81c980-a6a8-11eb-9b12-db478db195a2.mp4

**Comment by kcgen** [comment]
This is a bigger PR, so any review help - with an eye for better C++ or logical improvement - and in any capacity, would be much appreciated!

**Review by LowLevelMahn — APPROVED** [review]
looks good - hope there are enough users around to tests all these additional devices :)

**Comment by kklobe** [comment]
I have downloaded two games that supposedly support PS/1, Prince of Persia and Police Quest 2, and I cannot hear audio on either of them. Initialization seems to pass:

```
MIXER: PS1DAC channel operating at 48000 Hz without resampling
MIXER: PS1 channel operating at 48000 Hz without resampling
PS/1: Initialized IBM PS/1 Audio card
```
I have all other sound output off, and my `[speaker]` section is:

```
[speaker]
pcspeaker   = true
pcrate      = 18939
zero_offset = auto
tandy       = off
tandyrate   = 48000
disney      = false
ps1audio    = true
```

**Comment by kcgen** [comment]
> I have downloaded two games that supposedly support PS/1

Thanks for the help @kklobe  - I'm sure glad we're testing this. 

Discord PM inbound with test package.

I'm using a couple games to test - I will try to check more. 

**Silpheed:**
1. Wait at the title screen for the star-scene intro: should be music when you see the stars.
1. Hit a key to start, wait for Xacalite. No music, but when his mouth moves, you should hear him talking.
1. Hit another key to start playing. There should be music and DAC sound-effects while playing.

Silpheed's DAC effects are actual recordings.. and were apparently the best effects Silpheed has on the PC (even better than Adlib and Roland).  The explosions are pretty satisfying. 
Amazing the game plays at 500 cycles!

**Space Quest 4**
 1. At Sierra's Coarsegold, CA mountain intro, you should hear their intro.
 2. At the start of the game, you should hear eerie music and effects as Roger's dropped and the lightening strikes.

**Comment by kklobe** [comment]
> 1. Wait at the title screen for the star-scene intro: should be music when you see the stars.
> 2. Hit a key to start, wait for Xacalite. No music, but when his mouth moves, you should hear him talking.
> 3. Hit another key to start playing. There should be music and DAC sound-effects while playing.

Confirmed.

> **Space Quest 4:**
> 
> 1. At Sierra's Coarsegold, CA mountain intro, you should hear their intro.
> 2. At the start of the game, you should hear eerie music and effects as Roger's dropped and the lightning strikes.

Confirmed.

**Comment by kklobe** [comment]
Another test: I was able to get KQ6 DOS working with a resource.cfg of:

```
 videoDrv  = VGA320.DRV
 soundDrv  = IBMPS1.DRV
 audioDrv  = AUDPS1.DRV
 joyDrv    = NO
 kbdDrv    = IBMKBD.DRV
 mouseDrv  = STDMOUSE.DRV
 memoryDrv = ARM.DRV
 directory = \SIERRA\KQ6CD
 mode = real
 minHunk   = 207k
 language  = 1
 cmd       = kq6cd
 sync      = .\
 audio     = .\
 audioSize = 8K
 cd        = YES
audio=.\
sync=.\
movieDir=.\seq
patchDir=.\
```

Approved!

**Review by kklobe — COMMENTED** [review]
Tested Silpheed, Space Quest IV, and King's Quest VI, all worked.

**Comment by kcgen** [comment]
> Another test: I was able to get KQ6 DOS working with a resource.cfg 

Brilliant, @kklobe - thank you!

I'll start a wiki-page so the community can share the list games worth playing using PS/1 Audio.

**Comment by Wengier** [comment]
> > Another test: I was able to get KQ6 DOS working with a resource.cfg
> 
> Brilliant, @kklobe - thank you!
> 
> I'll start a wiki-page so the community can share the collection of must-play PS/1 Audio games.

There is a lot of developments and code cleanups for the PS/1 Audio feature here, and I am sure that having a Wiki page listing such games is helpful.

**Pull request merged**
