### PR TITLE
On macOS, use `command ⌘` instead of `Ctrl` for F-hotkeys

### LINKED ISSUE #992: Changing floppy images with CTRL + F4 sends Dosbox to the background in macOS when other windows are open
Hi,

i mount a few floppy images with:

`imgmount a test1.img test2.img test3.img -t floppy`

When trying to switch between these image files with `CTRL` + `F4`, the Dosbox window gets always minimized and the switching itself doesn't always work correctly (because of this?).

The option in macOS to use F1-F12 as standard function keys is activated.

Regards,
Burrito78

### PR DESCRIPTION
**Pull request by kcgen**
DOSBox's default `Ctrl+F<#>` keystrokes conflict on macOS because they perform window management actions.

The fact that new uses must choose between disabling their OS's window-management hotkeys (for which they may have considerable muscle-memory) or learn how to remap DOSBox's F-hotkeys is a problem. 

**This PR:**
 - Adds the left and right GUI keys (command ⌘ on macOS / Windows-key / ...) as the third modifier (MOD3). 
 - On macOS, the **Ctrl+Fn** keystrokes are performed with the Command ⌘ key instead of Ctrl.
 - All hotkeys that _aren't_ `Ctrl+F<key>`s, such as `Alt+Enter` and `Alt+F11`, are left as-is (because they don't conflict).

**Test Results**:
 - @burrito78 - It works indeed! I'm surprised, that's pretty elegant and consistent behaviour. If "Use all F1, F2 etc. keys…“ is ON -> CMD + F4. If "Use all F1, F2 etc. keys…“ is OFF -> FN + CMD + F4; Which is exactly what I expected.
 - @grounded0 - command+f1... f12 is tested and operational.

Fixes #992 and  #1007.

### CODE REVIEW

**Comment by dreamer** [comment]
While I agree, that this is an important change… it's basically a usability regression for Windows and Linux users… :(

Previously most of our users had instruction saying Ctrl+F1, and now it's Modifier+F1 - and users are expected to do discover what "Modifier" is on their own. I don't like it.

My suggestion on how to proceed:

- `intro` - we already have a feature to display bound keybinding in keymapper - we could reuse it for discovering an actual *bound* shortcut and display it instead of hardcoded string.
- man page - this man page is used only on Unix, non-macOS systems - we should keep the default binding names in there, as they are now.
- manual/README file - in here it's ok to keep "Modifier"

*But before we do any of that - we should consult with several macOS users to confirm they are actually ok with this change - I am not sure if they will be happy about replacing two-key combination with 3-key combination (shouldn't we use simply Option+Fx and not Ctrl+Option+Fx?).*

**Comment by Grounded0** [comment]
I like the option key proposal. If it doesn't interfere with defaults and has the least keys to push then that's the best way to go. Change is needed as it is already broken by being undocumented (control-option-F1) for the keymapper and interference with the macOS defaults.

**Comment by kcgen** [comment]
The Control+Option choice was the result of several pages of diacord discusion between macOS users on Discord, narrowing this down, including references to official documentation.  I should have included this as the basis for the PR (will add those links tomorrow).

There is no functional change on Windows and Linux (all hotkey defaults are unchanged) - but I agree the documentation is less direct using 'Modifier'.  Thanks for pointing out the Man page can be left as is.  

This also leaves all the existing singular Alt/Option hotkeys intact on all systems, macOS included, - which there are several: like to adjust the CGA composite and color model, hue (in color-mode), and brightness (in mono-mode). 

If we do want to explore using Option-F<keys> instead of the proposed Control+Option-F<keys>, then this will conflict with the existing CGA related hotkeys in the above paragraph (so we'll need a new home for them.. which is OK; from our hotkey survey last year, they are rarely or never used). 

Also regarding using Option (instead of Control+Option), it seems the documentation issue would still exist -- how do we revise the documentation property?

**Comment by Burrito78** [comment]
I like the `option` approach better because it's less clutter/more elegant and easier to remember. I don't see any conflicts while poking around a little in macOS.

I agree that` intro` shouldn't change much if possible. Making the user go hunt what `Modifier` actually means seems more like a UI hack to me right in front of the audience. Also mentioning macOS specifically here seems odd/hacky in a way.

Just a general FYI from a macOS perspective: I think that having to go into keyboard properties and enabling `F1-F12` is already too much for some users. Ideally Dosbox-Staging on macOS wouldn't rely on F-Keys at all but is see that this is probably unrealistic.

Big shout out to kcgen for getting this going! I liked your ideas when i first saw them but dreamer is also right (of course :)) and i think that generally the entry barrier (especially on macOS) is still too high for new users and elegant, minimal solutions should be the goal for going forward with Dosbox-Staging.

**Comment by kcgen** [comment]
Tomorrow I will push a commit that uses `Option-F<keys>` (and drops the conflicting CGA keys) on macOS for testing. 

We can then discuss how we'd like to reflect this Ctrl/Option split in the documentation.

**Comment by Burrito78** [comment]
@kcgen Yes, you have to enable F-Keys to work as standard function keys in macOS keyboard settings. 

catalina-function-key-1-1024x898

**Comment by kcgen** [comment]
Pushed an update that uses `Option` for the -F<keys> on macOS.

It also moves the (now conflict) Hercules and CGA-mode hotkeys down to the "minus-equals-brackets" key-quad, as follows:

**Hercules**
```
 Alt/Option + Equals    Cycle the palette
```

**CGA (mono)**
```
 Alt/Option + Equals    Cycle the palette
 Alt/Option + Minus     Adjust mono brightness
```

**CGA (color)**
```
 Alt/Option + Equals    Increase hue
 Alt/Option + Minus     Decrease hue
 Alt/Option + [         Composite mode
 Alt/Option + ]         CGA model select
```

**Comment by Kappa971** [comment]
> **Hercules**
> 
> ```
>  Alt/Option + Equals    Cycle the palette
> ```
> 
> **CGA (mono)**
> 
> ```
>  Alt/Option + Equals    Cycle the palette
>  Alt/Option + Minus     Adjust mono brightness
> ```
> 
> **CGA (color)**
> 
> ```
>  Alt/Option + Equals    Increase hue
>  Alt/Option + Minus     Decrease hue
>  Alt/Option + [         Composite mode
>  Alt/Option + ]         CGA model select
> ```
Are these combinations usable with a non-American keyboard layout?

**Comment by Kappa971** [comment]
If the CTRL+<key> problem only concerns macOS, perhaps it is clearer to add just a note in the intro screen where it is specified that instead of CTRL+<key> you must use Control+Option+<key>

**Comment by kcgen** [comment]
In-program on macOS:





Conf content on macOS:

**Review by Burrito78 — APPROVED** [review]

**Comment by kcgen** [comment]
@Burrito78 ,

Regarding the notes added to README to help macOS users deconflict common keys, do you know if they will be somewhat long-lived?  

We want to be sure we're not chasing short lived hotkeys that might be different within a release or two.  (If that's the case, we could point users to Apple's online documentation instead).

**Comment by Burrito78** [comment]
Yes, i understand. I don't see that Apple would change these hotkeys anytime soon. But anything could happen, who knows. I'll keep an eye on this and if they change i will report back.

**Comment by kcgen** [comment]
Thanks @Burrito78! 
It helps a lot that you're on top of this - both the issue and the recommended working to help others!
Even if things change, we know there are eyes-on in and new wording or changes will be in-bound.

**Comment by kcgen** [comment]
Let's merge this. Reasoning:
 - The solid points raised by dreamer have been addressed. 
 - It's been reviewed by three macOS users who are in agreement with the changes.
 - The code has been runtime tested: zero change for Linux and Windows users, while macOS users get improved key mapping and documentation (both in the readme and at runtime).

If there are any corner cases, let's hit and fix those prior to 0.77!

Thank you @Burrito78 , @dreamer , @Grounded0 , @kklobe for the feedback, recommendations, and testing!

**Pull request merged**
