### PR TITLE
Update mt32emu wrap dependency to 2.5.0

### PR DESCRIPTION
**Pull request by dreamer**
In preparation for new wrap release: https://github.com/mesonbuild/mt32emu/pull/5

@kcgen can you check if this new version works correctly with your new changes?

### CODE REVIEW

**Comment by dreamer** [comment]
This is a pre-requisite for #965, I guess?

**Comment by kcgen** [comment]
> This is a pre-requisite for #965, I guess?

Yes - and it's working nicely!  Thanks for the quick update @dreamer.

I cherry picked the commit into `kc/versioned-mt32-2`, which builds clean and lets me run with all the model versions.

```
MT32: Initialized MT-32 Control v1.04 from ../mt32-roms/
```

**Comment by dreamer** [comment]
mt32emu 2.5.0 is now available in Meson WrapDB, we can start the review now :)

Finally, our normal debug builds are clean again! :)

**Review by kcgen — APPROVED** [review]
Let's go with it!

**Pull request merged**
