### PR TITLE
[post-0.82.0] Add GameMode daemon support on Linux

### PR DESCRIPTION
**Pull request by FeralChild64**
# Description

Added _GameMode_ registration support. Results might vary depending on the host system and a daemon configuration. A Discord user _michael05274_ reports using _GameMode_ manually greatly improves the emulation experience while streaming on a low performance CPU, I could observe a small (but measurable and consistent) FPS increase in Quake benchmark.

# Release notes

On Linux, DOSBox Staging now registers itself as a _GameMode_ client, there is no need to use the `gamemoderun` command anymore. _GameMode_ is a deamon that tries to tweak the system for the best gaming experience when a game or emulator is running, give it the highest priority, pin it to the high performance CPU cores, etc., depending on daemon settings. More details: https://github.com/FeralInteractive/gamemode

# Manual testing

Checked that DOSBox Staging starts and stops normally when GameMode is not installed. Checked that it does the same if daemon is installed, and _GAMEMODE: Client registered successfully_ log is printed out during the startup. 

~~Benchmarked the system using `timedemo demo1` _Quake_ command, but found no difference in performance on my system.~~ [edit] I was testing with _GameMode_ 1.8.1, which wasn't handling my CPU properly due to a bug. _GameMode_ 1.8.2 brings me a small, but measurable _Quake_ `timedemo demo1` results improvements (tested with `cycles=max`, I have discarded the first 3 measurements in each test to let the CPU warm up and thermal throttling engage):
- without _GameMode_: 176.9 / 176.5 / 176.7 FPS
- with _GameMode_: 180.4 / 180.6 / 180.3 FPS

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [x] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [x] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by FeralChild64** [comment]
The upstream most likely wants to stay compatible with old C/C++ variants, therefore they use `NULL` instead of `nullptr`. I have silenced the warnings, otherwise _Clang 15, Ubuntu 22.04_ workflow reports:

```
../src/gui/../libs/gamemode/gamemode_client.h:103:67: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:104:65: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:105:66: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:106:70: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:107:75: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:108:73: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:109:74: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:119:24: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:120:19: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:187:22: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:312:45: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:330:50: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:348:48: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
../src/gui/../libs/gamemode/gamemode_client.h:366:49: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
```

**Review by interloper98 — APPROVED** [review]
Looks like there are three exit pathways all leading to `QuitSDL`, and one including via an `atexit` trap to catch unexpected or mid-program `E_Exit(...)`.

That's nicely integrated, and I'm looking forward to trying this on my raspbian system :+1: !

**Review by johnnovak — APPROVED** [review]
Looking good @FeralChild64, thanks for providing a nicely written release notes snippet 🥇 I agree, it's 0.83.0 material, so let's keep the PR open until 0.82.0 final is out.

**Comment by FeralChild64** [comment]
I have tested GameMode with a Voodoo improvement fix from PR https://github.com/dosbox-staging/dosbox-staging/pull/3935, using QDOS (Quake mod) as a benchmark.

Unfortunately, results are terrible - like 20% lower framerate with GameMode. I don't think this tool is worth the hassle if it can cause such emulation performance regressions in some cases - closing the PR, this wasn't a good idea.

**Comment by johnnovak** [comment]
> Unfortunately, results are terrible - like 20% lower framerate with GameMode.

Well, you live and learn 😅

**Comment by FeralChild64** [comment]
@Torinde Maybe. Or maybe this is just the big.LITTLE design of the Intel CPUs which is problematic. Or maybe a better CPU cooling would have prevented thermal throttling of the P-cores.

Too many use cases, too many CPU topologies, too little to gain, too much to lose - I do not intend to spend any more time on it.

**Pull request closed without merging**
