### PR TITLE
Reconstruct and attribute DOSBox Daum's commits from SVN and X

### PR DESCRIPTION
**Pull request by ebenbruyns**
# Description

This is a reconstruction effort of daum's code layered ontop of SVN and X as would have been done originally. All the white space changes have been stripped out, which unfortunatley means that indentation suffers because of this.

The goal behind this effort was to try and increse the signal to noise ration in this code and allow for these changes to surface in a meaningful way while digging through commits. While there is still room for improvement, the bulk of the changes are now visible in a less than 10k sloc commit, which narrows it down significantly from the original 300k sloc commit against the original SVN branch. By layering the X diff in there is now a union between svn, x and daum that wasn't visible before. There are some changes in SVN that wasn't present in X.

## Related issues

Many, but this does not aim to fix those directly, this aims to assist with finding existing fixes that was not visible before

# Manual testing
You can build this as a flatpak by using this as a starting point: https://github.com/ebenbruyns/flathub

Just point to the right commit in the staging repo and do not apply the patch that gets applied in that manifest as it's already present in the code as supplied.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by kcgen** [comment]
Until till now, we've branched the entire (Daum) project off its closest SVN historic commit, given Daum was often shared as a flat zip file:
 - [forks/daum-20140126-r3857](https://github.com/dosbox-staging/dosbox-staging/tree/forks/daum-20140126-r3857)
 - [forks/daum-20150125-r3894](https://github.com/dosbox-staging/dosbox-staging/tree/forks/daum-20150125-r3894)

For those new to this aspect of the project, the Staging repository is a bit of an archeological tome that includes all of the DOSBox team's commits going back 21 years (Harekiet's first file! 7d1ca9bdd), with proper attribution and metadata, plus notable forks like hal9000's megabuild and Daum all hanging of their relevant SVN-fork point in time.

Staging itself is maintained as a fork off upstream as well, however with our default simply being `main`.

But why? 

Our ability to isolate (and bisect) change depends on the granularity of the commits in which they're made - and that's true looking forward and backward in time - going beyond just our own commits here in Staging.

Revealing the the excellent work that @ykhwong added to Daum, (with the SVN and X code separated away), will give the team the best chance to lift out features and fixes for continued use.

Thanks for this huge SCM reconstructive effort, @ebenbruyns!

**Review by kcgen — APPROVED** [review]
All looks good from my side.
- Commit authors (Valley Bell, Jon Campbell, ykhwong) all in the metadata itself
- Commit messages have command-voice titles
- Thorough description of @ebenbruyns's efforts described in the commit body
- @ebenbruyns has rightly noted himself as the person doing the SCM reconstructive effort.
- Mentions of the source and URL is provided.

**Comment by kcgen** [comment]
heads up to reviewers:

This is going into the protected (and historic) `/forks/*` area of the repo, where other forks are SCM'd off their correct SVN commit.

(This doesn't touch `main`.)

**Review by johnnovak — APPROVED** [review]
Sure, it's just another branch that doesn't affect anything else, so merge away 😄

**Pull request merged**
