### PR TITLE
Update homepage URL 

### PR DESCRIPTION
**Pull request by johnnovak**
# Description

In our desperate quest to be taken seriously, we've changed our homepage URL to https://www.dosbox-staging.org/ 😎

I used the following command, then patched up a few things manually:

```
 git grep -l "https://dosbox-staging.github.io" |  xargs sed -i "s#https://dosbox-staging.github.io#https://www.dosbox-staging.org#g"
```

Not sure about the `dosbox-staging.metainfo.xml`. I'm guessing we don't wanna change the `<id>` there, right? Linux folks? @weirddan455 @FeralChild64 @shermp 

```xml
<component type="desktop">
  <id>io.github.dosbox-staging</id>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>GPL-2.0-or-later</project_license>
  <name>DOSBox Staging</name>
  <summary>DOS/x86 emulator with advanced features</summary>
```

# Manual testing

- Publish dev site, test that the links are not broken.

- Test that the intro screen still looks fine (had to insert two extra spaces after the URL so the border is still aligned correctly; I've made the same change in all language files).

image

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by shermp** [comment]
Sorry, I don't know anything about desktop packaging in Linux, so can't help here.

**Comment by johnnovak** [comment]
> Sorry, I don't know anything about desktop packaging in Linux, so can't help here.

No prob 😄

**Comment by weirddan455** [comment]
I'm not sure exactly what that xml file is used for either.  It isn't included in the tarball on our website but it is referenced in a few scripts.  My best guess is that it's used by packagers.  Maybe Fedora uses it?  @oturpe (Fedora maintainer) is this file useful to you?

```
$ git grep metainfo
.github/workflows/linting.yml:      - name: Verify metainfo.xml
.github/workflows/linting.yml:        run:  appstream-util validate-relax --nonet contrib/linux/dosbox-staging.metainfo.xml
contrib/fedora/dosbox-staging.spec:appstream-util validate-relax --nonet %{buildroot}%{_metainfodir}/*.xml
contrib/fedora/dosbox-staging.spec:%{_metainfodir}/*
contrib/linux/meson.build:install_data('dosbox-staging.metainfo.xml', install_dir: data_dir / 'metainfo')
scripts/update-copyright-date.sh:sed -i "$code_sed_script" contrib/linux/dosbox-staging.metainfo.xml
website/docs/releases/release-notes/0.75.2.md:  (`metainfo.xml`), nor package description: please see the relevant files
```

I'll also note that we haven't been keeping the releases section updated.

```
  <releases>
    <release version="0.82.0-alpha" date="2023-12-20"/>
    <release version="0.81.0-rc1" date="2023-12-20"/>
    <release version="0.80.1" date="2023-01-06"/>
    <release version="0.80.0" date="2022-12-20"/>
    <release version="0.79.1" date="2022-09-30"/>
    <release version="0.79.0" date="2022-09-19"/>
    <release version="0.78.1" date="2022-01-07"/>
    <release version="0.78.0" date="2021-12-25"/>
    <release version="0.77.1" date="2021-08-28"/>
    <release version="0.77.0" date="2021-07-02"/>
    <release version="0.76.0" date="2020-12-03"/>
    <release version="0.75.2" date="2020-10-26"/>
    <release version="0.75.1" date="2020-07-19"/>
    <release version="0.75.0" date="2020-05-06"/>
  </releases>
```

**Review by weirddan455 — APPROVED** [review]
Everything else looks fine to me.

**Review by FeralChild64 — APPROVED** [review]
Looks correctly.

**Comment by oturpe** [comment]
> I'm not sure exactly what that xml file is used for either. It isn't included in the tarball on our website but it is referenced in a few scripts. My best guess is that it's used by packagers. Maybe Fedora uses it? @oturpe (Fedora maintainer) is this file useful to you?

metainfo.xml files are useful for desktop Linux distributions. They are defined by [AppStream] specification and are used by some package managers, such as GNOME Software, to display information about available applications. For instance, see below how DOSbox Staging looks in Fedora GNOME Software. Images and texts come from your metainfo.xml.

Indeed, changing the ID in metainfo.xml might cause some problems, most probably of the kind where package managers show duplicate entries and get confused if DOSBox Staging is already installed or not. I do not understand AppStream well enough the exactly say what would happen, but to keep it safe, I propose just leaving the ID as it is.

Somewhat relatedly, I do not think the material in `contrib/fedora` has  value anymore. I am not using the specfile there, and while the process outlined in README is a possible packaging workflow, I don't think it is a popular one, and is not how I update the Fedora package for DOSBox Staging. So I suggest the `fedora` folder can just be deleted. Doing Fedora packaging downstream in Fedora has worked fine, and unless there is somebody who is interested in doing maintenance both here and in Fedora, that's the best approach. And should such a person appears, using [Packit] would probably be the best approach anyway.

kuva

[AppStream]: https://www.freedesktop.org/wiki/Distributions/AppStream/
[Packit]: https://packit.dev/

**Comment by johnnovak** [comment]
Thanks @oturpe for clarifying this, and I agree, Fedora related build and packaging info should be removed if it's outdated and no one actively maintains it.

I've raised another PR for the removal:
https://github.com/dosbox-staging/dosbox-staging/pull/3697

Also, thanks for flagging the metainfo.xml is out of date in the `main` branch. It's up-to-date in the current release branch, so I ported the changes over in an additional commit.

**Comment by johnnovak** [comment]
But the patch seems to be for a different issue, so it isn't really surprising that it doesn't fix our regression 😄 

> If you run the game and it appears to get stuck on Start game, Enter Password or Exit to DOS Screens, you are experiencing key configuration problems, download this patch and the problem will be fixed.

**Pull request merged**
