### PR TITLE
Do not set icon at runtime

### PR DESCRIPTION
**Pull request by weirddan455**
# Description
Removes the embedded icon in icon.c.  Also removes the `SetIcon()` function that was decoding this embedded icon and programmatically setting it at runtime with `SDL_SetWindowIcon()`.  As mentioned in #3169 this is no longer the "proper" way to set an icon on any of the 3 major operating systems.  Windows prefers to have an icon embedded in its .exe by the build system which we are already doing.  On Linux, this method does not work in Wayland systems.  MacOS also does something else apparently (this code was already compiled out for Mac and MSVC).

Note for us Linux devs, we might fall back to a generic X.org icon if we're running from the build directory and don't have the .desktop file and icon files in the proper locations.  I'm considering writing a script to install these.  Once the desktop file is in place, the icon gets cached and shows up even if you run Dosbox from the terminal in a build directory.

The script could maybe also be used for end users.  Currently for Linux, we just ship a .tar.xz file.  Unzip and run.  A short script would maybe be helpful that basically just copies a desktop/start menu shortcut plus icon files.

End users that get Staging from Flatpack or from their distro's package manager would likely be unaffected.  Those packages should already be putting the .desktop and icon files in the correct place and nothing needs to be done by us.

## Related issues
#3169

# Manual testing
Copied the .desktop file to ~/.local/share/applications and the icon files to ~/.local/share/icons and confirmed the icon shows up when this is done.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by johnnovak — APPROVED** [review]
Good riddance! 🗑️ 🧹 😎

**Comment by johnnovak** [comment]
> > @weirddan455 Does the install target of the icons Makefile do a similar thing? Would it make sense to extend that Makefile instead of writing a script?
> 
> Yeah, that Makefile does pretty much what I was thinking about doing. I don't know how our end users are meant to run this though. Currently all they do is unzip a tarball if they download it from our website. I don't even see this Makefile in the the 0.80.1 release so it may get stripped out.

It's used here when creating the Linux package in our build process:

https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/create-package.sh#L142

I don't think it's meant to be packaged into the final package.

**Review by kcgen — APPROVED** [review]
:+1: ; looks good, @weirddan455 !

**Comment by Grounded0** [comment]
Does deploying this close?

- #3169

**Comment by weirddan455** [comment]
Probably not @Grounded0 but you haven't fully articulated what problem you are having exactly on that ticket.  The only bug this PR is likely to solve is the old icon appearing at the top left of the window instead of the new icons that @johnnovak made.

As far as I can tell, the only thing remaining to do for Linux icons is test the packaging and maybe write a script for users that download the tarball off the website.

This AUR package seems to depend on a `meson install` command so I'll test that later and make sure the new icons are getting installed properly:  https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dosbox-staging

**Pull request merged**
