### PR TITLE
Fix a bug detecting when the CPU register address is above 4 GiB

### LINKED ISSUE #746: Memory extender applications reliably crash DOSBox
DOSBox staging now reliably crashes when attempting to run applications that depend on DOS4GW or DOS32A memory extenders (Warcraft 1 & 2, Death Rally, Dark Legions, Wacky Wheels, etc.) but operates as expected when running non-extender games (Cosmo's Cosmic Adventures, Jill of the Jungle, SimCity 1, etc.)

To reproduce, install fresh Windows x64 DOSBox-staging with plain, auto-generated config file and attempt to execute a program/game that uses a memory extender. I think memory extenders are the common thread here, but I could definitely be wrong!

The game should load but it does not - and if we dump the output to stdout, no errors are generated, the output halts mid sentence (mine usually cuts off with "DOSBox has switched to max")

I can reproduce this on both of my laptops:
1) Dell Precision 5520, i5 7440hq, Intel UHD 630 graphics (driver v.27.20.100.8935), Windows 10 1809 LTSC x64 (17763.1613)
2) HP EliteBook 1040 G1, i7 4600u, Intel HD 4400 graphics (driver v.20.19.15.5126), Windows 10 1607 LTSB x64 (14393.4046)

The crash occurs starting with build 'v0.76.0-alpha-1000-g9a77a9' and all subsequent builds. The crash does not occur on build '0.76.0.alpha.985.g6b84faa5' and all prior builds.

Happy to provide additional info if needed!

### PR DESCRIPTION
**Pull request by kcgen**
Fixes #746 

Thanks to:
- @Diduz (#742) and @sarahwhitman (#746) for reporting. 
- @Diduz and @Grounded0 for bug confirmation testing.
- @dreamer for investigation and code review.
- @joncampbell123 for the fix and @Wengier for offering to port it.
- @Wengier and @sarahwhitman for fix verification.

### CODE REVIEW

**Comment by kcgen** [comment]
Working here on hardware 64-bit Windows 10 as well as 64-bit Windows 10 VM using DOOM + dynamic core as the test. Any help double checking would be appreciated!

**Comment by Wengier** [comment]
@kcgen Yes, I can confirm that the fixed code works with the latest version of VS2019 here too, using 64-bit dynamic core. Great work!

**Comment by kcgen** [comment]
> @kcgen Yes, I can confirm that the fixed code works with the latest version of VS2019 here too, using 64-bit dynamic core. Great work!

Thank you for the help testing this @Wengier!

**Comment by sarahwhitman** [comment]
@kcgen confirmed on my end as well, this PR resolves issue #746 on my Windows x64 systems! cheers

**Review by dreamer — APPROVED** [review]
@kcgen Thank you for porting the fix!
@sarahwhitman Thank you for the report and testing :)

**Comment by dreamer** [comment]
Ported to branch `release/0.76.x` to be released in 0.76.1: 4f6ff58901a1d2440510a9aeb876986025d966a3

**Pull request merged**
