### PR TITLE
Add `crt-auto-arcade-sharp` adaptive CRT shader

### PR DESCRIPTION
**Pull request by johnnovak**
# Description

This adds a new adaptive CRT shader called `crt-auto-arcade-sharp`, which is a sharp variant of the `crt-auto-arcade` shader for people who want thick scanlines but EGA/VGA monitor like horizontal sharpness. Needless to say, this is another fantasy setting that does not exist in real life, but for some people the arcade shader might be too blurry horizontally.

It's really game-specific which setting is better, the normal arcade shader or its sharper variant. For games that feature a lot of pixel-fonts, the sharper variant might be a better choice (e.g., pay attention to the small pixel-fonts on the Eye of the Beholder example below).

# Manual testing

Checked that it works and looks good 😎 🤘🏻 

Open the normal/sharp variants in two browser tab and switch between them to appreciate the differences.

### Gods – `crt-auto-arcade`

gods-arcade

### Gods – `crt-auto-arcade-sharp`

gods-arcade-sharp

### Eye of the Beholder I – `crt-auto-arcade`

eob-arcade

###  Eye of the Beholder I – `crt-auto-arcade-sharp`

eob-arcade-sharp

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by weirddan455 — APPROVED** [review]
I'm not the right person to review the shader code itself but there's very minimal changes on the C++ side and everything looks good there.

I can see how it makes the text sharper in those screenshots.  Great addition :+1:

**Comment by FeralChild64** [comment]
This time I see no crashes on Linux :)

**Review by kcgen — APPROVED** [review]
Looks great; code and visuals 👍

**Comment by johnnovak** [comment]
Thanks guys 😄

**Pull request merged**
