### PR TITLE
Improve platform builds workflow

### PR DESCRIPTION
**Pull request by oturpe**
# Description

_Platform builds_ workflow was broken for ppc64le and s390x architectures. This was because run-on-arch-action used by that workflow had reduced the set of available (os, arch) pairs. Migrate to supported pairs, and do two general improvements:

* Allow workflow dispatch for this workflow, so it can be run manually in addition to running periodically
* Fix version on run-on-arch-action, so that in the future, breaking changes there do not automatically break the workflow

## Related issues

Problems testing #3991 motivated this effort.

# Manual testing

Ran the workflow in my fork. Got s390x to pass and ppc64le to fail in the way that #3991 fixes. All ARM builds are failing for some reason related to zlib-ng Meson wrap. It looks like a genuine build problem when using that Meson wrap, so out of scope for this pull request where the focus is in the workflow itself.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
@oturpe Can't you just run the action in your forked repo? You wouldn't have privileges to run actions manually in our repo anyway.

**Comment by oturpe** [comment]
> Can't you just run the action in your forked repo? You wouldn't have privileges to run actions manually in our repo anyway.

That was basically what I was trying to here. The pull request was intended for my fork, but accidentally ended up here.

Since I did some fixes for the _Platform builds_ workflow, let me change this pull request to propose those fixes. I have updated title and description, and am now actually proposing these for merge.

**Comment by oturpe** [comment]
Here is an example from my fork about how _Platform builds_ now looks like: https://github.com/oturpe/dosbox-staging/actions/runs/11462012162/job/31892411919

**Comment by johnnovak** [comment]
> That was basically what I was trying to do here. The pull request was intended for my fork, but accidentally ended up here.

@oturpe Thanks, makes sense. This is a good incremental improvement so happy to merge as-is.

I saw you ran into problems with zlib-ng and Meson. Note that our future goal is to move away from Meson entirely and use CMake directly. That would sidestep the whole problem, but I don't have any timeline for this. Hopefully it will happen in 2025.

**Review by johnnovak — APPROVED** [review]

**Comment by FeralChild64** [comment]
@Torinde

1. Probably no team member has any RISC-V hardware, so we would have no idea whether the build works at all.
2. So far the RISC-V CPU performance was disappointing - much slower than Raspberry Pi.
3. There is no dynamic recompiler for RISC-V, which means DOSBox Staging would be VERY slow.

**Comment by oturpe** [comment]
In the technical sense, adding RISC-V should be simple. _Platform builds_ uses _run-on-arch-action_, and its [Supported Platforms](https://github.com/uraimo/run-on-arch-action?tab=readme-ov-file#supported-platforms) table lists `riscv64`. So, you would only need to add one more item to the [platform builds matrix](https://github.com/dosbox-staging/dosbox-staging/blob/66f60749c311116596493c3e7e202b83912b831f/.github/workflows/platforms.yml#L34) using that arch. I will leave the decision if it is a good idea or not to the core team.

**Comment by johnnovak** [comment]
> Is it possible to add there RISC-V (RV64I) as well?

Of course! You add it in a PR, test it, then maintain it 😆 All possible 😎

**Pull request merged**
