### PR TITLE
Fix debugger

### PR DESCRIPTION
**Pull request by kklobe**
To get the debugger working cross-platform, I embedded the latest [PDCurses](https://github.com/wmcbrine/PDCurses) and made a copy of their `sdl2` backend, `sdl2_dosbox`. The main issue was their use of SDL_PollEvent, which conflicted with the one in `sdlmain`. I changed the filenames to `.cpp`, which enabled me to add a simple `std::queue` to pass events from `sdlmain`.

I propose using this SDL2 backend for all platforms, deprecating `wincon` for Windows. This will allow us to more easily manage fixes and improvements and should ensure consistent behavior.

My primary goal is to get the baseline debugger functionality going with minimal impact to the code.

### CODE REVIEW

**Comment by shermp** [comment]
Do we want to consider silencing the unused var/params warnings just for the pdcurses code?

Another thing I was thinking about is where to send logging. I was investigating this debug stuff a few days ago, and it looks like the logs are all redirected to the debugger window. Do we want to keep doing that?

**Comment by kklobe** [comment]
> Do we want to consider silencing the unused var/params warnings just for the pdcurses code?

I'm ok with that. I'd prefer that to heavy editing of their base code to silence them.

> 
> Another thing I was thinking about is where to send logging. I was investigating this debug stuff a few days ago, and it looks like the logs are all redirected to the debugger window. Do we want to keep doing that?

Seems like a good candidate for a future improvement, for sure. I ended up turning off PAGING and PIT in my `dosbox.conf` for now.

**Comment by kcgen** [comment]
> Do we want to consider silencing the unused var/params warnings just for the pdcurses code?

I was originally hoping to contribute a minimal wrap for pdcurses to Meson project, similar to what we did for munt and FluidSynth.

That was before I realized the solution involved modifying pdcurses (with the event queue).  Thanks for explaining that @kklobe. 

In this case, we have to treat the code as our own.. and with 178 files added, we'll need a nice way of tracking upstream and re-layering the event queue changes, so just we can keep up to date with all their little fixes and such. 

so yeah, if we decide that vanilla pdcurses won't cut it and we need our modded version, then we'd want to get the warnings and static analysis issues fixed up.

**Comment by kcgen** [comment]
This is a really nice fix, @kklobe! 
Minimal code on the DOSBox side and using pdcurses let's the TUI interface with SDL2 instead of the host's terminal (under ncurses). 

👍

**Comment by kcgen** [comment]
Commenting on the draft PR, would suggest a single commit that just adds pdcurses as-is from upstream, without any ties into Staging (meson/visual studio or CI), with authorship credited to the upstream developer (similar to dr_libs, resid, etc..)

Then add separate commits that tie it into the build system and then another that adds the event queue modifications.

**Comment by kklobe** [comment]
> > Do we want to consider silencing the unused var/params warnings just for the pdcurses code?
> 
> I was originally hoping to contribute a minimal wrap for pdcurses to Meson project, similar to what we did for munt and FluidSynth.
> 
> That was before I realized the solution involved modifying pdcurses (with the event queue). Thanks for explaining that @kklobe.
> 
> In this case, we have to treat the code as our own.. and with 178 files added, we'll need a nice way of tracking upstream and re-layering the event queue changes to keep up to date with all their little fixes and such.
> 
> so yeah, if we decide that vanilla pdcurses won't cut it and we need our modded version, then we'd want to get the warnings and static analysis issues fixed up.

Since the new backend is really only 8 files, we could go the wrap route, just keep the 8 custom files in our repo, and go that way? My thinking was that PDCurses is probably pretty stable and we wouldn't need to update it very often (if at all), since the debugger is a mostly stationary target, so just copy it down once and call it a day, without messing with wraps.

**Comment by LowLevelMahn** [comment]
> To get the debugger working cross-platform, I embedded the latest [PDCurses](https://github.com/wmcbrine/PDCurses) and made a copy of their `sdl2` backend, `sdl2_dosbox`. The main issue was their use of SDL_PollEvent, which conflicted with the one in `sdlmain`. I changed the filenames to `.cpp`, which enabled me to add a simple `std::queue` to pass events from `sdlmain`.

My hope is that some of the changes, fixes can be going in to pdcurses main,
Did you contact the author about the warnings, maybe its possible that the author is interested to shape it further krc ist always informing the third parties about pvs, coverity findings

**Comment by kcgen** [comment]
> Since the new backend is really only 8 files, we could go the wrap route, just keep the 8 custom files in our repo, and go that way?

The less we have to carry, the better - 8 files with a couple mods is much better than 170+ source files.

Is this split approach (primary + backend) how the library is typically used? Ie. Kind of like Sdl2 + sdl2net? 

If we only had those 8 SDL pdcurses backend files in our repo, will that work if we have a repo-provided pdcurses primary lib present, or if vcpkg provides us their pdcurses libs?

(In the sdlnet example, if we just carried the sdlnet sources, then this would be compatible with any repo/vcpkg/wrap/brew provided primary Sdl2 lib)

**Comment by kklobe** [comment]
> > Since the new backend is really only 8 files, we could go the wrap route, just keep the 8 custom files in our repo, and go that way?
> 
> The less we have to carry, the better - 8 files with a couple mods is much better than 170+ source files.
> 
> Is this split approach (primary + backend) how the library is typically used? Ie. Kind of like Sdl2 + sdl2net?

I'm guessing most people just use one of the backends included and pull the whole thing in.

> 
> If we only had those 8 SDL pdcurses backend files in our repo, will that work if we have a repo-provided pdcurses primary lib present, or if vcpkg provides us their pdcurses libs?

We still would need the core source to build, not just installed libs, which complicates things a bit.

**Comment by kklobe** [comment]
@kcgen I just pushed `kk/fix-debugger-1`, let me know if this is what you had in mind with the layered commits, thanks!

**Comment by kcgen** [comment]
> @kcgen I just pushed `kk/fix-debugger-1`, let me know if this is what you had in mind with the layered commits, thanks!

Thanks @kklobe ; I think it's close!  for the  PD curses code, we didn't write any of that, so it should "start life" in our repo as a verbatim commit, under authorship of their current maintainer.

Here's an example for the "Where am I" library (written by Gregory Pakosz) was added:

https://github.com/dosbox-staging/dosbox-staging/pull/1317/commits

Specically commit https://github.com/dosbox-staging/dosbox-staging/pull/1317/commits/22815d2dfd15c4a43ed3c3d58d3dd8556e22cb27
 - the committed files are just the ones we need (plus the license), all verbatim as-is without modifications
 - authorship of the commit is assigned to the current maintainer `git commit --author "hello world <my@email.com>"`

Then subsequent commits integerate it into Staging, add meson files, etc.

So that's the first commit I think we need; the verbatim PD Curses (subset of) files + license, with the commit author assigned to their current maintainer(s).

Then your follow-on modifications (adding the queue, adding meson & VS tie-in, etc.. ), all with yourself as the author.

**Comment by kklobe** [comment]
> > @kcgen I just pushed `kk/fix-debugger-1`, let me know if this is what you had in mind with the layered commits, thanks!
> 
> Thanks @kklobe ; I think it's close! for the PD curses code, we didn't write any of that, so it should "start life" in our repo as a verbatim commit, under authorship of their current maintainer.
> 
> Here's [the PR](https://github.com/dosbox-staging/dosbox-staging/pull/1317) when we added "Where am I" library (written by Gregory Pakosz), specifically commit [22815d2](https://github.com/dosbox-staging/dosbox-staging/commit/22815d2dfd15c4a43ed3c3d58d3dd8556e22cb27) :
> 
> * the committed files are just the ones we need (plus the license), all verbatim as-is without modifications
> * authorship of the commit is assigned to the current maintainer `git commit --author "hello world <my@email.com>"`
> 
> So that's the first commit I think we need; the verbatim PD Curses (subset of) files + license, with the commit author assigned to their current maintainer(s).
> 
> Then your follow-on modifications (adding the queue, adding meson & VS tie-in, etc.. ), would come after, all with yourself as the author.

I had tried to do that - I set the first commit 285350bd4e2ea5ef44f3091ec8afe9cd63f0c2bf to the PDCurses author, with just the files I need from a `git clone`, did I miss something?

**Comment by kcgen** [comment]
> I had tried to do that - I set the first commit https://github.com/dosbox-staging/dosbox-staging/commit/285350bd4e2ea5ef44f3091ec8afe9cd63f0c2bf to the PDCurses author, with just the files I need from a git clone, did I miss something?

That's definitely it! :+1:, sorry for not seeing that earlier, @kklobe .

**Screenshot:**

Ok - it seems my GitHub web client is in some old state, because even refresh the PR's commit list is still showing me the old commits, with  https://github.com/dosbox-staging/dosbox-staging/commit/285350bd4e2ea5ef44f3091ec8afe9cd63f0c2bf still missing:




**Text form:**

1. [Fix debugger](https://github.com/dosbox-staging/dosbox-staging/pull/1629/commits/b4623bbefbf4105961f6d7150599095a78b5471b) by @[kklobe](https://github.com/dosbox-staging/dosbox-staging/commits?author=kklobe), committed 3 days ago

2. [Add header guard](https://github.com/dosbox-staging/dosbox-staging/pull/1629/commits/e88481418eb84b2a397682a8487dde63af18a1c8) by @[kklobe](https://github.com/dosbox-staging/dosbox-staging/commits?author=kklobe), committed 3 days ago

**Comment by kklobe** [comment]
> > I had tried to do that - I set the first commit [285350b](https://github.com/dosbox-staging/dosbox-staging/commit/285350bd4e2ea5ef44f3091ec8afe9cd63f0c2bf) to the PDCurses author, with just the files I need from a git clone, did I miss something?
> 
> That's definitely it! 👍, sorry for not seeing that earlier, @kklobe .
> 
> Ok - it seems my GitHub web client is in some old state, because refreshing [the PR's commit list]
I did push those changes, to a new branch, https://github.com/dosbox-staging/dosbox-staging/tree/kk/fix-debugger-1

**Comment by kcgen** [comment]
> I did push those changes to a new branch

Ahh, thanks. Yes, let's close this PR and open a new one. (I don't think we can point an existing PR at a New branch). Thanks, @kklobe .

**Pull request closed without merging**
