### PR TITLE
Revert object pool stuff

### PR DESCRIPTION
**Pull request by johnnovak**
# Description

This reverts the object pool stuff introduced by @interloper98 that increases the macOS requirements from 11.x to 14.x.

Sorry man, it's just not worth it. I know you were able to "prove" this improves things marginally, but those were synthetic benchmarks that might never matter under real-world usage. However, increasing the minimum system requirements by two major versions _very much_ affects users.

Full disclosure: I agreed to the inclusion of this complication reluctantly because I never really liked it. Just didn't want to curb your enthusiasm 😄 But it's problematic, so I think it has to go.

So yeah, probably you could make it work without using newer C++ features. But again, I never thought adding this complication was warranted in the first place (I was just like "yeah, whatever 🤷🏻 😄"); it doesn't solve any real-world problem we're experiencing.

## Related issues

See discussion here:
- https://github.com/dosbox-staging/dosbox-staging/issues/4108

# Release notes

N/A (only affects 0.83.x)

# Manual testing

TODO

The change has been manually tested on:

- [ ] Windows
- [ ] macOS
- [ ] Linux

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] my change has been manually tested on Windows, macOS, and Linux.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by kklobe** [comment]
I agree with this whole-heartedly. I've been stymied a couple of times trying to add new C++20 features, but they caused issues with various platforms and compilers, so I understand the enthusiasm to do this. But in this case, it's just not worth it; as @johnnovak mentions, this doesn't appear to be solving any real problems.

**Comment by weirddan455** [comment]
To play devil's advocate, we could just turn this feature off for Mac since it works perfectly fine on Windows and Linux.

I don't understand what this code is doing though so I'm not right person to give an informed decision.  I know the concept of an object pool but this goes over my head.  Maybe give @interloper98 a chance to weigh in on what the benefits of keeping this are?

**Comment by interloper98** [comment]
No big deal. Just ran the heap profiler and saw allocations were in the tens-of-thousands per second (one of them being memory used by the dynamic core) and it was an easy fix.
Profiling dosbox SVN showed it has near zero ongoing heap allocations,  so I was trying to get back to baseline.
Approving.

**Review by interloper98 — APPROVED** [review]

**Comment by interloper98** [comment]
I think what should happen is just more careful use of static vectors; let them allocate up to the edge of what the software uses and then  reusing that memory space through the rest of the runtime period.

**Comment by johnnovak** [comment]
> I think what should happen is just more careful use of static vectors; let them allocate up to the edge of what the software uses and then reuse that memory space through the rest of the runtime period.

Yeah I agree with that. Preallocating even a few megabytes for vectors like that is nothing these days. Doesn't even matter much for mobile phones, lol 😄 

Memory pools can make a difference, but we should always measure total app performance—the fact that 10k allocations happen per second and it's "unpooled" might or might not matter.

This is a good write-up about it (explaing why it _might_ make difference, but why it usually doesn't):
https://stackoverflow.com/a/67629914

**Comment by johnnovak** [comment]
> To play devil's advocate, we could just turn this feature off for Mac since it works perfectly fine on Windows and Linux.

The overarching line of thought here is not adding any complexity where it doesn't make a difference. So why would you do that if it doesn't make a difference? The previous code is simpler. Simpler == better, all other things being equal (or _mostly_ equal, even).

**Pull request merged**
