### PR TITLE
Scan Windows release builds with Windows Defender

### PR DESCRIPTION
**Pull request by kcgen**
Screenshot at 2020-04-29 16-19-25

I found I couldn't capture the scan output though; unfortuantely some powershell commands produce some kind "text overlay" that pops up in the GUI, then disappears when its done.  The best I could do was to dump the status pre-scan, and print the return-code post-scan.

### CODE REVIEW

**Comment by simonsan** [comment]
> I found I couldn't capture the scan output though; unfortuantely some powershell commands produce some kind "text overlay" that pops up in the GUI

Same problem here :-( 

I tried [Invoke-Process](https://adamtheautomator.com/powershell-start-process/) from the powershell gallery as well, but no success. :-/

**Comment by kcgen** [comment]
> you didn't invoke any exe directly ^^

@simonsan ; please help! How can we ensure the scan executes? I'll drop your solution in the commit, if it's easy for you to paste here.  Thank you!

**Comment by simonsan** [comment]
> > you didn't invoke any exe directly ^^
> 
> @simonsan ; please help! How can we ensure the scan executes? I'll drop your solution in the commit, if it's easy for you to paste here. Thank you!

Only sharing ideas:
1. `Update-MpSignature` | Updates the anti-malware definitions on the computer.
2. `Start-MpScan -ScanPath <path> | % { _.$ <do something with each piped values> (foreach) }`
or something like `Get-MpThreat` | Gets the history of threats detected on the computer.

```
Start-MpScan [-ScanPath <string>] [-ScanType {FullScan | QuickScan | CustomScan}] [-CimSession <CimSession[]>]
    [-ThrottleLimit <int>] [-AsJob]  [<CommonParameters>]

<CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https:/go.microsoft.com/fwlink/?LinkID=113216).

or instead of the last step using something like a [out variable](https:/go.microsoft.com/fwlink/?LinkID=113216) and checking with that?

**Comment by kcgen** [comment]
@simonsan ; thanks for the tips. 

> `Update-MpSignature` | Updates the anti-malware definitions on the computer.

Tried that [early on and it tanks](https://github.com/dosbox-staging/dosbox-staging/runs/631183629?check_suite_focus=true
):

Screenshot at 2020-04-29 17-45-45

> CommonParameters

Ahh this helps; will try getting verbose output, and stopping on an error `-Verbose -ErrorAction Stop`.  Hopefully the sample virus triggers it.

**Comment by kcgen** [comment]
My brain is being irreparably damaged through the use of Microsoft's scripting language ...  I will now step away from the keyboard and consume alcohol to mitigate the damage.

Screenshot at 2020-04-29 18-11-52

Screenshot at 2020-04-29 18-12-06

I need to step away from the keyboard.

**Comment by simonsan** [comment]
> My brain is being irreparably damaged through the use of Microsoft's scripting language ... I will now step away from the keyboard and consume alcohol to mitigate the damage.

Enjoy, I know what you're talking about. :-D 
https://github.com/SFTtech/openage/pull/1120/files#diff-11c4cb3c44c86d525a358ca31c77de4eR311

**Comment by kcgen** [comment]
Shutting this approach (using Windows Defender) down. Microsoft's Powershell commands simply do behave as documented nor do they return sane result codes useable by GitHub's workflow to properly indicate success or failure.

For example:

Microsoft says Realtime Scanning can be enabled with this Powershell command: `Set-MpPreference -DisableRealtimeMonitoring $False`

Screenshot at 2020-04-30 11-41-26

Which we attempt to do in the workflow:

Screenshot at 2020-04-30 11-42-48

The command is executed ans returns success to Powershell, allowing the next command (where we query Defender's current status) to be executed:

Screenshot at 2020-04-30 11-43-16

However, lo-and-behold we see that realtime scanning /was not/ enabled! (and yet our call returned success to powershell).  

Because of this blatant disregard for sane behavior, I'm closing down this PR.

**Comment by simonsan** [comment]
Cheers! If this is not insanity `-DisableRealtimeMonitoring $false` what else. 

Stay sane! Cheers.

**Comment by dragonwolf83** [comment]
This is more of an issue with Windows Defender than PowerShell scripting. 

The first issue with `Set-MpPreference -DisableRealtimeMonitoring $false` not working is because  Tamper Protection in Windows Defender is enabled. That prevents any changes from taking affect until you disable Tamper Protection. 

RealTime Monitoring should be enabled by default. I suspect there is a GPO registry key set to force it off. Check the registry to see if this exists:
```PowerShell
Get-Item -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection' 
```

If it does, you can try removing that and restarting Windows Defender (might be impossible with Tamper Protection on).

The second issue is that Windows Defender does not provide any detailed reporting or logs that would be useful for a clean scan. Event log contains info on scan started and finished. There is a larger log in `C:\ProgramData\Microsoft\Windows Defender\Support`. Maybe one of those would be helpful?

If a threat is found, it would be reported and you can check that with `Get-MpThreatDetection`

**Comment by simonsan** [comment]
@kcgen Might be easier to upload that archive to virustotal with https://github.com/darkoperator/Posh-VirusTotal :-D

**Comment by kcgen** [comment]
@dragonwolf83 ; thanks for revealing that there are likely deeper controls at play blocking Defender.  

If we managed to re-enable scanning, would commands like `Get-MpThreatDetection` hand-back correct return codes to GitHub if one or more threats are found?  We need the workflow to fail-hard if a virus is found instead of merrily uploading the package.

After watching Powershell commands return success when the requested action blatantly didn't work, it seems like almost every Powershell command requires some kind of diaper-wrapper to check its output (or resulting "objects"), to achieve sane per-command return-code behavior.

For example, I wouldn't doubt that `Get-MpThreatDetection` returns success no matter what.

So our code would need something like  Get-MpThreatDetection | Look-For-String "some indication a virus was found" | If it's found, some PowerShell call that returns failure/non-zero to the shell ... otherwise some Powershell code that returns success/zero to the shell.

**Comment by dragonwolf83** [comment]
> If we managed to re-enable scanning, would commands like Get-MpThreatDetection hand-back correct return codes to GitHub if one or more threats are found?

It returns no data on success, so you would do this:
```PowerShell
Get-MpThreatDetection -OutVariable threatResults
if( $threatResults ) { Throw 'Found Virus!' }
```

This is common for `Get` commands because returning no data is not really an error, it is it's own state, `$null`. This makes it easier to separate out issues with running a command from getting a result and acting upon that alone.

Looking at MpCmdRun, it gives better output on success. I can't tell if it would give the details on the virus or if you need to run `Get-MpThreatDetection` still to get that info. Either way, according to https://answers.microsoft.com/en-us/protect/forum/mse-protect_scanning/return-codes-for-mpcmdrunexe/622bdc04-d5c2-4a52-a0b1-b2832d10257d, it does error if a virus is found. 

```PowerShell
$ErrorActionPreference = 'Stop'

$dosboxFile = "./dosbox-staging-windows-${{ env.VERSION }}/eicar.com"
Invoke-WebRequest "https://secure.eicar.org/eicar.com" -OutFile $dosboxFile -Verbose
    
# Not using Start-MpScan because it does not provide any useful output on status of scans
& 'C:\Program Files\Windows Defender\MpCmdRun.exe' -Scan -ScanType 3 -File $dosboxFile
if( $LASTEXITCODE -ne 0 ) { Throw "Exit $LASTEXITCODE : Windows Defender found an issue" }
````

I confirmed you don't need to have RealTime Protection enabled to kick off the scan.

**Comment by kcgen** [comment]
@dragonwolf83 , thanks for investigating and the code drop: commit attributed https://github.com/dosbox-staging/dosbox-staging/commit/04df4f06bbbdd2075283f34bffb80cf8e8a1057b

Let's kick these tires again: https://github.com/dosbox-staging/dosbox-staging/runs/635302703?check_suite_focus=true

**Comment by kcgen** [comment]
> @kcgen Might be easier to upload that archive to virustotal with https://github.com/darkoperator/Posh-VirusTotal :-D

I appreciate the sarcasm :laughing:  Some good news too, VirusTotal upload is working nicely with their Go client (branch: https://github.com/dosbox-staging/dosbox-staging/compare/kc/win-av-3?expand=1)

**Comment by kcgen** [comment]
@dragonwolf83 - it worked!  
Screenshot at 2020-04-30 19-18-32

I've added a !fixup to exclude the sample virus, and we'll run with this. 

@dreamer, which do you prefer? 
 - Defender: faster and less code
 - VirusTotal, more code, but gives us visibility into our scan results in (all?) virus packages

Another option is to go with both:
 - Defender on pushes
 - VirusTotal in a daily cron just for master (would need help avoiding duplicating the workflow release YAML code though)

**Comment by dreamer** [comment]
@dragonwolf83 @simonsan Thank you for your help, this turned out great :)

@kcgen I would prefer to go with Microsoft Defender only. We do not download random stuff from the internet during builds (and I will not allow it in PR anyway), so these scans serve only as the second line of protection for libraries and dependencies that already come from trusted sources (vcpkg, brew, apt).

Putting AV scan in cron serves no purpose in my opinion - if some software repository configured/mirrored by GitHub is going to be compromised, we'll know about it anyway from normal work. And there are no build artefacts to publish in AV scan jobs anyway.

Overall great work - I guess it's time to cleanup and put `kc/win-av-scan-1` as a PR? :)

**Pull request closed without merging**
