### PR TITLE
Add note about Inno Setup

### PR DESCRIPTION
**Pull request by keenanweaver**
Adds a note about the Windows installer to the Staging website.

### CODE REVIEW

**Comment by kcgen** [comment]
Suggest:
 - merging the two commits into one,
 - using a complete sentences (to be consistent with the style of the document)
 - wrapping the long markdown line (to be consistent with the style of the document)

**Comment by kcgen** [comment]
Adding @johnnovak for review.

**Comment by kcgen** [comment]
Looks good, @keenanweaver :+1: 

Can you squash the three into one?

**Comment by keenanweaver** [comment]
Please pardon my noobiness. I'll figure it out!

**Comment by johnnovak** [comment]
I saw this got merged in, and I have mixed feelings about it @keenanweaver & @kcgen .

I had a look at that linked doco page that describes the available command line options you can use with the generated InnoSetup installers, but why is this so important that we need to mention it at the top of the download instructions page?

All those options seem to be heavily geared towards sysadmins and power users, but we actually provide the Windows installer to make life easy for the casual user. I think the Venn diagram of someone downloading the Windows installer *and* wanting to launch it from the command line to customise those sysadmin only options via command line flags is awfully thin 😁 Note we also provide the portable ZIP archive; I'd say most power users would go for that option and ignore the Windows installer completely.

To put things in context, I consider myself a power user, and never ever in my 25 years of "Windows career" had I felt the need to explore the command line options for any of the installers I used. Maybe all had some options, but I wouldn't know as I always used the GUI, 100% of the time! 😄

Maybe we could mention this in a subsection further down below, but I question to decision to put this up there to the top, implying this is something important first-time users need to know about.

**Comment by keenanweaver** [comment]
You've found me out; I am a Windows sysadmin :smile:. I've no qualms regarding its position or even its inclusion at all. I just find it to be a useful bit of information to include on the download page. *Someone* out there will wanna know. Maybe just say it's Inno Setup?

**Comment by johnnovak** [comment]
> You've found me out; I am a Windows sysadmin 😄. I've no qualms regarding its position or even its inclusion at all. I just find it to be a useful bit of information to include on the download page. _Someone_ out there will wanna know. Maybe just say it's Inno Setup?

Like I said, I don't mind its inclusion, but I don't think it warrants to be put right to the top. Can you create a new subsection for it above "Older builds" called "Customising install parameters" or something and move it there? Maybe also instead of "For available install parameters" say "For the available command-line install parameters".

**Comment by kcgen** [comment]
Oh, and here I thought it was an addition to the build documentation (for those people creating their own packages).

Agree it makes sense to notch it down a bit, more in the details for those who are looking for automated / silent deploys, etc. 

Now all those sysadmins running puppet and salt can do mass deployments for all their employees. "DOS productivity application". 😅

**Comment by johnnovak** [comment]
> Now all those sysadmins running puppet and salt can do mass deployments for all their employees. "DOS productivity application". 😅

Yeah, like the Boss [Screen](https://www.howtogeek.com/749864/gaming-when-you-should-be-working-the-history-of-the-boss-key/
) in Leisure Suit Larry, for instance. That chart seems business-y enough for me!

image

No such luck in Space Quest III, though!

image

**Pull request closed without merging**
