### PR TITLE
Remove fontstash library

### PR DESCRIPTION
**Pull request by weirddan455**
# Description
This library is unused and unmaintained by upstream.

## Related issues
#2998

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by weirddan455** [comment]
It just occurred to me maybe @johnnovak was planning on using this for his OSD.  It was brought in with commit b204e392685b5f3bb2a0b7bfd9f680a12c3f10ab (committed by @kcgen) around the same time as stb_truetype

I'm just a little confused as I can't tell where the code actually came from.  It's significantly changed from upstream and upstream is also unmaintained since 2019.

If you really want to use the library, I'll close this PR but I'd suggest looking into alternatives.  I believe stb_truetype itself has some support for font atlases.  There's also rtext from the raylib library which is based on stb_truetype.  It's modular so we don't need to bring in the entire raylib dependency:  https://github.com/raysan5/raylib/blob/master/src/rtext.c

**Review by kcgen — APPROVED** [review]
I agree; even if this package is still desirable, it might make more sense to re-assess the state of maintained forks just prior to putting it to use in our repo.

**Comment by weirddan455** [comment]
I'll wait for @johnnovak to see this before merging in case he has any objections.

**Comment by johnnovak** [comment]
Yeah I was planning to use it for my OSD stuff. NanoVG + stb_truetype + fontstash is my "stack" of choice for drawing custom GUIs in my other projects.

Yes, all three are effectively "unmaintained" but it doesn't matter much because they're all very mature and self-contained libraries with no further dependencies. Are they 100% bug-free? Probably not. Have I run into a single bug during my heavy use of these libs? No, not one time.

These are not fast-moving targets like SDL, fonstash in particular doesn't depend on anything, even conceptually only on the concept of UTF-8 glyphs which is set in stone. Personally, I'm fine with it, but also happy to look into alternative implementations. In short, I don't care much either way, I don't think what we choose matters a lot. Probably you'll be able to use the current version of fonstash fine in 2050 too 😎 

That other implementation you linked is 2.1 KLOC, fonstash is 1.7 KLOC. So if you're proposed implementation can be simply plugged in, why not 😄 I'll need to think about this more, but I think in either case my plan was to rewrite fonstash in C++... or maybe just use it from C++. The reasons are a bit complicated, we'll see.

So I guess you can remove it for now if you want, that will force me to re-evaluate things when the time comes.

**Comment by weirddan455** [comment]
@johnnovak  I don't particularly care if this library sits in the tree not doing anything.  At least I know why it's there now.  My main issue is that the code we've pulled in does not match the upstream source (https://github.com/memononen/fontstash).  I assume this came from one of the forks but I don't know which one.

I'm just trying to go through the list in #2998 and verify everything is up to date.  The advantage of removing it would be we don't have to worry about keeping it in sync.  If you want to use it, just pull in a  fresh copy from upstream when it's actually going to be used.

**Comment by johnnovak** [comment]
> @johnnovak I don't particularly care if this library sits in the tree not doing anything. At least I know why it's there now. My main issue is that the code we've pulled in does not match the upstream source (https://github.com/memononen/fontstash). I assume this came from one of the forks but I don't know which one.
> 
> I'm just trying to go through the list in #2998 and verify everything is up to date. The advantage of removing it would be we don't have to worry about keeping it in sync. If you want to use it, just pull in a fresh copy from upstream when it's actually going to be used.

That's fine, I'll re-add this or something else if I need it. Well, you don't need to update it anyway as it's unused 😄 I'm pretty sure I copied it from the VCVRack repo.

**Pull request merged**
