### PR TITLE
Adds full directory logging for every file save/load debugger command

### PR DESCRIPTION
**Pull request by LowLevelMahn**
it sometimes hard to know were the MEMDUMP or INTVEC files getting created, while switching between batch-file or IDE dosbox start

this pull logs (at least for windows/linux) the absolute output path of the files created by some debugger commands 

(i changed only one file, but there are still 22 commits in this pull??)

### CODE REVIEW

**Comment by johnnovak** [comment]
What just happened with the commit log? 😲

**Comment by ThomasEricB** [comment]
Sorry but this PR changes far too little for the 23 commits it has... In fact, there is even an unnecessary commit that only change `tests.vcxproj` just to revert these changes later on. I recommend following @johnnovak 's suggested footsteps to get out of it.

**Comment by LowLevelMahn** [comment]
> Sorry but this PR changes far too little for the 23 commits it has... In fact, there is even an unnecessary commit that only change `tests.vcxproj` just to revert these changes later on. I recommend following @johnnovak 's suggested footsteps to get out of it.

these are all totaly unrelated commits, partialy weeks/month old - i don't know why these become part of the pull
i only changed the debug.cpp

**Comment by dreamer** [comment]
> > Sorry but this PR changes far too little for the 23 commits it has... In fact, there is even an unnecessary commit that only change `tests.vcxproj` just to revert these changes later on. I recommend following @johnnovak 's suggested footsteps to get out of it.
> 
> these are all totaly unrelated commits, partialy weeks/month old - i don't know why these become part of the pull i only changed the debug.cpp

That's because you don't understand the difference between merge and rebase and you kept merging new changes from our `main` branch instead of rebasing your commits on top. Perhaps you used some silly GUI app and it did this for you.

That's ok, you just need some practice to learn Git :)

To recover from this situation I recommend creating a new branch based on the newest version of our `main` branch and cherry-pick exactly the commits you want to submit. If you need help then ping me on Discord.

Please read this: [CONTRIBUTING.md#contributing-code](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#contributing-code)
Especially the section about writing good commit messages.

I have some comments about the code as well, but we'll get to that part only after commit history will look OK.

**Review by dreamer — CHANGES_REQUESTED** [review]
> > Sorry but this PR changes far too little for the 23 commits it has... In fact, there is even an unnecessary commit that only change `tests.vcxproj` just to revert these changes later on. I recommend following @johnnovak 's suggested footsteps to get out of it.
> 
> these are all totaly unrelated commits, partialy weeks/month old - i don't know why these become part of the pull i only changed the debug.cpp

That's because you don't understand the difference between merge and rebase and you kept merging new changes from our `main` branch instead of rebasing your commits on top. Perhaps you used some silly GUI app and it did this for you.

That's ok, you just need some practice to learn Git :smile:.

To recover from this situation I recommend creating a new branch based on the newest version of our `main` branch and cherry-pick exactly the commits you want to submit. If you need help then ping me on Discord.

Please read this: [CONTRIBUTING.md#contributing-code](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#contributing-code)
Especially the section about writing good commit messages.

I have some comments about the code as well, but we'll get to that part only after commit history will look OK.

**Comment by LowLevelMahn** [comment]
> Perhaps you used some silly GUI app and it did this for you.

thats the case - i always merge, never rebase - no problem in business so far :)

**Comment by dreamer** [comment]
> thats the case - i always merge, never rebase - no problem in business so far :)

Your PR won't be merged in this state, sorry. You need to rebase it.

**Comment by johnnovak** [comment]
> > Perhaps you used some silly GUI app and it did this for you.
> 
> thats the case - i always merge, never rebase - no problem in business so far :)

We use a rebase workflow in this project, plain and simple.

**Comment by dreamer** [comment]
Just to be clear: we do sometimes use merge instead of rebasing, but we need a very good reason for doing so (e.g. we merge SVN trunk, or we used merge to incrementally convert the buildsystem from autoconf to Meson). But for normal, everyday improvements - we *very strongly* prefer rebasing.

One of the major reasons for doing so: a clean history, not polluted by spurious merge commits, makes it much easier to run `git bisect`.

**Comment by LowLevelMahn** [comment]
@johnnovak
@dreamer 

Thank you both for clearing that up
i was introduced to git some years ago while working for several companies - all prefered the merge way (and think because the UIs tend to prefere merge before rebase in the defaults)

**Comment by dreamer** [comment]
In my experience companies usually simply don't care about introducing a technical debt (even when they claim otherwise) - a strong technical leadership is necessary to create proper development culture. Top companies usually have very strict rules about this though.

Yes, Git does indeed defaults to using merge, because it was designed for a workflow where PRs are handled by the integrator and each branch represents a separate thread from a mailing list (and merge commits are always created manually by the maintainer, never by machine, [see this](https://public-inbox.org/git/)).

Waiting for revised PR, I think the actual code changes will need only minor revisions :smile:.

**Comment by dreamer** [comment]
> and its default pull behavior is merge - is it dangerous to switch that to rebase? (the current project i am working on (~10 developers) has no preference)

In Git nothing's "dangerous" because you always have this cool command: `git reflog`, which stores the history of where your HEADs were pointing to - this way you can recover from almost any weird situation you might end up with.

As for changing the defaults for your tools - you just need to understand and know what to expect.

When training new people in Git I strongly suggest to not use any GUI and rely on terminal instead - this way it is much harder to make unintended accidental changes. The only graphical tool I recommend is `gitk` (comes preinstalled with Git), to confirm that the history of your branch looks as you intended.

Sorry for wishy-washy response - I simply can't give recommendations for what you should do in other projects :)

**Comment by LowLevelMahn** [comment]
> Sorry for wishy-washy response

way enough repsonse for such a simple pull request :)

**Comment by johnnovak** [comment]
For the record, I know how to use git at a semi-advanced (but far from "pro") level in the _command line_; I'm always confused by the various GUIs, git support in IDEs, so I stay away from them and use the command line 100% of the time. Some GUIs actually _rename_ certain git features, or set certain flags "silently" without telling you, creating quite a bit of confusion. My advice: learn how to use it from the command line, then even if you choose to use a GUI, at least you know what's the "normal" behaviour.

Regarding what companies use, at my last two companies we've used a rebase/fast-forward style PR process, so I haven't done anything else in the past 5-6 years then the rebase workflow. To me it's natural and I strongly prefer it because yeah it keeps the history clean and it's less confusing; PRs are always fast-forwarded on top of branch the change goes into. Plain & simple & clean!

**Comment by ThomasEricB** [comment]
> im using GitExtension as a UI client - sometimes command line

>When training new people in Git I strongly suggest to not use any GUI and rely on terminal instead - this way it is much harder to make unintended accidental changes. The only graphical tool I recommend is gitk (comes preinstalled with Git), to confirm that the history of your branch looks as you intended.

>My advice: learn how to use it from the command line, then even if you choose to use a GUI, at least you know what's the "normal" behaviour.

I'm sorry @dreamer and @johnnovak but I'll have to wholeheartedly disagree with you both. I use Git Extensions as well, as @kcgen can attest (alongside the terminal)! I think Git Extensions excels into explaining and showing to the user what is going on and helps you not make mistakes. It's a very robust GUI. For me it doesn't replace the command line, but rather it helps me to visualize what I am doing. 

@LowLevelMahn I recommend you to read the Git Extensions wiki as it is full of information that is pertinent to learning how to use it optimally

**Pull request closed without merging**
