### PR TITLE
Support for UTF-8 locale

### PR DESCRIPTION
**Pull request by FeralChild64**
From now on, if locale file is named _xx-utf8.lng_, it is considered an UTF-8 locale and handled as such. Legacy _xx.lng_ files are still supported; if both are found, UTF-8 is preferred.

Since probably no current Unicode engine handles all the FreeDOS code pages (and does it well), I had to introduce my own solution. Not all FreeDOS code pages are supported yet, but the common ones already are. To support more, it should be enough to edit `cp_main_definitions.cpp`, and possibly `cp_ascii.cpp`. To see the benefits of the engine, switch the language to Polish (`language=pl` in the configuration file), and try commands:

```
keyb pl 667
keyb pl 668
keyb lv 775
keyb uk 437
```

667 and 668 are mutually incompatible code pages for Polish language. 775 is a Baltic Rim code page - not designed for Polish at all, but by chance it contains all (or almost all) national characters needed. 437 is an US code page, it contains almost no national characters. After each of these commands, you'll see the message is now printed out using the newly set code page; also, for code page 437, we have a reasonable fallback for each glyph.

Screenshot

Currently the conversion is one-way (from UTF-8 to guest side code page), but it should be easy to extend the engine for converting characters the opposite way. Possible future uses of this code I can think of:
- handling national characters in file names, with host OS using UTF-8
- there were some discussions about TTF output
- better handling of physical mouse names returned by ManyMouse library (it returns names in UTF-8)

Note: several files were created using search&replace on data taken from unicode.org - this is all documented inside the files.

### CODE REVIEW

**Comment by kcgen** [comment]
Amazing work, @FeralChild64.  You're moving some mountains here!

> Legacy xx.lng files are still supported; if both are found, UTF-8 is preferred.

> Since probably no current Unicode engine handles all the FreeDOS code pages (and does it well), I had to introduce my own solution. 

I wasn't able to tell if there's still scenarios where only the legacy non-utf8 is useful for us. 

Please feel free to fully drop the old stuff and forge ahead 100%, especially if it eliminates big branches of carrying if/else's throughout the code. 

We're not aware of users with custom / privatr .LNG files (if there are maybe they will raise a ticket and we can help them upgrade).

**Comment by FeralChild64** [comment]
> I wasn't able to tell if there's still scenarios where only the legacy non-utf8 is useful for us.

Right now only about 25% of code pages provided by FreeDOS are supported. I intend to add more, but this is a really boring, time consuming job. Until all of them are supported, it would be, IMHO, better to keep supporting non-UTF-8 files, especially that very little code is needed for this - otherwise someone willing to translate DOSBox Staging to a new language might get into trouble if he is unlucky.

**Comment by kcgen** [comment]
Oh, very good to know! If there's any help the team can help with in converting files - with some tips or before/after comparisons, please put a shout out in the translation ticket.

Or even start a new ticket, and pin it so everyone can see.  I'm positive there are folks can pitch in to accelerate this!

**Comment by FeralChild64** [comment]
@kcgen  Once this is in main, creating a ticket is definitely a good idea.

**Comment by kcgen** [comment]
For all the key-character static arrays, is this something we can store as data resource files instead, and  load on-demand, similar to some of the other resources?

**Comment by FeralChild64** [comment]
> For all the key-character static arrays, is this something we can store as data resource files instead, and load on-demand, similar to some of the other resources?

We could, but what's the point? It's less than 1KB of data per code page (often much less), we would need to have a parser for the file format, and the format should be able to handle things like this:
```C
    // United States
    { 437, { &cp_437 } },

    // Polish, Mazovia encoding, with Euro
    { 667, { &cp_euro_ee, &cp_partial_667, &cp_437 } },

    // Polish, mostly 852 compatible, with Euro
    { 668, { &cp_euro_ee, &cp_partial_668, &cp_437 } },
```

**Comment by kcgen** [comment]
> We could, but what's the point? 

They are N data records of external origin, somewhat similar to the shaders, cpx files, and translations. 

We don't N hardcoded variables for all of these resources - instead load them on the fly, and only if needed, with a single chunk of source code. 

This approach means that we can handle any quantity of these records, and lets users easily contribute /  upload / fix them, similar to these other data resources.

When N data records are injected as hardcoded source, their impact scales: each .cpp has to be compiled, each .cpp is read and parsed by IDEs (on every startup), the strings these data records pollute source searches.  Each record adds to this ongoing load, for each developers, for each build job. Where as when data records are left as data, they don't have this incremental hit on the dev side.

There's also the same tiny but incremental runtime hit to populate all these static structures at runtime. Most users might only use a single one of these records (if that).

**Comment by FeralChild64** [comment]
Let's close this PR, I'll try to create a solution with data in separate files.

BTW, this PR also contains some corrections to Polish translation - fixed two frames, added information about Kashubian (dialect of Polish) codepage. Would it be possible to merge just pl.txt for now?

**Comment by kcgen** [comment]
Apologies for causing any lost work with this; hopefully writing the reader will be lean and can assume a fixed layout (or heck, read binary data straight into structs). 

> BTW, this PR also contains some corrections to Polish translation - fixed two frames, added information about Kashubian (dialect of Polish) codepage.

:👍 I won't touch this branch; hopefully these can be cherry picked I to the new branch. 

> Would it be possible to merge just pl.txt for now?

Please feel free; (I don't know how to do such an operation).

**Comment by FeralChild64** [comment]
Don’t worry, not much will be lost. The biggest challenge is to create a sane file format and definition layout - I’ll probably extend a little the one unicode.org uses.

OK, I’ll extract the PL translation fixes to a separate branch later.

**Pull request closed without merging**
