### PR TITLE
Use `DOSBox Staging.app` on macOS per Human Interface Guidelines

### LINKED ISSUE #1803: Application name in macOS should be DOSBox Staging.app
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

Mac OS

### If Other OS, please describe

_No response_

### Is your feature request related to a problem? Please describe.

Application name in macOS is currently dosbox-staging.app. This isn't inline with the macOS Human Interface Guidelines which recommend natural application names.

### Describe the solution you'd like

Application package should be renamed to DOSBox Staging.app. Here's a renamed example with the benefits of inheriting the name in the Dock and being the same as applications name in about box and menu bar for consistency:

Screenshot 2022-07-21 at 19 02 43
Screenshot 2022-07-21 at 19 04 49
Screenshot 2022-07-21 at 23 33 46
Screenshot 2022-07-21 at 23 34 01

### Describe alternatives you've considered

No alternatives has been considered.

### Add any other context or screenshots about the feature request here.

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by kcgen**
Fixes #1803.

Needs testing to confirm we're handling the space properly.

Thanks to @Grounded0 for reporting this.

### CODE REVIEW

**Review by Burrito78 — APPROVED** [review]
It's working perfectly on macOS 11.6.8 Big Sur.
Screenshot 2022-08-23 at 23 47 43
Screenshot 2022-08-23 at 23 50 46

**Comment by brandonrobertz** [comment]
I'm using the `macos.yml` action as a guide for how to do this, but the build fails on my system at the `create-package.sh` step.

```
$ ./scripts/create-package.sh -p macos -v $(git describe --abbrev=5) -f "$(pwd)" "$(pwd)"                                                                                                                                                                       
+ install_doc                                                                                                                                                                                                                                                   
+ case $platform in                                                                                                                                                                                                                                             
+ install_file docs/README.template '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/README'                                                                                                                                   
+ src=docs/README.template                                                                                                                                                                                                                                      
+ dest='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/README'                                                                                                                                                                
+ case $platform in                                                                                                                                                                                                                                             
+ create_parent_dir '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/README'                                                                                                                                                   
+ path='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/README'                                                                                                                                                                
++ dirname '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/README'                                                                                                                                                            
+ dir='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport'                                                                                                                                                                        
+ '[' '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport' '!=' . ']'                                                                                                                                                             
+ case $platform in                                                                                                                                                                                                                                             
+ install -d '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/'                                                                                                                                                                
+ install -m 644 docs/README.template '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/README'                                                                                                                                 
+ install_file COPYING '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/COPYING'                                                                                                                                               
+ src=COPYING                                                                                                                                                                                                                                                   
+ dest='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/COPYING'                                                                                                                                                               
+ case $platform in                                                                                                                                                                                                                                             
+ create_parent_dir '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/COPYING'                                                                                                                                                  
+ path='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/COPYING'                                                                                                                                                               
++ dirname '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/COPYING'                                                                                                                                                           
+ dir='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport'                                                                                                                                                                        
+ '[' '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport' '!=' . ']'                                                                                                                                                             
+ case $platform in                                                                                                                                                                                                                                             
+ install -d '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/'                                                                                                                                                                
+ install -m 644 COPYING '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/COPYING'                                                                                                                                             
+ install_file README '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/manual.txt'                                                                                                                                             
+ src=README                                                                                                                                                                                                                                                    
+ dest='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/manual.txt'                                                                                                                                                            
+ case $platform in                                                                                                                                                                                                                                             
+ create_parent_dir '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/manual.txt'                                                                                                                                               
+ path='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/manual.txt'                                                                                                                                                            
++ dirname '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/manual.txt'                                                                                                                                                        
+ dir='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport'                                                                                                                                                                        
+ '[' '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport' '!=' . ']'                                                                                                                                                             
+ case $platform in                                                                                                                                                                                                                                             
+ install -d '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/'                                                                                                                                                                
+ install -m 644 README '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/manual.txt'                                                                                                                                           
+ install_file docs/README.video '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/video.txt'  
+ src=docs/README.video                                                                                                                                                                                                                                         
+ dest='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/video.txt'                                                                                                                                                             
+ case $platform in                                                                                                                                                                                                                                             
+ create_parent_dir '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/video.txt'                                                                                                                                                
+ path='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/video.txt'                                                                                                                                                             
++ dirname '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/video.txt'                                                                                                                                                         
+ dir='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport'                                                                                                                                                                        
+ '[' '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport' '!=' . ']'                                                                                                                                                             
+ case $platform in                                                                                                                                                                                                                                             
+ install -d '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/'                                                                                                                                                                
+ install -m 644 docs/README.video '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/video.txt'                                                                                                                                 
+ readme_tmpl='/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/README'                                                                                                                                                         
+ '[' -n 522361b41 ']'                                                                                                                                                                                                                                          
+ sed -i -e 's|%GIT_COMMIT%|522361b41|' '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/README'
+ '[' -n kc/rename-macos-app-1 ']'                              
+ sed -i -e 's|%GIT_BRANCH%|kc/rename-macos-app-1|' '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/README'
+ '[' -n dosbox-staging ']'                                     
+ sed -i -e 's|%GITHUB_REPO%|dosbox-staging|' '/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/SharedSupport/README'
+ install_resources                                             
+ case "$platform" in                                           
+ local src_dir=/Users/brandon/src/dosbox-staging/../Resources  
+ local 'dest_dir=/Users/brandon/src/dosbox-staging/dist/DOSBox Staging.app/Contents/Resources'                                 
+ find /Users/brandon/src/dosbox-staging/../Resources -type f   
+ IFS=                                                          
+ read -r src                                                   
find: /Users/brandon/src/dosbox-staging/../Resources: No such file or directory                                                 
+ case $platform in                                             
+ pkg_macos                                                     
+ for arch in x86_64 arm64                                      
+ echo 'Checking shared object dependencies for x86_64:'        
Checking shared object dependencies for x86_64:                 
+ otool -L /Users/brandon/src/dosbox-staging/dosbox-x86_64/dosbox                                                               
/Users/brandon/src/dosbox-staging/dosbox-x86_64/dosbox:         
        /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (compatibility version 17.0.0, current version 17.0.0)                      
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1856.105.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)                                      
        /usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 11.0.0, current version 11.0.0)                       
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)                                         
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)                                          
        /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1856.105.0)
        /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)      
        /usr/local/opt/sdl2_net/lib/libSDL2_net-2.0.0.dylib (compatibility version 1.0.0, current version 1.1.0)                
        /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 1000.0.0)
        /System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI (compatibility version 1.0.0, current version 69.0.0) 
        /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1141.1.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)                                         
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)                                         
+ python3 scripts/verify-macos-dylibs.py /Users/brandon/src/dosbox-staging/dosbox-x86_64/dosbox                                 
Problematic runtime dependency: '/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (compatibility version 17.0.0, current version 17.0.0)'
Is it installed by default on macOS system? 
```

**Comment by kcgen** [comment]
When packaging, we need to make sure that the executable only depends on system libraries that any Apple user will have, as opposed to brew-provided libs, so that's what it's complaintling about.  

If you can try a clean setup using SDL statically:

```shell
meson setup -Dwrap_mode=forcefallback \
-Dtry_static_libs=sdl2,sdl2_net build

meson compile -C build
```

Hopefully the packaging step will pass and the binary won't depend on any /use/local dynlibs.

**Review by johnnovak — APPROVED** [review]
Nice @kcgen 👍🏻

**Pull request merged**
