### PR TITLE
Use std math functions in `compressor.cpp`

### PR DESCRIPTION
**Pull request by johnnovak**
# Description

Standard C functions are best to be avoided if we don't specifically need exact conformance with what the C standard mandates. In particular, the `std::min` and `std::max` functions are potentially more performant as they can be compiled to branchless code as opposed to `fmin/fmax`.

Key point from this [extremely informative post](https://stackoverflow.com/a/40870480):

> In C++, use std::min and std::max, which are defined in terms of > or <, and don't have the same requirements on NaN behaviour that fmin and fmax do. Avoid [fmin and fmax](http://en.cppreference.com/w/c/numeric/math/fmin) for performance unless you need their NaN behaviour.

# Manual testing

Space Quest III still works and there is sound 😎 🤘🏻 

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [ ] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Review by kcgen — COMMENTED** [review]
These are probably doing silent upgrades to `double`s; should be float-equivalent for each (std::expf, etc)

Edit: ignore that; these look like template calls in C++!

I tested with `meson setup -Dcpp_args='-Wdouble-promotion' build`

**Review by kcgen — APPROVED** [review]
:+1: nice cleanup!

**Comment by johnnovak** [comment]
> These are probably doing silent upgrades to `double`s; should be float-equivalent for each (std::expf, etc)

I don't think that's the case. `std::min/std::max` are templated, and `std::exp`, `std::sqrt` etc. all have overloaded float, double, and long double variants. E.g.:

image


image

Source:

- https://en.cppreference.com/w/cpp/algorithm/min
- https://en.cppreference.com/w/cpp/numeric/math/sqrt
- https://en.cppreference.com/w/cpp/numeric/math/exp
- https://en.cppreference.com/w/cpp/numeric/math/pow

**Comment by johnnovak** [comment]
> Edit: ignore that; these look like template calls in C++!
> I tested with meson setup -Dcpp_args='-Wdouble-promotion' build

Ah, thanks for that! Like I'm always saying: trust but verify 😏

**Pull request merged**
