### PR TITLE
Update Dutch (nl) translation

### PR DESCRIPTION
**Pull request by rderooy**
Based on the current en.txt file.

### CODE REVIEW

**Review by johnnovak — APPROVED** [review]
Nice one @rderooy 🎉

**Comment by Kappa971** [comment]
> Based on the current en.txt file.

This [en.txt](https://github.com/dosbox-staging/dosbox-staging/files/11929531/en.txt) file was taken from the latest main branch build, I think there are many more additions than your en.txt file

**Comment by rderooy** [comment]
> > Based on the current en.txt file.
> 
> This [en.txt](https://github.com/dosbox-staging/dosbox-staging/files/11929531/en.txt) file was taken from the latest main branch build, I think there are many more additions than your en.txt file

Indeed, I noticed it is rather out-of-date. I just pushed additional updates.

**Review by FeralChild64 — APPROVED** [review]

**Comment by FeralChild64** [comment]
@rderoy I never use the `en.txt` from the repository. I juust set language to English, start emulator, and type `config -wl en.txt` - and I have the current language file. To determine what has changed between two `en.txt` files I use a _Kompare_ tool; for Windows there is a free _WinMerge_.

**Comment by rderooy** [comment]
@FeralChild64 thanks for the hint on generating an updated en.txt file. For comparing them, I use 'meld' myself.
http://meldmerge.org/

**Comment by johnnovak** [comment]
> @rderoy I never use the `en.txt` from the repository. I juust set language to English, start emulator, and type `config -wl en.txt` - and I have the current language file. To determine what has changed between two `en.txt` files I use a _Kompare_ tool; for Windows there is a free _WinMerge_.

It would be good to start a how-to documentation file in the repo with such tips and instructions. The whole thing is still a bit of a mystery to me.

**Comment by johnnovak** [comment]
Can we merge this @rderooy ?

**Comment by rderooy** [comment]
Yes. There are some updates I need to do for the just merged config changes, but this can be merged in the meantime. Or you can let it sit and I will update it with those changes in the next days.

**Comment by johnnovak** [comment]
Thanks for confirming @rderooy , merging then! 🎉

**Pull request merged**
