### PR TITLE
Update string_utils to C++20

### PR DESCRIPTION
**Pull request by japsmits**
# Description

Update string_utils to use C++20 constructs. Replace the starts_with and end_with functions with calls to their std::string and std::string_view counterparts.

Remove the unused (and buggy) replace() method.

Add unit tests to ensure the changed code still works.

## Related issues

#1314 

# Manual testing

Updated unit tests to include tests of the changed code.

# Checklist

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [ ] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [x] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by japsmits** [comment]
Apparently replace() is used, but not for a Windows build. But it's still buggy since it returns the original string without any replacements. I'll fix the function and add a unit test for it.

**Comment by japsmits** [comment]
Apparently Debian 10 doesn't fully support C++20 yet, since std::string::starts_with and ::ends_with are unavailable. This more-or-less reduces this PR to a bugfix (which is also useful).

Question, @johnnovak: should I abandon this pull-request and wait for better times, or is this the time to drop support for Debian 10?

**Comment by FeralChild64** [comment]
We have discussed on the Discord few days ago regarding Debian 10 - it's getting EOL very soon, we should drop it for the next major release.

**Comment by japsmits** [comment]
In that case, I'll create a branch that fixes the bug in replace() and add the unit-tests. The rest can come when all compilers and C++ libraries support C++20.

**Comment by johnnovak** [comment]
> In that case, I'll create a branch that fixes the bug in replace() and add the unit-tests. The rest can come when all compilers and C++ libraries support C++20.

Thanks @japsmits. Yes, as @FeralChild64 mentioned, we decided to drop Debian 10 support. I will remove it from CI shortly.

And yes, in general we're limited by the C++20 feature set all our target compilers support. It's not so easy to clearly define that, so we decided to let the CI workflows "discover" that common subset for us as we go.

**Pull request closed without merging**
