### PR TITLE
Remove obsolete Intel iGPU workaround

### PR DESCRIPTION
**Pull request by NicknineTheEagle**
# Description

https://github.com/dosbox-staging/dosbox-staging/blob/c04107d084c1f4f51919a31ee1b68f59fde0d437/src/gui/sdlmain.cpp#L1348-L1361
This workaround for Intel iGPUs was added a few years back after I reported an issue where Dosbox OpenGL output was dark on 10th-gen Intel iGPU. Recently, I have re-tested OpenGL renderer without this workaround on 11th-gen Intel with the latest graphics driver and the issue was not reproduced. This means that this workaround is possibly obsolete but we need someone with 6th-gen to 10th-gen Intel to confirm this.

## Related issues

https://github.com/dosbox-staging/dosbox-staging/pull/1829

# Manual testing

Tested on 11th-gen Intel iGPU with 32.0.101.6078 graphics driver:
https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

Need someone with 6th-gen to 10th-gen Intel iGPU to test OpenGL renderer in PR build and see if it appears correctly. Make sure you have the latest graphics driver:
https://www.intel.com/content/www/us/en/download/776137/intel-7th-10th-gen-processor-graphics-windows.html

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [ ] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] provided the release notes draft (for significant user-facing changes).
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by NicknineTheEagle** [comment]
> On i7-8500Y I was getting [this warning](https://github.com/dosbox-staging/dosbox-staging/pull/3939#issuecomment-2363296056) and with this PR I don't get the warning anymore.
> 
> @NicknineTheEagle, how to check for "OpenGL output was dark"? What I saw so far looks OK to me, but I'm not sure if some specific graphics mode/setting is required...

Try switching to `output = texture`, if it looks same then you're good.

**Comment by johnnovak** [comment]
@Torinde Thanks, can you post the `output = opengl` image again when you also set `glshader = sharp`?

**Comment by interloper98** [comment]
@NicknineTheEagle , when I added the ARM64 target, vcpkg failed to build Tracy's dependencies because Tracy at the time didn't support ARM.

So I had to exclude it from the `vcpkg.json` file using this:
```json
    {
      "name": "tracy",
      "platform": "!(windows & arm64)"
    },
```

If you want to try enabling it again, replace that snippet with just `tracy,` to make it a "full triplet" like the other deps.

(I'm not sure it'll work though.. it looks like Tracy still doesn't support ARM here https://vcpkg.io/en/package/tracy. But maybe ARM64 is separate from ARM?)

Worth a try, anyway!

**Comment by NicknineTheEagle** [comment]
> @NicknineTheEagle , when I added the ARM64 target, vcpkg failed to build Tracy's dependencies because Tracy at the time didn't support ARM.
> 
> So I had to exclude it from the `vcpkg.json` file using this:
> 
> ```json
>     {
>       "name": "tracy",
>       "platform": "!(windows & arm64)"
>     },
> ```
> 
> If you want to try enabling it again, replace that snippet with just `tracy,` to make it a "full triplet" like the other deps.
> 
> (I'm not sure it'll work though.. it looks like Tracy still doesn't support ARM here https://vcpkg.io/en/package/tracy. But maybe ARM64 is separate from ARM?)
> 
> Worth a try, anyway!

Those snippets get automatically enabled by VS. I've pushed this change to that VS would stop constantly re-saving sln file.

**Comment by NicknineTheEagle** [comment]
> > OPENGL: Vendor: Intel
> > OPENGL: Version: 4.6.0 - Build 26.20.100.7926
> > OPENGL: GLSL version: 4.60 - Build 26.20.100.7926
> > OPENGL: NPOT textures supported

That is a very old driver, you should consider upgrading (see OP for the link). It's probably whatever is currently delivered by Windows Update in which case you'll also have to disable Windows Update driver downloads cause it'll infuriatingly replace newer versions with whatever ancient version it has: https://www.dell.com/support/kbdoc/en-us/000194492/how-to-stop-windows-updates-from-downloading-and-installing

**Comment by johnnovak** [comment]
Thanks @Torinde. The results look fine to me so far, so this is looking good.

It would be worthwhile to test again with the _actual_ latest drivers as @NicknineTheEagle suggested, and if we're getting the same picture with `glshader = sharp` and `glshader = nearest`, it's good to go 🚀

**Comment by johnnovak** [comment]
> I can update the driver on that PC, but not right now. If the Windows Update (old) driver is OK, most probably Intel latest will also be OK...
> 
> Isn't it more interesting to check if the problem is gone on a PC/driver that _had_ the problem in the past?
> 
> Later I can try on an 4th gen GMA.

Fair point, it's unlikely the problem is coming back in a more recent driver. I'm ok to merge this as-is and release in 0.82.0 if @NicknineTheEagle agrees.

**Comment by NicknineTheEagle** [comment]
> > I can update the driver on that PC, but not right now. If the Windows Update (old) driver is OK, most probably Intel latest will also be OK...
> > Isn't it more interesting to check if the problem is gone on a PC/driver that _had_ the problem in the past?
> > Later I can try on an 4th gen GMA.
> 
> Fair point, it's unlikely the problem is coming back in a more recent driver. I'm ok to merge this as-is and release in 0.82.0 if @NicknineTheEagle agrees.

I'm not sure, I'd rather cover all bases. Plus power users are more likely to stay on the latest graphics driver so that's worth checking, in my opinion.

**Comment by NicknineTheEagle** [comment]
No, that is a different issue. When I was getting the issue, there were no errors in log and the output was still visible but darkened.

**Comment by johnnovak** [comment]
> I'm not sure, I'd rather cover all bases. Plus power users are more likely to stay on the latest graphics driver so that's worth checking, in my opinion.

Ok, there's no need to rush.

**Comment by martyMcfly7** [comment]
Tested on 10th-gen Intel iGPU with 31.0.101.2130 (latest) graphics driver

> 2024-10-10 22:24:17.319 | OPENGL: Vendor: Intel
> 2024-10-10 22:24:17.320 | OPENGL: Version: 4.6.0 - Build 31.0.101.2130
> 2024-10-10 22:24:17.320 | OPENGL: GLSL version: 4.60 - Build 31.0.101.2130
> 2024-10-10 22:24:17.320 | OPENGL: NPOT textures supported

texture
texture

opengl sharp
opengl sharp

opengl nearest
opengl nearest

**Comment by johnnovak** [comment]
Thanks @martyMcfly7 , much appreciated ❤️ 

@NicknineTheEagle Is there anything else to confirm on this?

**Comment by NicknineTheEagle** [comment]
> Thanks @martyMcfly7 , much appreciated ❤️ 
> 
> @NicknineTheEagle Is there anything else to confirm on this?


Nope, we're good to go.

**Review by johnnovak — APPROVED** [review]
Thanks for the follow-up on this @NicknineTheEagle 🎖️

**Comment by interloper98** [comment]
Just saw this come up in a search for the 0.82 release:

> _"Программа сама подцепила файл настройки прошлой версии эмулятора, вот только изображение было какое-то тусклое. Даже очень."_

I'm using Firefox built-in translate and it says: 

"The program itself picked up the settings file of the previous version of the emulator, but the image was somehow dim. Even very much so."

https://www.emu-land.net/news/dosbox_staging_v0820

Made me think of this PR where @NicknineTheEagle mentions the original fix was for a dark image.  Sounds like this user is getting affected by it (or the translation is wrong?)

**Comment by NicknineTheEagle** [comment]
Sus. I'll ask more about it.

**Pull request merged**
