### PR TITLE
Check if hardware cursor is actually being enabled or disabled before setting VGA_LineDraw

### LINKED ISSUE #3723: Screen corruption in 0.81.0 and 0.81.1 when exiting "Teddybear's Revenge" demo by Eclipse
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

_No response_

### What Operating System are you using?

Windows 10

### If Other OS, please describe

_No response_

### Relevant hardware info

i7 7700K, 32GB RAM, GTX 1070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When demo ends or user quits, screen is corrupted as shown in the following screenshot:

image0001

Other machine= settings are not affected.

This also occurs with 0.81.0, but not on 0.80.1 nor 0.80.0.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run demo
2. Wait for demo to end or press ESC
3.

### Download URL of affected game or software

https://files.scene.org/get/parties/1996/saturne96a/in64/e_teddy2.zip

### Your configuration

```ini
[dosbox]
machine=svga_s3

[autoexec]
mount c f:\emus\dosbox\c -t dir
c:
cd e_teddy2
teddy.exe
```

### Provide a Log

_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

### PR DESCRIPTION
**Pull request by weirddan455**
# Description

This affects writes to the hardware cursor register of the S3 SVGA card. Previous, when this register was written to, it would always call VGA_ActivateHardwareCursor(). This function sets the VGA_LineDraw function pointer but it was only intended to be called with certain VGA modes.

This fixes display corruption on exit from the "Teddy's Revenge" demo. The demo calls INT10_VideoState_Restore after switching to text mode. This restores the hardware cursor register (which was never enabled to begin with).

## Related issues

Fixes #3723

# Manual testing

The demo exits cleanly back to text mode now with default settings.

# Checklist

_Please tick the items as you have addressed them. Don't remove items; leave the ones that are not applicable unchecked._

I have:

- [x] followed the project's [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
- [x] performed a self-review of my code.
- [x] commented on the particularly hard-to-understand areas of my code.
- [x] split my work into well-defined, bisectable commits, and I [named my commits well](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages).
- [x] applied the appropriate labels (bug, enhancement, refactoring, documentation, etc.)
- [x] [checked](https://github.com/dosbox-staging/dosbox-staging/blob/main/scripts/compile_commits.sh) that all my commits can be built.
- [ ] confirmed that my code does not cause performance regressions (e.g., by running the Quake benchmark).
- [ ] added unit tests where applicable to prove the correctness of my code and to avoid future regressions.
- [ ] made corresponding changes to the documentation or the website according to the [documentation guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md).
- [ ] [locally verified](https://github.com/dosbox-staging/dosbox-staging/blob/main/DOCUMENTATION.md#previewing-documentation-changes-locally) my website or documentation changes.

### CODE REVIEW

**Comment by johnnovak** [comment]
Very nice surgical fix @weirddan455 🏅 

If you have capacity, would you be able to run some of the video tests I documented here?

https://github.com/dosbox-staging/dosbox-staging/wiki/Video-emulation-tests

If you document which tests you've run in a comment, I will run as much of the rest as I can.

One important test case I haven't documented on that page yet is running Win3.x in 256 colour, high colour, and true colour modes, and confirming the cursor works and there is no display corruption. AFAIK, the hardware cursor is only used by the Windows drivers.

**Comment by weirddan455** [comment]
Yeah I can do some tests later.  I think the only possible regressions could be games/programs that use hardware cursor.  I'll test Windows 3.1.  Not sure if I have the right drivers for hardware cursor but I'll look into later.

**Comment by johnnovak** [comment]
> Yeah I can do some tests later. I think the only possible regressions could be games/programs that use hardware cursor. I'll test Windows 3.1. Not sure if I have the right drivers for hardware cursor but I'll look into it later.

Okay, my Win 3.x setup guide & images are coming, I just got sidetracked, as always. Getting back to it tomorrow, probably.

**Comment by johnnovak** [comment]
> I've seen the [graphical/host cursor in DOS mode](https://github.com/joncampbell123/dosbox-x/issues/3384#issuecomment-1872487713) - when using vbmouse.exe - 'unnatural' for DOS, but it adds to the "seamless" feeling when using DOSbox in a window and using it along other host OS programs.
> 
> So, I hope that still works with the above changes (I haven't tested that yet).

That's a totally different thing, Torinde, and this change has no connection to it AFAIK. This is about hardware cursor drawing support on the S3 SVGA card.

**Review by johnnovak — APPROVED** [review]
Win3.x works, Myst works, checked a few demos and those work too.

Nice work man, ship it 😎

**Pull request merged**
