### PR TITLE
Disambiguate the CONFIG_ROMDIR versus its ROM files

### PR DESCRIPTION
**Pull request by kcgen**
@IlyaIndigo, can you comment on this new wording?

(Follow up from https://github.com/dosbox-staging/dosbox-staging/issues/884#issuecomment-786744327)

### CODE REVIEW

**Comment by IlyaIndigo** [comment]
I translated it this way.
```
:CONFIG_ROMDIR
The directory containing the required MT-32 and/or CM-32L ROMs,
which must be named only in this way and only in capital letters:
  MT32_CONTROL.ROM or CM32L_CONTROL.ROM - ROM file management.
  MT32_PCM.ROM or CM32L_PCM.ROM - PCM ROM files.
The directory can be absolute or relative, or be empty,
to use the 'mt32-roms' subdirectory in the configuration directory
DOSBox, followed by a check of other locations in the system.
```
If everywhere in the configuration directories are called directories and not paths, it should be that way everywhere. This is even correct, you just need to write the right sentence and also remember the notion of subdirectories when it comes to nesting.
But I think it is necessary to mention and emphasize that files should be strictly named only as such and in uppercase.

**Comment by kcgen** [comment]
> The directory containing the required MT-32 and/or CM-32L ROMs,
which must be named only in this way and only in capital letters:
  MT32_CONTROL.ROM or CM32L_CONTROL.ROM - ROM file management.
  MT32_PCM.ROM or CM32L_PCM.ROM - PCM ROM files.

The above allows for an ambiguous combination of ROM files. To fix that, they need to be tied together in pairs in the requirement wording and in the file options.  I've taken your wording plus the pair-wise wording. 

What do you think?

``` text
The directory containing one or both pairs of MT-32 and/or CM-32L ROMs files.
The files must be named in capitals, exactly as follows:
  - MT-32 ROM pair: MT32_CONTROL.ROM and MT32_PCM.ROM
  - CM-32L ROM pair: CM32L_CONTROL.ROM and CM32L_PCM.ROM
```

**Comment by IlyaIndigo** [comment]
@kcgen  I agree with you. Wonderful! :-)

**Review by dreamer — APPROVED** [review]

**Review by dreamer — COMMENTED** [review]
Argh; I made a mistake, I shouldnt've merged this in.

@kcgen - there are no changes to the cpp files in this PR. Next time we'll add any new translation string in code, changes in English translation files in here will be automatically reverted.

**Comment by kcgen** [comment]
> Argh; I made a mistake, I shouldnt've merged this in.

Sorry - I also forgot to update the source. Branch `kc/reword-romdir-2` brings that in-line with these text files.

> Next time we'll add any new translation string in code, changes in English translation files in here will be automatically reverted.

Ok - good to know.  I guess that's your translation tool working behind the scenes? It takes the corresponding  description from the sources and overwrites it in these translation files? (until someone provides a translation, and then it's not overwritten?)

**Comment by dreamer** [comment]
> Ok - good to know. I guess that's your translation tool working behind the scenes? It takes the corresponding description from the sources and overwrites it in these translation files? (until someone provides a translation, and then it's not overwritten?)

There is nothing behind the scenes :) see script `contrib/translations/update-en.sh`.

**Comment by kcgen** [comment]
Thanks; I wasn't aware of this!

**Comment by dreamer** [comment]
Yeah, this is very confusing. For english translation the flow is:

- make change in .cpp file -> use `config -wl` to write a file encoded in codepage 437 -> use iconv to convert file to utf-8

For all other languages it's

- (once) start new translation file based on the newest version of English utf-8 file
- translate utf-8 file only
- use iconv to encode from utf-8 to all necessary old DOS encodings

Old translation system is terrible…

**Pull request merged**
