### PR TITLE
Add state-tracking for the GUS DMA terminal count status

### PR DESCRIPTION
**Pull request by kcgen**
**Background context:** when the number of remaining DMA transfers reaches zero, it's said to have reached the _terminal count_.

Previously, the DMA terminal count was only evaluated as-needed to halt the active DMA transfer, and its state was not tracked. 

**jmarsh** of vogons.org discovered the need to both store the terminal count state and allow it to be queried in the response register during DRAM DMA Control Register Read calls, [as later documented](https://github.com/joncampbell123/dosbox-x/issues/1961#issuecomment-714591841) by @joncampbell123 in subsection 2.6.1.1 of:

http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Sound%20and%20Music/Gravis\/Ultrasound/UltraSound%20Lowlevel%20ToolKit%20%281994%2d12%2d21%29%20v2%2e22%2epdf

... which shows bit 6 holding the DMA terminal count status:

doc

Although DOSBox Staging's prior implementation worked (as it was derived from DOSBox-X's implementation), @joncampbell123 explained that the X implementation worked by setting bit 6 positive for _any_ pending IRQ, thus perhaps unnecessarily starting a DMA transfer, but nonetheless catching all cases were it was actually needed.  Therefore, this change more accurately represents GUS DMA state as expected by the running DOS software.

**Credits:**

1. This fix was discovered and authored by jmarsh of the vogon.org forums and added to DOSBox in SVN commit 4387.

2. It was further documented and adapted by @joncampbell123 for DOSBox-X, including the change to retain the terminal count status during DMA Control Register Writes, as this bit would normally not exist and thus not be overwritten in hardware.

Thank you **jmarsh** and @joncampbell123.

### CODE REVIEW

**Comment by kcgen** [comment]
Tested working with the following regression test:

``` text
gus_regression_tests
├── mods_demos
│   ├── capamod
│   └── second_reality
├── native
│   ├── acid_tetris
│   ├── alien_incident
│   ├── archon_ultra
│   ├── axia
│   ├── crusader_no_regret
│   ├── death_rally
│   ├── epic_pinball
│   ├── extreme_pinball
│   ├── flying_tigers_2
│   ├── future_dimensions
│   ├── in_pursuit
│   ├── interpose
│   ├── iron_seed
│   ├── jazz_jackrabbit_holiday_hare
│   ├── line_war_2
│   ├── one_must_fall_2097
│   ├── pinball_dreams
│   ├── pinball_dreams_2
│   ├── pinball_world
│   ├── psycho_pinball
│   ├── quake
│   ├── rayman
│   ├── silverball
│   ├── star_control_2
│   ├── star_gunner
│   ├── super_frog
│   ├── super_stardust
│   ├── the_horde
│   ├── time_commando
│   ├── turrican
│   ├── vanguard
│   ├── xixit
│   └── zone_66
└── wavetable
    ├── blood
    ├── duke_3d_atomic
    ├── heretic
    ├── hocus_pocus
    ├── redneck_rampage
    ├── rise_of_the_triad
    └── shadow_warrior
```

**Review by dreamer — APPROVED** [review]
Besides broken URL in commit message, there's nothing more to add :)

@kcgen After merging this PR we can safely revert eaab880d3831b0600e1468de5ee617bc184bda11 before merging svn/trunk - right?

**Comment by dreamer** [comment]
I edited the commit message and merged as: fcae63cc293358bbab01e6d8e9b567ccda67e505

@kcgen Thanks! 

(I still would like an answer what to do with eaab880)

**Comment by kcgen** [comment]
Thanks for the url correction @dreamer. I wrapped it using back-slashes as I know we're try to hold to a line-length < 80 for comments.  Maybe for URLs we should allow any length?

> After merging this PR we can safely revert eaab880 before merging svn/trunk - right?

This PR effectively merges (or _adapts_ is probably a better way of saying it) as much as we want to use from https://github.com/dosbox-staging/dosbox-staging/commit/eaab880d3831b0600e1468de5ee617bc184bda11...

But I'm not sure how that plays into your workflow regarding merging svn/trunk commits to master. Maybe you still want to merge-and-revert just to create the linkage from trunk to master, indicating its been processed?

**Comment by dreamer** [comment]
> Maybe for URLs we should allow any length?

Functional requirements are more important than stylistic ones, so yes :) This URL was particularly lenghty, but I included it anyway (breaking 72-column rule for message descriptions).

> (…) but I'm not sure how that plays into your workflow regarding merging svn/trunk commits to master. Maybe you still want to merge-and-revert just to create the linkage from trunk to master, indicating its been processed?

I will do the same as with previous cases when we wanted to avoid something from SVN: revert on temporary branch and merge that - this way no risky conflict resolution is necessary; thanks!

**Comment by kcgen** [comment]
Sounds good; and thanks for the explanation :-)

**Pull request closed without merging**
