### PR TITLE
Remove `magic_enum` due to cons outweighing pros

### PR DESCRIPTION
**Pull request by kcgen**
Although **magic_enum** does provide elegant reflective `enum` support that avoids both the programming burden of writing string-to-enum conversion routines (and vice-versa) as well as the runtime cost of evaluating those string comparisons (yes: magic_enum makes those conversions compile-time `constexpr`s), it turns out it only does so with `enum` values between -128 and 127.

Additional code changes are needed to expand this range up to 16-bits, either in general or on an enum-specific basis. To expand the range, a macro generates 65k `constexpr` cases which the compiler then has to dissolve back down, adding compile time burden.

`enum` values beyond 16-bit are not supported by magic_enum, probably because it would require the generation of 2^32 `constexpr` cases, producing an insurmountable compile-time burden.

Our use of `enum` goes beyond the prosaic: we use values matching specific DOS constants that can range from single bits up to full integers. So unfortunately, it turns out the use-case for magic_enum is significantly narrowed, and even worse: inconsistently available as a language feature.

That last point makes it a deal-breaker because it doubles the burden on the maintainers, encouraging the use of reflective coding style for `enum`s that happen to have sub-16-bit values while using the traditional non-reflective style for `enum`s having 16-bit and greater values.

I prefer we avoid carrying two programming styles for the same concept (enum), as it avoids confusion and keeps things clearer for future contributors as well.  

We will wait until a better implementation of reflective `enum` emerges that supports the full value range without compromises, either from the community or via the language standard itself.

### CODE REVIEW

**Comment by shermp** [comment]
Good idea, especially since it does not support older compilers that are otherwise C++17 capable such as GCC 8.

**Comment by kcgen** [comment]
> Good idea, especially since it does not support older compilers that are otherwise C++17 capable such as GCC 8.

Thanks @shermp; I agree. When I tried to enum the codepage pages with `magic_enum`, I hit the -128..127 limitation and I realized it wasn't a complete a solution as I expected. Combined with the recent compiler issues, it was enough to make me pull it out on the spot.

**Review by johnnovak — APPROVED** [review]
Given these limitations, it's probably for the better. I agree it's just not worth it for all the complexity it introduces into the codebase overall. What bothered me about it was that you cannot easily (or at all?) use valid C++ keywords as enum values with it, and AFAIK it cannot do automatic (de)capitalisation (e.g. to map "auto" to SomeEnum::Auto, for example).

**Comment by nemo93** [comment]
Seems like I'll be able to proceed on testing latest `main` on Retropie/Pi. This is brilliant. Thanks a lot.

**Pull request merged**
